include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FBEnhancerPrefs
FBEnhancerPrefs_FILES = FBEnhancerPrefsListController.m
FBEnhancerPrefs_INSTALL_PATH = /Library/PreferenceBundles

FBEnhancerPrefs_FRAMEWORKS = UIKit
FBEnhancerPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk