include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AutoACPrefs

AutoACPrefs_FILES = AutoACRootListController.m
AutoACPrefs_FRAMEWORKS = UIKit
AutoACPrefs_PRIVATE_FRAMEWORKS = Preferences
AutoACPrefs_INSTALL_PATH = /Library/PreferenceBundles
AutoACPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
