  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC121googlemac_iPhone_YouTube_YouTube_Features_Reel_Presentation_Sources_Factory_ReelWatchNavigationActionFactory_Impl_ImplLibP33_B284F99CB7692FA99849DE65EF232A1D27ReelWatchOfflineInterceptor_h
#define _TtC121googlemac_iPhone_YouTube_YouTube_Features_Reel_Presentation_Sources_Factory_ReelWatchNavigationActionFactory_Impl_ImplLibP33_B284F99CB7692FA99849DE65EF232A1D27ReelWatchOfflineInterceptor_h
@import Foundation;

#include "YTNavigationActionProtocol-Protocol.h"
#include "YTNavigationInterceptor-Protocol.h"

@class NSObject;

@interface _TtC121googlemac_iPhone_YouTube_YouTube_Features_Reel_Presentation_Sources_Factory_ReelWatchNavigationActionFactory_Impl_ImplLibP33_B284F99CB7692FA99849DE65EF232A1D27ReelWatchOfflineInterceptor : NSObject <YTNavigationInterceptor> // (Swift)

/* instance methods */
- (void)interceptWithAction:(<YTNavigationActionProtocol> *)action completionHandler:(id /* block */)handler;
- (id)init;

@end

#endif /* _TtC121googlemac_iPhone_YouTube_YouTube_Features_Reel_Presentation_Sources_Factory_ReelWatchNavigationActionFactory_Impl_ImplLibP33_B284F99CB7692FA99849DE65EF232A1D27ReelWatchOfflineInterceptor_h */
