//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC92googlemac_iPhone_Shared_Identity_AccountSettings_AccountUI_Impl_AccountUIServiceImpl_ImplLib20AccountUIServiceImpl_h
#define _TtC92googlemac_iPhone_Shared_Identity_AccountSettings_AccountUI_Impl_AccountUIServiceImpl_ImplLib20AccountUIServiceImpl_h
@import Foundation;

#include "ASMAccountUIService-Protocol.h"
#include "ASMAccountUIServicePush-Protocol.h"
#include "ASMLink.h"
#include "ASMLoggerModel-Protocol.h"
#include "ASMSessionID-Protocol.h"

@class NSObject, UIViewController, googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift;

@interface _TtC92googlemac_iPhone_Shared_Identity_AccountSettings_AccountUI_Impl_AccountUIServiceImpl_ImplLib20AccountUIServiceImpl : NSObject <ASMAccountUIService, ASMAccountUIServicePush> { // (Swift)
    /* instance variables */
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift browserOpener;
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift octarineService;
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift phenotypeFlagService;
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift accountServiceInjector;
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift loggerModelInjector;
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift sessionServiceInjector;
}

/* class methods */
+ (void)launchGoogleAccountFromViewController:(UIViewController *)controller link:(ASMLink *)link loggerModel:(<ASMLoggerModel> *)model sessionID:(<ASMSessionID> *)id animated:(_Bool)animated pushIfPossible:(_Bool)possible dismissalHandler:(id /* block */)handler completionHandler:((void (^)((id /* block */)self (NSDictionary *)id)))handler;

/* instance methods */
- (void)presentScreenFromViewController:(id)controller animated:(_Bool)animated params:(id)params;
- (void)pushScreenToNavigationController:(id)controller animated:(_Bool)animated params:(id)params;
- (id)init;

@end

#endif /* _TtC92googlemac_iPhone_Shared_Identity_AccountSettings_AccountUI_Impl_AccountUIServiceImpl_ImplLib20AccountUIServiceImpl_h */
