  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC31third_party_swift_Lottie_Lottie16AnimationSubview_h
#define _TtC31third_party_swift_Lottie_Lottie16AnimationSubview_h
@import Foundation;

@class UIView;

@interface _TtC31third_party_swift_Lottie_Lottie16AnimationSubview : UIView // (Swift)

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC31third_party_swift_Lottie_Lottie16AnimationSubview_h */
