  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC105googlemac_iPhone_Shared_Notifications_Services_Communication_Implementation_ServiceImplementation_ImplLib37CommunicationNotificationsServiceImpl_h
#define _TtC105googlemac_iPhone_Shared_Notifications_Services_Communication_Implementation_ServiceImplementation_ImplLib37CommunicationNotificationsServiceImpl_h
@import Foundation;

#include "GNPCommunicationNotificationsService-Protocol.h"

@class DispatchQueue, NSObject, Swift.Bool, _$sSSSg, _$sScTyyt _$ss5NeverOMn ?, _$sSo17GNPStreamzService_p, _$sSo20NSURLSessionDataTaskCSg, _$sSo21GINInteractionService_p, _$sSo21GNPURLSessionProvider_p, _$sSo21UNNotificationContentCSg, _$sSo25GNPPayloadAssemblyService_p, _$sSo33NFDCTextCommunicationNotificationC, _$sSo7INImageCSg, googlemac_iPhone_Shared_Notifications_Services_Communication_API_HandlerAPI.CommunicationNotificationsHandler ?, googlemac_iPhone_Shared_Notifications_Services_Communication_Implementation_ServiceImplementation_ImplLib.AtomicIntentWrapper, googlemac_iPhone_Shared_Notifications_Services_Communication_Implementation_ServiceImplementation_ImplLib.CommunicationNotificationsServiceImpl.ImageType ?;

@interface _TtC105googlemac_iPhone_Shared_Notifications_Services_Communication_Implementation_ServiceImplementation_ImplLib37CommunicationNotificationsServiceImpl : NSObject <GNPCommunicationNotificationsService> { // (Swift)
    /* instance variables */
    googlemac_iPhone_Shared_Notifications_Services_Communication_API_HandlerAPI.CommunicationNotificationsHandler ? providerHandler;
    _$sSo25GNPPayloadAssemblyService_p payloadAssemblyService;
    _$sSo21GNPURLSessionProvider_p urlSessionProvider;
    _$sSo21GINInteractionService_p interactionService;
    _$sSo17GNPStreamzService_p streamzService;
    _$sSSSg clientID;
    _$sScTyyt _$ss5NeverOMn ? task;
    _$sSo33NFDCTextCommunicationNotificationC communicationNotification;
    googlemac_iPhone_Shared_Notifications_Services_Communication_Implementation_ServiceImplementation_ImplLib.CommunicationNotificationsServiceImpl.ImageType ? imageType;
    Swift.Bool hasImage;
    _$sSo20NSURLSessionDataTaskCSg imageDownloadTask;
    googlemac_iPhone_Shared_Notifications_Services_Communication_Implementation_ServiceImplementation_ImplLib.AtomicIntentWrapper intent;
    _$sSo21UNNotificationContentCSg notificationContent;
    _$sSo7INImageCSg fallbackImage;
    Swift.Bool shouldSkipInteractionDonationWait;
    Swift.Bool completionHandlerCalled;
    DispatchQueue completionHandlerCallQueue;
}

/* instance methods */
- (void)updateContentFromCommunicationNotification:(id)notification notificationContent:(id)content completionHandler:(id /* block */)handler;
- (void)serviceExtensionTimeWillExpire;
- (id)init;

@end

#endif /* _TtC105googlemac_iPhone_Shared_Notifications_Services_Communication_Implementation_ServiceImplementation_ImplLib37CommunicationNotificationsServiceImpl_h */
