@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ACTPinger_h
#define ACTPinger_h
@import Foundation;

#include "ACTPingerDelegate-Protocol.h"
#include "NSURLConnectionDelegate-Protocol.h"

@class NSDate, NSMutableData, NSObject, NSString, NSURLConnection, NSURLRequest, NSURLResponse;

@interface ACTPinger : NSObject <NSURLConnectionDelegate>

@property (copy, nonatomic) NSURLRequest *request;
@property (retain, nonatomic) NSURLConnection *connection;
@property (retain, nonatomic) NSURLResponse *response;
@property (retain, nonatomic) NSMutableData *receivedData;
@property (nonatomic) unsigned long long remainingRetryCount;
@property (retain, nonatomic) NSDate *staleDate;
@property (nonatomic) _Bool modifiedForRetry;
@property (retain, nonatomic) id <ACTPingerDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)pingerWithRequestString:(id)string retryParameters:(id)parameters;

/* instance methods */
- (id)parameters;
- (id)requestString;
- (id)initWithRequest:(id)request;
- (void)dealloc;
- (_Bool)isEqual:(id)equal;
- (void)ping;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)connection:(id)connection didReceiveData:(id)data;
- (id)retryQueue;
- (id)pingerStore;
- (void)connectionDidFinishLoading:(id)loading;
- (void)handleFailureWithError:(id)error;
- (void)connection:(id)connection didFailWithError:(id)error;
- (_Bool)shouldRetry;
- (void)appendRetryParameter;
- (_Bool)isModifiedForRetry;

@end

#endif /* ACTPinger_h */
