  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ADSAPIEngageRootIds_SalesCrmComparisonGroup_h
#define ADSAPIEngageRootIds_SalesCrmComparisonGroup_h
@import Foundation;

#include "GPBMessage.h"

@interface ADSAPIEngageRootIds_SalesCrmComparisonGroup : GPBMessage

@property (nonatomic) long long salesCrmComparisonGroupType;
@property (nonatomic) _Bool hasSalesCrmComparisonGroupType;
@property (nonatomic) long long salesCrmUserRoleId;
@property (nonatomic) _Bool hasSalesCrmUserRoleId;

/* class methods */
+ (id)descriptor;

@end

#endif /* ADSAPIEngageRootIds_SalesCrmComparisonGroup_h */
