//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ADSAPIGetResponse_ColumnHeader_FullType_h
#define ADSAPIGetResponse_ColumnHeader_FullType_h
@import Foundation;

#include "GPBMessage.h"

@class NSMutableArray, NSString;

@interface ADSAPIGetResponse_ColumnHeader_FullType : GPBMessage

@property (nonatomic) int type;
@property (nonatomic) _Bool hasType;
@property (copy, nonatomic) NSString *typeName;
@property (nonatomic) _Bool hasTypeName;
@property (retain, nonatomic) NSMutableArray *tupleElementTypesArray;
@property (readonly, nonatomic) unsigned long long tupleElementTypesArray_Count;

/* class methods */
+ (id)descriptor;

@end

#endif /* ADSAPIGetResponse_ColumnHeader_FullType_h */
