  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ADSAPIEngageRootIds_SupportCasesCaseRootIds_h
#define ADSAPIEngageRootIds_SupportCasesCaseRootIds_h
@import Foundation;

#include "ADSAPIEngageRootIds_SupportCasesCaseTargets.h"
#include "GPBInt64Array.h"
#include "GPBMessage.h"

@class NSMutableArray, NSString;

@interface ADSAPIEngageRootIds_SupportCasesCaseRootIds : GPBMessage

@property (retain, nonatomic) NSMutableArray *supportCasesCaseKeysArray;
@property (readonly, nonatomic) unsigned long long supportCasesCaseKeysArray_Count;
@property (retain, nonatomic) ADSAPIEngageRootIds_SupportCasesCaseTargets *supportCasesCaseTargets;
@property (nonatomic) _Bool hasSupportCasesCaseTargets;
@property (retain, nonatomic) GPBInt64Array *supportCasesPoolIdsArray;
@property (readonly, nonatomic) unsigned long long supportCasesPoolIdsArray_Count;
@property (copy, nonatomic) NSString *supportCasesCaseOrganization;
@property (nonatomic) _Bool hasSupportCasesCaseOrganization;
@property (copy, nonatomic) NSString *supportCasesAuthenticatedCustomerContactEmail;
@property (nonatomic) _Bool hasSupportCasesAuthenticatedCustomerContactEmail;

/* class methods */
+ (id)descriptor;

@end

#endif /* ADSAPIEngageRootIds_SupportCasesCaseRootIds_h */
