  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ASDKViewController_h
#define ASDKViewController_h
@import Foundation;

#include "ASDisplayNode.h"
#include "ASVisibilityDepth-Protocol.h"

@class NSString, UIViewController;

@interface ASDKViewController : UIViewController <ASVisibilityDepth> {
    /* instance variables */
    _Bool _ensureDisplayed;
    _Bool _automaticallyAdjustRangeModeBasedOnViewEvents;
    _Bool _parentManagesVisibilityDepth;
    long long _visibilityDepth;
    _Bool _selfConformsToRangeModeProtocol;
    _Bool _nodeConformsToRangeModeProtocol;
    struct UIEdgeInsets { double top; double left; double bottom; double right; } _fallbackAdditionalSafeAreaInsets;
}

@property (readonly, nonatomic) ASDisplayNode *node;
@property (copy, nonatomic) id /* block */ overrideDisplayTraitsWithTraitCollection;
@property (copy, nonatomic) id /* block */ overrideDisplayTraitsWithWindowSize;
@property (readonly, nonatomic) unsigned char interfaceState;
@property (nonatomic) _Bool neverShowPlaceholders;
@property (nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } additionalSafeAreaInsets;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (id)initWithCoder:(id)coder;
- (id)initWithNode:(id)node;
- (id)init;
- (void)_initializeInstance;
- (void)dealloc;
- (void)loadView;
- (void)viewWillLayoutSubviews;
- (void)viewDidLayoutSubviews;
- (void)_updateNodeFallbackSafeArea;
- (void)didMoveToParentViewController:(id)controller;
- (void)viewWillAppear:(_Bool)appear;
- (void)setVisibilityDepth:(unsigned long long)depth;
- (void)viewDidDisappear:(_Bool)disappear;
- (long long)visibilityDepth;
- (void)visibilityDepthDidChange;
- (_Bool)automaticallyAdjustRangeModeBasedOnViewEvents;
- (void)setAutomaticallyAdjustRangeModeBasedOnViewEvents:(_Bool)events;
- (void)updateCurrentRangeModeWithModeIfPossible:(signed char)possible;
- (struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })nodeConstrainedSize;
- (struct { long long x0; long long x1; double x2; long long x3; long long x4; long long x5; long long x6; long long x7; id x8; struct CGSize { double x0; double x1; } x9; long long x10; long long x11; long long x12; })primitiveTraitCollectionForUITraitCollection:(id)collection;
- (void)propagateNewTraitCollection:(struct { long long x0; long long x1; double x2; long long x3; long long x4; long long x5; long long x6; long long x7; id x8; struct CGSize { double x0; double x1; } x9; long long x10; long long x11; long long x12; })collection;
- (void)traitCollectionDidChange:(id)change;
- (void)didRotateFromInterfaceOrientation:(long long)orientation;

@end

#endif /* ASDKViewController_h */
