//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ASMExtra_h
#define ASMExtra_h
@import Foundation;

#include "ASMBoolArray.h"
#include "ASMByteArray.h"
#include "ASMCharArray.h"
#include "ASMDoubleArray.h"
#include "ASMFloatArray.h"
#include "ASMIntArray.h"
#include "ASMLongArray.h"
#include "ASMShortArray.h"
#include "ASMStringArray.h"
#include "GPBMessage.h"

@class NSString;

@interface ASMExtra : GPBMessage

@property (readonly, nonatomic) int extraTypeOneOfCase;
@property (copy, nonatomic) NSString *stringValue;
@property (nonatomic) _Bool hasStringValue;
@property (retain, nonatomic) ASMStringArray *stringArrayValue;
@property (nonatomic) _Bool hasStringArrayValue;
@property (nonatomic) _Bool booleanValue;
@property (nonatomic) _Bool hasBooleanValue;
@property (retain, nonatomic) ASMBoolArray *booleanArrayValue;
@property (nonatomic) _Bool hasBooleanArrayValue;
@property (nonatomic) int charValue;
@property (nonatomic) _Bool hasCharValue;
@property (retain, nonatomic) ASMCharArray *charArrayValue;
@property (nonatomic) _Bool hasCharArrayValue;
@property (nonatomic) int byteValue;
@property (nonatomic) _Bool hasByteValue;
@property (retain, nonatomic) ASMByteArray *byteArrayValue;
@property (nonatomic) _Bool hasByteArrayValue;
@property (nonatomic) int shortValue;
@property (nonatomic) _Bool hasShortValue;
@property (retain, nonatomic) ASMShortArray *shortArrayValue;
@property (nonatomic) _Bool hasShortArrayValue;
@property (nonatomic) int intValue;
@property (nonatomic) _Bool hasIntValue;
@property (retain, nonatomic) ASMIntArray *intArrayValue;
@property (nonatomic) _Bool hasIntArrayValue;
@property (nonatomic) double doubleValue;
@property (nonatomic) _Bool hasDoubleValue;
@property (retain, nonatomic) ASMDoubleArray *doubleArrayValue;
@property (nonatomic) _Bool hasDoubleArrayValue;
@property (nonatomic) float floatValue;
@property (nonatomic) _Bool hasFloatValue;
@property (retain, nonatomic) ASMFloatArray *floatArrayValue;
@property (nonatomic) _Bool hasFloatArrayValue;
@property (nonatomic) long long longValue;
@property (nonatomic) _Bool hasLongValue;
@property (retain, nonatomic) ASMLongArray *longArrayValue;
@property (nonatomic) _Bool hasLongArrayValue;

/* class methods */
+ (id)descriptor;

@end

#endif /* ASMExtra_h */
