  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ASTableLayoutController_h
#define ASTableLayoutController_h
@import Foundation;

#include "ASAbstractLayoutController.h"

@class UITableView;

@interface ASTableLayoutController : ASAbstractLayoutController

@property (readonly, weak, nonatomic) UITableView *tableView;

/* instance methods */
- (id)initWithTableView:(id)view;
- (id)elementsForScrolling:(unsigned char)scrolling rangeMode:(signed char)mode rangeType:(long long)type map:(id)map;
- (void)allElementsForScrolling:(unsigned char)scrolling rangeMode:(signed char)mode displaySet:(id *)set preloadSet:(id *)set map:(id)map;

@end

#endif /* ASTableLayoutController_h */
