@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ASTCTProvider_h
#define ASTCTProvider_h
@import Foundation;

#include "ASTCTAndroidAppInfo.h"
#include "ASTCTCastAppInfo.h"
#include "ASTCTChromeOsAppInfo.h"
#include "ASTCTCloudProviderInfo.h"
#include "ASTCTHomeAppInfo.h"
#include "ASTCTInternalProviderInfo.h"
#include "ASTCTIosAppInfo.h"
#include "ASTCTKaiOsAppInfo.h"
#include "ASTCTSipProviderInfo.h"
#include "ASTCTWebProviderInfo.h"
#include "GPBMessage.h"

@class NSString;

@interface ASTCTProvider : GPBMessage

@property (readonly, nonatomic) int typeOneOfCase;
@property (retain, nonatomic) ASTCTAndroidAppInfo *androidAppInfo;
@property (nonatomic) _Bool hasAndroidAppInfo;
@property (retain, nonatomic) ASTCTCastAppInfo *castAppInfo;
@property (nonatomic) _Bool hasCastAppInfo;
@property (retain, nonatomic) ASTCTCloudProviderInfo *cloudProviderInfo;
@property (nonatomic) _Bool hasCloudProviderInfo;
@property (retain, nonatomic) ASTCTSipProviderInfo *sipProviderInfo;
@property (nonatomic) _Bool hasSipProviderInfo;
@property (retain, nonatomic) ASTCTIosAppInfo *iosAppInfo;
@property (nonatomic) _Bool hasIosAppInfo;
@property (retain, nonatomic) ASTCTInternalProviderInfo *internalProviderInfo;
@property (nonatomic) _Bool hasInternalProviderInfo;
@property (retain, nonatomic) ASTCTWebProviderInfo *webProviderInfo;
@property (nonatomic) _Bool hasWebProviderInfo;
@property (retain, nonatomic) ASTCTKaiOsAppInfo *kaiosAppInfo;
@property (nonatomic) _Bool hasKaiosAppInfo;
@property (retain, nonatomic) ASTCTHomeAppInfo *homeAppInfo;
@property (nonatomic) _Bool hasHomeAppInfo;
@property (retain, nonatomic) ASTCTChromeOsAppInfo *chromeosAppInfo;
@property (nonatomic) _Bool hasChromeosAppInfo;
@property (copy, nonatomic) NSString *iconImageURL;
@property (nonatomic) _Bool hasIconImageURL;
@property (copy, nonatomic) NSString *fallbackURL;
@property (nonatomic) _Bool hasFallbackURL;

/* class methods */
+ (id)descriptor;

@end

#endif /* ASTCTProvider_h */
