  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BuyflowRefreshResponse_h
#define BuyflowRefreshResponse_h
@import Foundation;

#include "BuyflowPage.h"
#include "GPBMessage.h"
#include "OrchResponseContext.h"
#include "OrchSecureDataHeader.h"
#include "OrchUiError.h"

@class NSMutableArray;

@interface BuyflowRefreshResponse : GPBMessage

@property (retain, nonatomic) OrchUiError *error;
@property (nonatomic) _Bool hasError;
@property (retain, nonatomic) OrchResponseContext *context;
@property (nonatomic) _Bool hasContext;
@property (retain, nonatomic) OrchSecureDataHeader *secureHeader;
@property (nonatomic) _Bool hasSecureHeader;
@property (retain, nonatomic) BuyflowPage *nextPage;
@property (nonatomic) _Bool hasNextPage;
@property (retain, nonatomic) NSMutableArray *overflowMenuOptionArray;
@property (readonly, nonatomic) unsigned long long overflowMenuOptionArray_Count;

/* class methods */
+ (id)descriptor;

@end

#endif /* BuyflowRefreshResponse_h */
