  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef CAVISMeasuredAdsPosition_h
#define CAVISMeasuredAdsPosition_h
@import Foundation;

#include "GPBMessage.h"

@interface CAVISMeasuredAdsPosition : GPBMessage

@property (nonatomic) int top;
@property (nonatomic) _Bool hasTop;
@property (nonatomic) int right;
@property (nonatomic) _Bool hasRight;
@property (nonatomic) int bottom;
@property (nonatomic) _Bool hasBottom;
@property (nonatomic) int left;
@property (nonatomic) _Bool hasLeft;

/* class methods */
+ (id)descriptor;

@end

#endif /* CAVISMeasuredAdsPosition_h */
