//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef CHRVoiceShortcutCenter_h
#define CHRVoiceShortcutCenter_h
@import Foundation;

#include "OS_dispatch_queue-Protocol.h"

@class NSArray, NSObject;

@interface CHRVoiceShortcutCenter : NSObject

@property (retain, nonatomic) NSArray *relevantSiriShortcuts;
@property (retain, nonatomic) NSArray *relevantWidgetSuggestions;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *voiceShortcutCenterAccessQueue;

/* class methods */
+ (id)sharedVoiceShortcutCenter;

/* instance methods */
- (id)initPrivate;
- (void)getAllVoiceShortcutsWithCompletion:(id /* block */)completion;
- (void)getVoiceShortcutWithIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)setShortcutSuggestions:(id)suggestions;
- (void)setRelevantSiriShortcuts:(id)shortcuts completionHandler:(id /* block */)handler;
- (void)setRelevantWidgetSuggestions:(id)suggestions completionHandler:(id /* block */)handler;

@end

#endif /* CHRVoiceShortcutCenter_h */
