  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef CSHMContactForm_h
#define CSHMContactForm_h
@import Foundation;

#include "CSHMC2CConfiguration.h"
#include "GPBMessage.h"

@class NSMutableArray, NSString;

@interface CSHMContactForm : GPBMessage

@property (copy, nonatomic) NSString *id_p;
@property (nonatomic) _Bool hasId_p;
@property (retain, nonatomic) NSMutableArray *emailAddressesArray;
@property (readonly, nonatomic) unsigned long long emailAddressesArray_Count;
@property (retain, nonatomic) NSMutableArray *fieldsArray;
@property (readonly, nonatomic) unsigned long long fieldsArray_Count;
@property (copy, nonatomic) NSString *subjectLineFieldId;
@property (nonatomic) _Bool hasSubjectLineFieldId;
@property (copy, nonatomic) NSString *bodyTextFieldId;
@property (nonatomic) _Bool hasBodyTextFieldId;
@property (copy, nonatomic) NSString *confirmationMessage;
@property (nonatomic) _Bool hasConfirmationMessage;
@property (copy, nonatomic) NSString *submitButtonText;
@property (nonatomic) _Bool hasSubmitButtonText;
@property (copy, nonatomic) NSString *title;
@property (nonatomic) _Bool hasTitle;
@property (copy, nonatomic) NSString *intro;
@property (nonatomic) _Bool hasIntro;
@property (copy, nonatomic) NSString *validationInfo;
@property (nonatomic) _Bool hasValidationInfo;
@property (nonatomic) _Bool returnCaseId;
@property (nonatomic) _Bool hasReturnCaseId;
@property (nonatomic) _Bool isSearchable;
@property (nonatomic) _Bool hasIsSearchable;
@property (nonatomic) _Bool hasMultiplePages;
@property (nonatomic) _Bool hasHasMultiplePages;
@property (retain, nonatomic) NSMutableArray *languageArray;
@property (readonly, nonatomic) unsigned long long languageArray_Count;
@property (nonatomic) int totalPages;
@property (nonatomic) _Bool hasTotalPages;
@property (nonatomic) int connectorType;
@property (nonatomic) _Bool hasConnectorType;
@property (retain, nonatomic) NSMutableArray *supportedLanguageOverrideArray;
@property (readonly, nonatomic) unsigned long long supportedLanguageOverrideArray_Count;
@property (retain, nonatomic) NSMutableArray *prevalidationErrorArray;
@property (readonly, nonatomic) unsigned long long prevalidationErrorArray_Count;
@property (retain, nonatomic) CSHMC2CConfiguration *c2CConfiguration;
@property (nonatomic) _Bool hasC2CConfiguration;
@property (copy, nonatomic) NSString *internalDescription;
@property (nonatomic) _Bool hasInternalDescription;

/* class methods */
+ (id)descriptor;

@end

#endif /* CSHMContactForm_h */
