  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef CSHMDynamicColorSettings_h
#define CSHMDynamicColorSettings_h
@import Foundation;

#include "CSHMDynamicColorThemePalette.h"
#include "GPBMessage.h"

@interface CSHMDynamicColorSettings : GPBMessage

@property (retain, nonatomic) CSHMDynamicColorThemePalette *light;
@property (nonatomic) _Bool hasLight;
@property (retain, nonatomic) CSHMDynamicColorThemePalette *dark;
@property (nonatomic) _Bool hasDark;

/* class methods */
+ (id)descriptor;

@end

#endif /* CSHMDynamicColorSettings_h */
