//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef DIALResponse_h
#define DIALResponse_h
@import Foundation;

@class NSDate, NSDictionary, NSObject, NSString;

@interface DIALResponse : NSObject

@property (readonly, nonatomic) _Bool mdx_inAppDIAL;
@property (readonly, nonatomic) NSDate *mdx_smartRemoteRequestTime;
@property (readonly, nonatomic) NSString *mdx_screenID;
@property (readonly, nonatomic) NSString *mdx_deviceID;
@property (readonly, nonatomic) NSString *mdx_loungeToken;
@property (readonly, nonatomic) double mdx_loungeTokenRefreshInterval;
@property (readonly, nonatomic) NSString *mdx_theme;
@property (readonly, nonatomic) NSString *mdx_signInSessionID;
@property (readonly, nonatomic) NSString *mdx_seamlessSessionID;
@property (readonly, nonatomic) NSString *mdx_passiveSessionID;
@property (readonly, nonatomic) NSString *mdx_brand;
@property (readonly, nonatomic) NSString *mdx_model;
@property (readonly, nonatomic) NSString *mdx_proberData;
@property (nonatomic) long long status;
@property (nonatomic) _Bool stoppable;
@property (copy, nonatomic) NSString *instanceURLString;
@property (nonatomic) _Bool castSupported;
@property (copy, nonatomic) NSDictionary *additionalData;

/* instance methods */
- (_Bool)mdx_isInAppDIAL;
- (_Bool)isStoppable;
- (_Bool)isCastSupported;

@end

#endif /* DIALResponse_h */
