@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef DTASN1Parser_h
#define DTASN1Parser_h
@import Foundation;

#include "DTASN1ParserDelegate-Protocol.h"

@class NSData, NSDateFormatter, NSError, NSObject;

@interface DTASN1Parser : NSObject {
    /* instance variables */
    NSData *_data;
    unsigned long long _dataLength;
    unsigned long long _parseLevel;
    _Bool _abortParsing;
    NSDateFormatter *_UTCFormatter;
    struct { unsigned int delegateSupportsDocumentStart:1; unsigned int delegateSupportsDocumentEnd:1; unsigned int delegateSupportsContainerStart:1; unsigned int delegateSupportsContainerEnd:1; unsigned int delegateSupportsContextStart:1; unsigned int delegateSupportsContextEnd:1; unsigned int delegateSupportsString:1; unsigned int delegateSupportsInteger:1; unsigned int delegateSupportsData:1; unsigned int delegateSupportsBitString:1; unsigned int delegateSupportsNumber:1; unsigned int delegateSupportsNull:1; unsigned int delegateSupportsError:1; unsigned int delegateSupportsDate:1; unsigned int delegateSupportsObjectIdentifier:1; } _delegateFlags;
}

@property (weak, nonatomic) id <DTASN1ParserDelegate> delegate;
@property (readonly, nonatomic) NSError *parserError;

/* instance methods */
- (id)initWithData:(id)data;
- (void)_parseErrorEncountered:(id)encountered;
- (unsigned long long)_parseLengthAtLocation:(unsigned long long)location lengthOfLength:(unsigned long long *)length;
- (_Bool)_parseValueWithTag:(unsigned long long)tag dataRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (_Bool)_parseRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (_Bool)parse;
- (void)abortParsing;

@end

#endif /* DTASN1Parser_h */
