  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef DUIRootViewController_h
#define DUIRootViewController_h
@import Foundation;

#include "DUIActionServiceImpl.h"
#include "DUIRootViewControllerDelegate-Protocol.h"
#include "DUISectionViewModel.h"
#include "DUITreeViewController.h"
#include "DUITreeViewControllerDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, UINavigationBar, UIView, UIViewController;

@interface DUIRootViewController : UIViewController <DUITreeViewControllerDelegate> {
    /* instance variables */
    DUITreeViewController *_treeViewController;
    DUISectionViewModel *_topAppBarSectionViewModel;
    int _firstSection;
    DUIActionServiceImpl *_actionService;
    NSLayoutConstraint *_dynamicUIBottomConstraint;
    NSLayoutConstraint *_dynamicUIHeightConstraint;
    UINavigationBar *_navigationBar;
    id <DUIRootViewControllerDelegate> _rootViewControllerDelegate;
    _Bool isDynamicUITriggered;
    UIView *_backgroundView;
    UIView *_containerView;
    UIView *_safeAreaView;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)backgroundColor;

/* instance methods */
- (id)initWithUiTree:(id)tree flowServiceDelegate:(id)delegate rootViewControllerDelegate:(id)delegate;
- (void)viewDidLoad;
- (void)addTapGesture;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewDidDisappear:(_Bool)disappear;
- (void)viewDidLayoutSubviews;
- (void)performAction:(id)action;
- (void)addNavigationViewController;
- (void)renderTopAppBar;
- (void)updateMaskOfNavigationBar;
- (void)triggerDynamicUI;
- (void)closeBottomSheet;
- (void)keyboardWillShowWithNotification:(id)notification;
- (void)keyboardWillHideWithNotification:(id)notification;
- (void)treeViewController:(id)controller didUpdateContentWithHeight:(double)height;
- (void)treeViewControllerDidDismiss:(id)dismiss;
- (void)renderedTemplateWithNodeIdentifier:(int)identifier sectionIdentifier:(int)identifier;

@end

#endif /* DUIRootViewController_h */
