//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ELMCapabilitiesStore_h
#define ELMCapabilitiesStore_h
@import Foundation;

@class NSObject;

@interface ELMCapabilitiesStore : NSObject {
    /* instance variables */
    struct Handle<std::shared_ptr<youtube::elements::interfaces::CapabilitiesStore>, std::shared_ptr<youtube::elements::interfaces::CapabilitiesStore>> { struct shared_ptr<djinni::ProxyCache<djinni::CppProxyCacheTraits>::Pimpl> { struct Pimpl *__ptr_; struct __shared_weak_count *__cntrl_; } m_cache; struct shared_ptr<youtube::elements::interfaces::CapabilitiesStore> { struct CapabilitiesStore *__ptr_; struct __shared_weak_count *__cntrl_; } m_obj; } _cppRefHandle;
}

/* class methods */
+ (id)instance;
+ (id)create:(_Bool)create preferCachedValues:(_Bool)values isCapsStreamParsingEnabled:(_Bool)enabled;

/* instance methods */
- (id)initWithCpp:(const void *)cpp;
- (void)setPreloader:(id)preloader;
- (id)getCapabilitiesLoader;
- (id)getCapabilitiesBytes:(id)bytes ensureLoaded:(_Bool)loaded;

@end

#endif /* ELMCapabilitiesStore_h */
