  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ELMPerformanceJSONAgent_h
#define ELMPerformanceJSONAgent_h
@import Foundation;

#include "ELMPerformanceAgent-Protocol.h"

@class NSMutableArray, NSObject, NSString, NSURL;

@interface ELMPerformanceJSONAgent : NSObject <ELMPerformanceAgent> {
    /* instance variables */
    NSURL *_outPath;
    NSMutableArray *_traceEvents;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)didReceiveMeasurementEvents:(id)events;
- (long long)ignoredEventTypes;
- (id)traceEventsFormatFromELMPerformanceEvent:(id)event;
- (id)argsFromELMPerformanceEvent:(id)event;
- (id)queueForEvents;

@end

#endif /* ELMPerformanceJSONAgent_h */
