//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ELMPBCompactVideoModel_h
#define ELMPBCompactVideoModel_h
@import Foundation;

#include "ELMPBCommand.h"
#include "ELMPBCompactVideoData.h"
#include "ELMPBContext.h"
#include "ELMPBEnvironmentData.h"
#include "ELMPBTheme.h"
#include "GPBMessage.h"
#include "YTDownloadsElementVideoModel-Protocol.h"
#include "YTILoggingDirectives.h"
#include "YTIRenderer.h"

@class NSData, NSString;

@interface ELMPBCompactVideoModel : GPBMessage <YTDownloadsElementVideoModel>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) ELMPBCompactVideoData *compactVideoData;
@property (nonatomic) _Bool hasCompactVideoData;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;
@property (retain, nonatomic) YTILoggingDirectives *loggingDirectives;
@property (nonatomic) _Bool hasLoggingDirectives;
@property (retain, nonatomic) ELMPBTheme *theme;
@property (nonatomic) _Bool hasTheme;
@property (retain, nonatomic) ELMPBContext *context;
@property (nonatomic) _Bool hasContext;
@property (retain, nonatomic) ELMPBEnvironmentData *environment;
@property (nonatomic) _Bool hasEnvironment;
@property (retain, nonatomic) ELMPBCommand *logLongPressCommand;
@property (nonatomic) _Bool hasLogLongPressCommand;
@property (retain, nonatomic) ELMPBCommand *previewTooltipCommand;
@property (nonatomic) _Bool hasPreviewTooltipCommand;
@property (retain, nonatomic) ELMPBCommand *logMenuClickCommand;
@property (nonatomic) _Bool hasLogMenuClickCommand;
@property (nonatomic) _Bool usePanelBackgroundColor;
@property (nonatomic) _Bool hasUsePanelBackgroundColor;
@property (copy, nonatomic) NSString *updatableCompactVideoRefreshKey;
@property (nonatomic) _Bool hasUpdatableCompactVideoRefreshKey;
@property (retain, nonatomic) ELMPBCommand *updatableCompactVideoRefreshCommand;
@property (nonatomic) _Bool hasUpdatableCompactVideoRefreshCommand;
@property (copy, nonatomic) NSString *targetItemSection;
@property (nonatomic) _Bool hasTargetItemSection;
@property (retain, nonatomic) YTIRenderer *optimisticRenderer;
@property (nonatomic) _Bool hasOptimisticRenderer;

/* class methods */
+ (id)descriptor;

/* instance methods */
- (id)yt_videoID;

@end

#endif /* ELMPBCompactVideoModel_h */
