  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef EmbeddedSettingsPage_h
#define EmbeddedSettingsPage_h
@import Foundation;

#include "GPBMessage.h"
#include "OrchDependencyGraph.h"
#include "OrchWebViewComponent.h"

@class NSMutableArray, NSString;

@interface EmbeddedSettingsPage : GPBMessage

@property (copy, nonatomic) NSString *title;
@property (nonatomic) _Bool hasTitle;
@property (retain, nonatomic) NSMutableArray *simpleFormArray;
@property (readonly, nonatomic) unsigned long long simpleFormArray_Count;
@property (retain, nonatomic) NSMutableArray *taxInfoFormArray;
@property (readonly, nonatomic) unsigned long long taxInfoFormArray_Count;
@property (retain, nonatomic) NSMutableArray *confirmationDialogArray;
@property (readonly, nonatomic) unsigned long long confirmationDialogArray_Count;
@property (retain, nonatomic) NSMutableArray *cardHeaderArray;
@property (readonly, nonatomic) unsigned long long cardHeaderArray_Count;
@property (retain, nonatomic) NSMutableArray *actionBarArray;
@property (readonly, nonatomic) unsigned long long actionBarArray_Count;
@property (retain, nonatomic) NSMutableArray *componentGroupArray;
@property (readonly, nonatomic) unsigned long long componentGroupArray_Count;
@property (retain, nonatomic) NSMutableArray *dynamicListArray;
@property (readonly, nonatomic) unsigned long long dynamicListArray_Count;
@property (retain, nonatomic) NSMutableArray *integratorCallbackClientDataArray;
@property (readonly, nonatomic) unsigned long long integratorCallbackClientDataArray_Count;
@property (retain, nonatomic) OrchDependencyGraph *dependencyGraph;
@property (nonatomic) _Bool hasDependencyGraph;
@property (retain, nonatomic) NSMutableArray *tableArray;
@property (readonly, nonatomic) unsigned long long tableArray_Count;
@property (retain, nonatomic) NSMutableArray *partialUpdateDataArray;
@property (readonly, nonatomic) unsigned long long partialUpdateDataArray_Count;
@property (retain, nonatomic) NSMutableArray *widgetLinkArray;
@property (readonly, nonatomic) unsigned long long widgetLinkArray_Count;
@property (retain, nonatomic) OrchWebViewComponent *webViewComponent;
@property (nonatomic) _Bool hasWebViewComponent;
@property (retain, nonatomic) NSMutableArray *customerSelectorArray;
@property (readonly, nonatomic) unsigned long long customerSelectorArray_Count;
@property (nonatomic) long long simpleFormScrollToUiReference;
@property (nonatomic) _Bool hasSimpleFormScrollToUiReference;

/* class methods */
+ (id)descriptor;

@end

#endif /* EmbeddedSettingsPage_h */
