//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef FIRAnalyticsConfiguration_h
#define FIRAnalyticsConfiguration_h
@import Foundation;

@class NSObject;

@interface FIRAnalyticsConfiguration : NSObject

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (void)postNotificationName:(id)name value:(id)value;
- (void)setAnalyticsCollectionEnabled:(_Bool)enabled persistSetting:(_Bool)setting;

@end

#endif /* FIRAnalyticsConfiguration_h */
