  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GAIGLAttributionReference_AttributionScore_h
#define GAIGLAttributionReference_AttributionScore_h
@import Foundation;

#include "GAIGLAttributionReference_InputPartReference.h"
#include "GAIGLAttributionReference_OutputPartReference.h"
#include "GAIGLAttributionReference_UnknownPartReference.h"
#include "GPBMessage.h"

@interface GAIGLAttributionReference_AttributionScore : GPBMessage

@property (nonatomic) float attributionScore;
@property (readonly, nonatomic) int partReferenceOneOfCase;
@property (retain, nonatomic) GAIGLAttributionReference_InputPartReference *inputPartReference;
@property (nonatomic) _Bool hasInputPartReference;
@property (retain, nonatomic) GAIGLAttributionReference_OutputPartReference *outputPartReference;
@property (nonatomic) _Bool hasOutputPartReference;
@property (retain, nonatomic) GAIGLAttributionReference_UnknownPartReference *unknownInputPartReference;
@property (nonatomic) _Bool hasUnknownInputPartReference;

/* class methods */
+ (id)descriptor;

@end

#endif /* GAIGLAttributionReference_AttributionScore_h */
