  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GAPITranslatorConfig_h
#define GAPITranslatorConfig_h
@import Foundation;

#include "GPBMessage.h"

@class NSString;

@interface GAPITranslatorConfig : GPBMessage

@property (copy, nonatomic) NSString *selector;
@property (nonatomic) _Bool hasSelector;
@property (nonatomic) _Bool outputAllPrimitiveFieldsToJson;
@property (nonatomic) _Bool hasOutputAllPrimitiveFieldsToJson;
@property (nonatomic) int jspbVariant;
@property (nonatomic) _Bool hasJspbVariant;
@property (nonatomic) int jspbPivot;
@property (nonatomic) _Bool hasJspbPivot;
@property (nonatomic) _Bool jspbAcceptNegativeUnsignedNumber;
@property (nonatomic) _Bool hasJspbAcceptNegativeUnsignedNumber;
@property (nonatomic) _Bool useWebSafeBase64ForByteFields;
@property (nonatomic) _Bool hasUseWebSafeBase64ForByteFields;
@property (nonatomic) _Bool structIntegersAsStrings;
@property (nonatomic) _Bool hasStructIntegersAsStrings;
@property (nonatomic) _Bool addTrailingZerosForTimestampAndDuration;
@property (nonatomic) _Bool hasAddTrailingZerosForTimestampAndDuration;
@property (nonatomic) int jsonTranslationMaxRecursionDepth;
@property (nonatomic) _Bool hasJsonTranslationMaxRecursionDepth;
@property (nonatomic) _Bool dropEmptyFields;
@property (nonatomic) _Bool hasDropEmptyFields;

/* class methods */
+ (id)descriptor;

@end

#endif /* GAPITranslatorConfig_h */
