//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GAPICrossOriginValidation_h
#define GAPICrossOriginValidation_h
@import Foundation;

#include "GPBInt64Array.h"
#include "GPBMessage.h"

@class NSMutableArray, NSString;

@interface GAPICrossOriginValidation : GPBMessage

@property (retain, nonatomic) NSMutableArray *allowedOriginsArray;
@property (readonly, nonatomic) unsigned long long allowedOriginsArray_Count;
@property (retain, nonatomic) NSMutableArray *allowedMethodsArray;
@property (readonly, nonatomic) unsigned long long allowedMethodsArray_Count;
@property (retain, nonatomic) NSMutableArray *allowedHeadersArray;
@property (readonly, nonatomic) unsigned long long allowedHeadersArray_Count;
@property (retain, nonatomic) GPBInt64Array *allowedOriginPenUsersArray;
@property (readonly, nonatomic) unsigned long long allowedOriginPenUsersArray_Count;
@property (copy, nonatomic) NSString *legacyPathPrefix;

/* class methods */
+ (id)descriptor;

@end

#endif /* GAPICrossOriginValidation_h */
