  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.1, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GCAVUpdateVaultRequest_h
#define GCAVUpdateVaultRequest_h
@import Foundation;

#include "GCAVRequestContextData.h"
#include "GCAVVault.h"
#include "GPBFieldMask.h"
#include "GPBMessage.h"

@class NSString;

@interface GCAVUpdateVaultRequest : GPBMessage

@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSString *instanceIdToken;
@property (retain, nonatomic) GCAVVault *vault;
@property (nonatomic) _Bool hasVault;
@property (retain, nonatomic) GPBFieldMask *updateMask;
@property (nonatomic) _Bool hasUpdateMask;
@property (copy, nonatomic) NSString *gcmRegistrationId;
@property (nonatomic) int gmscoreVersion;
@property (retain, nonatomic) GCAVRequestContextData *requestContextData;
@property (nonatomic) _Bool hasRequestContextData;

/* class methods */
+ (id)descriptor;

@end

#endif /* GCAVUpdateVaultRequest_h */
