  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GCKBResourceLoader_h
#define GCKBResourceLoader_h
@import Foundation;

@class NSObject;

@interface GCKBResourceLoader : NSObject {
    /* instance variables */
    Class _bundleClass;
}

/* class methods */
+ (id)dataWithCommentsStripped:(id)stripped;

/* instance methods */
- (id)initForClass:(Class)_class;
- (id)resourceFileAsString:(id)string;
- (id)resourceFileAsString:(id)string stripComments:(_Bool)comments;
- (id)resourceFileAsData:(id)data;
- (id)resourceFileAsJSON:(id)json;
- (id)bundlePathForFile:(id)file;

@end

#endif /* GCKBResourceLoader_h */
