  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GCKConsentScreenResponse_h
#define GCKConsentScreenResponse_h
@import Foundation;

#include "GCKConsentEligibility.h"
#include "GCKConsentScreen.h"
#include "GCKConsentToken-Protocol.h"

@class NSObject;

@interface GCKConsentScreenResponse : NSObject // (Swift)

@property (nonatomic, readonly) GCKConsentEligibility *eligibility;
@property (nonatomic, readonly) GCKConsentScreen *screen;
@property (nonatomic, readonly) id <GCKConsentToken> verificationToken;

/* instance methods */
- (id)initWithConsentScreen:(id)screen eligibility:(id)eligibility verificationToken:(id)token;
- (id)init;

@end

#endif /* GCKConsentScreenResponse_h */
