//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GCKCastDeviceCChordProberBuilder_h
#define GCKCastDeviceCChordProberBuilder_h
@import Foundation;

#include "GCKAnalyticsEventLogger.h"
#include "GCKDatabase.h"
#include "GCKNNetworkReachability.h"
#include "GCKRuntimeConfiguration.h"

@class NSObject;

@interface GCKCastDeviceCChordProberBuilder : NSObject

@property (readonly, nonatomic) GCKAnalyticsEventLogger *analyticsEventLogger;
@property (readonly, nonatomic) GCKDatabase *database;
@property (readonly, nonatomic) GCKNNetworkReachability *networkReachability;
@property (readonly, nonatomic) GCKRuntimeConfiguration *runtimeConfiguration;

/* instance methods */
- (id)initWithDatabase:(id)database analyticsEventLogger:(id)logger networkReachability:(id)reachability runtimeConfiguration:(id)configuration;
- (id)buildWithSocketAddress:(id)address;

@end

#endif /* GCKCastDeviceCChordProberBuilder_h */
