//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GCKDBAppSupportStateInfo_h
#define GCKDBAppSupportStateInfo_h
@import Foundation;

#include "GCKDBDeviceInfo.h"

@class NSManagedObject, NSSet;

@interface GCKDBAppSupportStateInfo : NSManagedObject

@property (retain, nonatomic) NSSet *cachedAppInfos;
@property (retain, nonatomic) GCKDBDeviceInfo *deviceInfo;

/* instance methods */
- (id)cachedAppIDsSupported:(_Bool)supported;
- (long long)supportStateForAppID:(id)id;
- (id)cachedAppInfoWithAppID:(id)id;
- (void)addOrUpdateAppID:(id)id asSupported:(_Bool)supported withTTL:(double)ttl;
- (void)addOrUpdateAppIDs:(id)ids asSupported:(_Bool)supported withTTL:(double)ttl;
- (_Bool)hasAllUnsupportedAppIDs:(id)ids;

@end

#endif /* GCKDBAppSupportStateInfo_h */
