//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GCKMDNSServiceRecord_h
#define GCKMDNSServiceRecord_h
@import Foundation;

#include "GCKMDNSDataRecord.h"

@class NSArray, NSString;

@interface GCKMDNSServiceRecord : GCKMDNSDataRecord

@property (retain, nonatomic) NSArray *serviceHost;
@property (nonatomic) unsigned short servicePort;
@property (nonatomic) long long servicePriority;
@property (nonatomic) long long serviceWeight;
@property (readonly, nonatomic) unsigned long long serviceProtocol;
@property (readonly, copy, nonatomic) NSString *serviceName;
@property (readonly, copy, nonatomic) NSString *serviceInstanceName;

/* class methods */
+ (id)recordWithName:(id)name serviceHost:(id)host servicePort:(unsigned short)port servicePriority:(long long)priority serviceWeight:(long long)weight;

/* instance methods */
- (id)initWithName:(id)name recordClass:(unsigned short)_class;
- (_Bool)readDataWith:(id)with;
- (_Bool)writeDataWith:(id)with;
- (_Bool)isDataEqualTo:(id)to;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* GCKMDNSServiceRecord_h */
