//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GCKOCSendMessageResponse_h
#define GCKOCSendMessageResponse_h
@import Foundation;

#include "GPBMessage.h"

@interface GCKOCSendMessageResponse : GPBMessage

@property (nonatomic) int successCnt;
@property (nonatomic) _Bool hasSuccessCnt;
@property (nonatomic) int offlineCnt;
@property (nonatomic) _Bool hasOfflineCnt;
@property (nonatomic) int errorCnt;
@property (nonatomic) _Bool hasErrorCnt;

/* class methods */
+ (id)descriptor;

@end

#endif /* GCKOCSendMessageResponse_h */
