@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GFBFeedbackSuggestionFetcher_h
#define GFBFeedbackSuggestionFetcher_h
@import Foundation;

#include "SUPReceiverConfig.h"

@class NSObject;

@interface GFBFeedbackSuggestionFetcher : NSObject {
    /* instance variables */
    SUPReceiverConfig *_receiverConfig;
}

/* instance methods */
- (id)initWithReceiverConfig:(id)config;
- (void)fetchWithUserDescription:(id)description completionHandler:(id /* block */)handler;

@end

#endif /* GFBFeedbackSuggestionFetcher_h */
