  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GFBFeedbackReport_h
#define GFBFeedbackReport_h
@import Foundation;

#include "FKFeedbackServiceCrashData.h"

@class NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSObject, NSString, UIImage;

@interface GFBFeedbackReport : NSObject {
    /* instance variables */
    NSMutableDictionary *_productSpecificBinaryDataMimeTypes;
}

@property (copy, nonatomic) NSString *userDescription;
@property (retain, nonatomic) UIImage *screenshot;
@property (retain, nonatomic) NSArray *screenshotHighlightAnnotationFrames;
@property (copy, nonatomic) NSString *context;
@property (copy, nonatomic) NSString *metricsSessionID;
@property (copy, nonatomic) NSString *ssv3SessionID;
@property (copy, nonatomic) NSString *logContents;
@property (readonly, nonatomic) NSDictionary *productSpecificData;
@property (readonly, nonatomic) NSDictionary *feedbackSpecificData;
@property (retain, nonatomic) NSArray *allowlistedPSDKeys;
@property (retain, nonatomic) NSArray *blocklistedPSDKeys;
@property (readonly, nonatomic) NSDictionary *productSpecificBinaryData;
@property (copy, nonatomic) NSArray *experimentIDs;
@property (readonly, nonatomic) NSArray *feedbackExperimentDataArray;
@property (readonly, nonatomic) _Bool silent;
@property (readonly, nonatomic) unsigned long long reportType;
@property (nonatomic) _Bool shouldIncludeScreenshot;
@property (nonatomic) _Bool shouldIncludeSystemLogsAndProductSpecificData;
@property (nonatomic) _Bool disableSystemLogsAndProductSpecificData;
@property (nonatomic) _Bool shouldIncludeEmailPSD;
@property (retain, nonatomic) FKFeedbackServiceCrashData *crashData;
@property (copy, nonatomic) NSString *categoryTag;
@property (copy, nonatomic) NSString *userEmail;
@property (copy, nonatomic) NSArray *experimentTokens;
@property (nonatomic) long long feedbackSource;
@property (nonatomic) long long noExperimentTokensReason;
@property (readonly, copy, nonatomic) NSString *deviceModel;
@property (readonly, copy, nonatomic) NSString *deviceCategory;
@property (readonly, copy, nonatomic) NSString *osVersion;
@property (readonly, copy, nonatomic) NSString *executableName;
@property (readonly, copy, nonatomic) NSString *bundleIdentifier;
@property (readonly, copy, nonatomic) NSString *bundleVersion;
@property (readonly, retain, nonatomic) NSDate *timestamp;
@property (readonly, nonatomic) float batteryLevel;
@property (readonly, nonatomic) long long batteryState;
@property (readonly, copy, nonatomic) NSString *uiLanguage;
@property (nonatomic) int feedbackVersion;
@property (nonatomic) _Bool suggestionShown;

/* instance methods */
- (id)initWithReportType:(unsigned long long)type isSilent:(_Bool)silent;
- (void)setProductSpecificValue:(id)value forKey:(id)key;
- (void)setProductSpecificBinaryData:(id)data forKey:(id)key;
- (void)setProductSpecificBinaryData:(id)data forKey:(id)key mimeType:(id)type;
- (void)addFeedbackExperimentData:(id)data;
- (_Bool)hasLogContents;
- (_Bool)hasProductSpecificData;
- (_Bool)hasLogContentsOrProductSpecificData;
- (int)protoReportType;
- (id)exportProto;
- (_Bool)isSilent;

@end

#endif /* GFBFeedbackReport_h */
