//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GFMDirectAddMembersRequest_h
#define GFMDirectAddMembersRequest_h
@import Foundation;

#include "GFMApiRequestHeader.h"
#include "GPBMessage.h"

@class NSMutableArray, NSString;

@interface GFMDirectAddMembersRequest : GPBMessage

@property (retain, nonatomic) GFMApiRequestHeader *apiHeader;
@property (nonatomic) _Bool hasApiHeader;
@property (retain, nonatomic) NSMutableArray *directAddParamsArray;
@property (readonly, nonatomic) unsigned long long directAddParamsArray_Count;
@property (copy, nonatomic) NSString *requesterProductId;
@property (nonatomic) _Bool hasRequesterProductId;

/* class methods */
+ (id)descriptor;

@end

#endif /* GFMDirectAddMembersRequest_h */
