  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GFMGetFamilyRequest_h
#define GFMGetFamilyRequest_h
@import Foundation;

#include "GFMApiRequestHeader.h"
#include "GPBMessage.h"

@interface GFMGetFamilyRequest : GPBMessage

@property (retain, nonatomic) GFMApiRequestHeader *apiHeader;
@property (nonatomic) _Bool hasApiHeader;
@property (nonatomic) _Bool includePossibleRoles;
@property (nonatomic) _Bool hasIncludePossibleRoles;
@property (nonatomic) _Bool includeUnconfirmedMembers;
@property (nonatomic) _Bool hasIncludeUnconfirmedMembers;
@property (nonatomic) _Bool retrieveFamilyForUnconfirmedMember;
@property (nonatomic) _Bool hasRetrieveFamilyForUnconfirmedMember;
@property (nonatomic) _Bool includeMergedPersons;
@property (nonatomic) _Bool hasIncludeMergedPersons;
@property (nonatomic) _Bool includeSubscriptionInfo;
@property (nonatomic) _Bool hasIncludeSubscriptionInfo;
@property (nonatomic) _Bool includeSummaryTextInSettingsApp;
@property (nonatomic) _Bool hasIncludeSummaryTextInSettingsApp;

/* class methods */
+ (id)descriptor;

@end

#endif /* GFMGetFamilyRequest_h */
