  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GFMUpdateInvitationRequest_h
#define GFMUpdateInvitationRequest_h
@import Foundation;

#include "GFMApiRequestHeader.h"
#include "GFMInvitation.h"
#include "GPBMessage.h"

@class NSString;

@interface GFMUpdateInvitationRequest : GPBMessage

@property (retain, nonatomic) GFMApiRequestHeader *apiHeader;
@property (nonatomic) _Bool hasApiHeader;
@property (copy, nonatomic) NSString *invitationId;
@property (nonatomic) _Bool hasInvitationId;
@property (retain, nonatomic) GFMInvitation *invitation;
@property (nonatomic) _Bool hasInvitation;

/* class methods */
+ (id)descriptor;

@end

#endif /* GFMUpdateInvitationRequest_h */
