  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GHKSearchBarContainerViewDelegate_Protocol_h
#define GHKSearchBarContainerViewDelegate_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol GHKSearchBarContainerViewDelegate <NSObject>

@required

/* required instance methods */
- (void)searchBarContainerView:(id)view seekingToOpenHelpUnit:(id)unit fromSpinnerHostViewController:(id)controller withNavigationController:(id)controller webViewControllerDelegate:(id)delegate;
- (void)searchResultViewController:(id)controller seekingToOpenDeepLinkURL:(id)url fromSpinnerHostViewController:(id)controller withNavigationController:(id)controller webViewControllerDelegate:(id)delegate viewID:(int)id shouldReplaceWebContent:(_Bool)content;
- (void)searchResultViewController:(id)controller didRequestToPrefetchHelpUnits:(id)units;

@optional

@end

#endif /* GHKSearchBarContainerViewDelegate_Protocol_h */
