//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GIKAccountInfoServiceDependenciesImpl_h
#define GIKAccountInfoServiceDependenciesImpl_h
@import Foundation;

#include "GIKAccountInfoServiceDependencies-Protocol.h"
#include "GIPAccountID-Protocol.h"
#include "GOOLazy.h"

@class NSObject, NSString;

@interface GIKAccountInfoServiceDependenciesImpl : NSObject <GIKAccountInfoServiceDependencies> {
    /* instance variables */
    id /* block */ _emailAccountInfoServiceOptionalInjector;
    id /* block */ _gidAccountInfoServiceOptionalInjector;
    id /* block */ _phoneNumberAccountInfoServiceOptionalInjector;
    id /* block */ _ssoAccountInfoServiceOptionalInjector;
}

@property (readonly, nonatomic) id <GIPAccountID> accountID;
@property (readonly, nonatomic) GOOLazy *lazyEmailAccountInfoService;
@property (readonly, nonatomic) GOOLazy *lazyGidAccountInfoService;
@property (readonly, nonatomic) GOOLazy *lazyPhoneNumberAccountInfoService;
@property (readonly, nonatomic) GOOLazy *lazySsoAccountInfoService;
@property (readonly, nonatomic) id /* block */ emailAccountInfoServiceInjector;
@property (readonly, nonatomic) id /* block */ gidAccountInfoServiceInjector;
@property (readonly, nonatomic) id /* block */ phoneNumberAccountInfoServiceInjector;
@property (readonly, nonatomic) id /* block */ ssoAccountInfoServiceInjector;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithAccountID:(id)id emailAccountInfoService:(id /* block */)service gidAccountInfoService:(id /* block */)service phoneNumberAccountInfoService:(id /* block */)service ssoAccountInfoService:(id /* block */)service;

@end

#endif /* GIKAccountInfoServiceDependenciesImpl_h */
