  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GILEventDispatcher_h
#define GILEventDispatcher_h
@import Foundation;

#include "GILBatchedEventStore.h"
#include "GILBatchedEventStoreDelegate-Protocol.h"
#include "GILEventDispatcher-Protocol.h"
#include "GILEventDispatcherExecutor-Protocol.h"
#include "GILLoggingRulesService-Protocol.h"
#include "GILValidationService-Protocol.h"
#include "GIPAccountID-Protocol.h"

@class NSDictionary, NSHashTable, NSObject, NSString;

@interface GILEventDispatcher : NSObject <GILBatchedEventStoreDelegate, GILEventDispatcher> {
    /* instance variables */
    NSDictionary *_eventHandlersByComponentID;
    NSDictionary *_logExtensionProvidersByComponentID;
    NSHashTable *_eventHandlersForBatchedEvents;
    id <GILValidationService> _validationService;
    id <GILEventDispatcherExecutor> _executor;
    id <GIPAccountID> _accountID;
    GILBatchedEventStore *_batchedEventStore;
    _Bool _isAppendingBatchEvents;
    id <GILLoggingRulesService> _loggingRulesService;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithAccountID:(id)id configurationService:(id)service loggingRulesService:(id)service validationService:(id)service eventHandlers:(id)handlers;
- (id)initWithAccountID:(id)id loggingRulesService:(id)service executor:(id)executor eventHandlers:(id)handlers validationService:(id)service flushInterval:(double)interval;
- (void)dispatchEvents:(id)events;
- (void)appendToBatchedEventInRootSnapshot:(id)snapshot withBlock:(id /* block */)block;
- (void)flushBatchedEvent:(id)event;
- (void)routeEvents:(id)events;
- (id)logExtensionsFromEvents:(id)events;

@end

#endif /* GILEventDispatcher_h */
