@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GIMBindingBuilder_h
#define GIMBindingBuilder_h
@import Foundation;

#include "GIMBinder-Protocol.h"
#include "GIMBindingAdditionalKeyBuilder-Protocol.h"
#include "GIMBindingCollectionKeyBuilder-Protocol.h"
#include "GIMBindingCreationPolicyBuilder-Protocol.h"
#include "GIMBindingDebugStringBuilder-Protocol.h"
#include "GIMBindingIdentificationBuilder-Protocol.h"
#include "GIMBindingInitializerBuilder-Protocol.h"
#include "GIMBindingLabelBuilder-Protocol.h"
#include "GIMBindingLinkBuilder-Protocol.h"
#include "GIMBindingReferencingPolicyBuilder-Protocol.h"
#include "GIMProvider-Protocol.h"

@class NSArray, NSMutableArray, NSObject, NSString;

@interface GIMBindingBuilder : NSObject <GIMBinder, GIMBindingAdditionalKeyBuilder, GIMBindingCollectionKeyBuilder, GIMBindingCreationPolicyBuilder, GIMBindingDebugStringBuilder, GIMBindingIdentificationBuilder, GIMBindingInitializerBuilder, GIMBindingLabelBuilder, GIMBindingLinkBuilder, GIMBindingReferencingPolicyBuilder> {
    /* instance variables */
    NSString *_moduleName;
    NSMutableArray *_itemKeyBuilders;
    NSArray *_itemKeys;
    id <GIMProvider> _provider;
    Class _linkedClass;
    id /* block */ _initializerBlock;
    long long _creationPolicy;
    long long _referencingPolicy;
    Class _identifierClass;
    NSString *_debugString;
}

/* class methods */
+ (id)builderWithModuleName:(id)name;

/* instance methods */
- (id)build;
- (id)bindType:(id)type;
- (id)bindArrayOfType:(id)type;
- (id)bindDictionaryFromType:(id)type toType:(id)type;
- (id)bindKey:(id)key;
- (id)andType:(id)type;
- (id)andArrayOfType:(id)type;
- (id)andDictionaryFromType:(id)type toType:(id)type;
- (id)andKey:(id)key;
- (id)withArrayKey:(id)key;
- (id)withDictionaryKey:(id)key;
- (id)lazily;
- (id)eagerly;
- (void)withDebugString:(id)string;
- (id)identifiedBy:(Class)by;
- (id)initializedWith:(id /* block */)with;
- (id)labelled:(id)labelled;
- (id)toClass:(Class)_class;
- (id)toProvider:(id)provider;
- (id)strongly;
- (id)weakly;
- (id)copying;
- (id)itemKeysFromFields;
- (id)providerFromFields;
- (Class)linkedClassFromFields;
- (id /* block */)initializerBlockFromFields;
- (long long)creationPolicyFromFields;
- (long long)referencingPolicyFromFields;
- (Class)identifierClassFromFields;
- (id)currentItemKeyBuilder;

@end

#endif /* GIMBindingBuilder_h */
