  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GMDCSearchBarController_h
#define GMDCSearchBarController_h
@import Foundation;

#include "GMDCSearchBarControllerConfiguration.h"

@class UIViewController, googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift;

@interface GMDCSearchBarController : UIViewController { // (Swift)
    /* instance variables */
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift searchBarHostingController;
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift searchBar;
}

@property (nonatomic, retain) GMDCSearchBarControllerConfiguration *configuration;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (id)init;
- (void)viewDidLoad;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* GMDCSearchBarController_h */
