  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GOOGRTCVideoSource_h
#define GOOGRTCVideoSource_h
@import Foundation;

#include "GOOGRTCMediaSource.h"
#include "GOOGRTCVideoCapturerDelegate-Protocol.h"

@class NSString;

@interface GOOGRTCVideoSource : GOOGRTCMediaSource <GOOGRTCVideoCapturerDelegate>

@property (readonly, nonatomic) struct scoped_refptr<webrtc::VideoTrackSourceInterface> { struct VideoTrackSourceInterface *x0; } nativeVideoSource;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFactory:(id)factory nativeVideoSource:(struct scoped_refptr<webrtc::VideoTrackSourceInterface> { struct VideoTrackSourceInterface *x0; })source;
- (id)initWithFactory:(id)factory nativeMediaSource:(struct scoped_refptr<webrtc::MediaSourceInterface> { struct MediaSourceInterface *x0; })source type:(long long)type;
- (id)initWithFactory:(id)factory signalingThread:(void *)thread workerThread:(void *)thread nativeVideoSource:(struct scoped_refptr<webrtc::VideoTrackSourceInterface> { struct VideoTrackSourceInterface *x0; })source;
- (void)capturer:(id)capturer didCaptureVideoFrame:(id)frame;
- (void)adaptOutputFormatToWidth:(int)width height:(int)height fps:(int)fps;

@end

#endif /* GOOGRTCVideoSource_h */
