  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GOOSideViewAvatarBadgeView_h
#define GOOSideViewAvatarBadgeView_h
@import Foundation;

@class CAShapeLayer, UIImage, UIView;

@interface GOOSideViewAvatarBadgeView : UIView {
    /* instance variables */
    UIImage *_avatarBadgeImage;
    struct CGSize { double width; double height; } _lastSize;
    CAShapeLayer *_maskLayer;
}

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame avatarBadgeImage:(id)image;
- (void)layoutSubviews;
- (id)avatarBadgeImage;
- (void)setAvatarBadgeImage:(id)image animated:(_Bool)animated;
- (void)updateLayerContentsWithImage:(id)image animated:(_Bool)animated;

@end

#endif /* GOOSideViewAvatarBadgeView_h */
