//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GOOSideViewAccountViewDelegate_Protocol_h
#define GOOSideViewAccountViewDelegate_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol GOOSideViewAccountViewDelegate <NSObject>

@required

/* required instance methods */
- (void)accountView:(id)view didSelectAccount:(id)account atIndex:(long long)index;
- (void)accountViewDidTapAccountSettings:(id)settings;
- (void)accountViewDidTapSignIn:(id)in;
- (void)accountViewDidChangeHeight:(id)height newHeight:(double)height;
- (_Bool)accountViewRequiresAttention;

@optional

@end

#endif /* GOOSideViewAccountViewDelegate_Protocol_h */
