//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GOOToken_h
#define GOOToken_h
@import Foundation;

#include "GOOTokenDelegate-Protocol.h"

@class NSString, UIButton, UIColor, UIControl, UIImage, UILabel, UIView;

@interface GOOToken : UIControl {
    /* instance variables */
    UIButton *_deleteButton;
    struct UIEdgeInsets { double top; double left; double bottom; double right; } _textEdgeInsets;
    UILabel *_textLabel;
    UIView *_deleteCircle;
}

@property (copy, nonatomic) NSString *text;
@property (retain, nonatomic) UIImage *image;
@property (retain, nonatomic) UIView *leftView;
@property (retain, nonatomic) UIColor *selectedTextColor;
@property (retain, nonatomic) UIColor *selectedBackgroundColor;
@property (retain, nonatomic) UIColor *selectedBorderColor;
@property (retain, nonatomic) UIColor *unselectedTextColor;
@property (retain, nonatomic) UIColor *unselectedBackgroundColor;
@property (retain, nonatomic) UIColor *unselectedBorderColor;
@property (nonatomic) _Bool showDeleteButton;
@property (weak, nonatomic) id <GOOTokenDelegate> delegate;
@property (nonatomic) _Bool showDeleteButtons;

/* class methods */
+ (double)tokenHeight;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithText:(id)text;
- (void)addDeleteIcon;
- (_Bool)isUIAccessibilityCustomActionAvailable;
- (_Bool)isAccessibilityElement;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (struct CGSize { double x0; double x1; })intrinsicContentSize;
- (void)setSelected:(_Bool)selected;
- (_Bool)canBecomeFirstResponder;
- (void)deleteAction:(id)action;
- (void)setTextEdgeInsets:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })insets;
- (void)setTitleColor:(id)color backgroundColor:(id)color borderColor:(id)color;

@end

#endif /* GOOToken_h */
