  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GPULoggingService_Protocol_h
#define GPULoggingService_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol GPULoggingService <NSObject>

@required

/* required instance methods */
- (void)logMetricsWithNodeIdentifier:(int)identifier sectionIdentifier:(int)identifier event:(int)event report:(id)report;
- (void)logMetricsWithEvent:(int)event report:(id)report;
- (void)logMetricsWithEvent:(int)event report:(id)report configType:(int)type version:(id)version subVersion:(id)version;
- (void)logMetricsWithEvent:(int)event toggleValue:(_Bool)value report:(id)report;
- (void)logMetricsWithEvent:(int)event webEventType:(long long)type eventLatency:(long long)latency report:(id)report;
- (void)logSupportSessionEvent:(int)event eventDetail:(id)detail report:(id)report;
- (void)updateClearcutLoggerWithComplianceData:(long long)data;

@optional

@end

#endif /* GPULoggingService_Protocol_h */
