  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GRWNotificationBlockState_h
#define GRWNotificationBlockState_h
@import Foundation;

#include "GPBMessage.h"

@class NSMutableArray;

@interface GRWNotificationBlockState : GPBMessage

@property (nonatomic) int reportType;
@property (nonatomic) _Bool hasReportType;
@property (nonatomic) int appBlockState;
@property (nonatomic) _Bool hasAppBlockState;
@property (retain, nonatomic) NSMutableArray *channelBlockStateArray;
@property (readonly, nonatomic) unsigned long long channelBlockStateArray_Count;
@property (retain, nonatomic) NSMutableArray *channelGroupBlockStateArray;
@property (readonly, nonatomic) unsigned long long channelGroupBlockStateArray_Count;

/* class methods */
+ (id)descriptor;

@end

#endif /* GRWNotificationBlockState_h */
