  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GSCFifeUrl_h
#define GSCFifeUrl_h
@import Foundation;

#include "GSCImageUrl.h"

@class NSString;

@interface GSCFifeUrl : GSCImageUrl {
    /* instance variables */
    _Bool _downloadVideo;
    _Bool _videoFormat;
    _Bool _isMissingHTTPS;
    NSString *_trailingQueryParams;
}

@property (readonly, nonatomic) NSString *unhandledOptions;

/* class methods */
+ (void)initialize;
+ (id)imageUrlWithURLString:(id)urlstring;
+ (id)encodeFifeBaseUrl:(id)url;
+ (id)decodeFifeBaseUrl:(id)url;
+ (id)fifeBaseUrlPrefix;
+ (id)fifeBaseUrl;
+ (id)fifeBaseMediaKeyUrlWithKey:(id)key;
+ (void)changeFifeBaseUrl:(id)url;
+ (void)changeMediaKeyUrlDirectory:(id)directory;

/* instance methods */
- (id)initWithURLString:(id)urlstring format:(unsigned char)format;
- (id)urlString;
- (id)url;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)initWithFifeUrl:(id)url;
- (void)parseOptionsString:(id)string;
- (id)finalizeUrlForContentFormat;
- (id)finalizeUrlForLegacyFormat;
- (id)finalizeUrlForDriveThumbnail;
- (id)constructFifeOptionString:(_Bool)string;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* GSCFifeUrl_h */
