  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GSRankSignalProto_h
#define GSRankSignalProto_h
@import Foundation;

#include "GPBMessage.h"
#include "GSFieldMetadataProto.h"

@class NSString;

@interface GSRankSignalProto : GPBMessage

@property (nonatomic) int type;
@property (nonatomic) _Bool hasType;
@property (nonatomic) float rank;
@property (nonatomic) _Bool hasRank;
@property (nonatomic) float rawScalar;
@property (nonatomic) _Bool hasRawScalar;
@property (copy, nonatomic) NSString *rawString;
@property (nonatomic) _Bool hasRawString;
@property (retain, nonatomic) GSFieldMetadataProto *metadata;
@property (nonatomic) _Bool hasMetadata;

/* class methods */
+ (id)descriptor;

@end

#endif /* GSRankSignalProto_h */
