//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GSZInMemoryStreamzService_h
#define GSZInMemoryStreamzService_h
@import Foundation;

#include "GSZInMemoryStreamzServiceOptions.h"
#include "GSZStreamzConfigurationService-Protocol.h"
#include "GSZStreamzService-Protocol.h"
#include "GSZStreamzTransportService-Protocol.h"
#include "OS_dispatch_queue-Protocol.h"

@class NSMutableArray, NSObject, NSString;

@interface GSZInMemoryStreamzService : NSObject <GSZStreamzService> {
    /* instance variables */
    GSZInMemoryStreamzServiceOptions *_options;
    id <GSZStreamzTransportService> _transportService;
    id <GSZStreamzConfigurationService> _configurationService;
    NSMutableArray *_counterValues;
    NSMutableArray *_eventMetricValues;
    NSMutableArray *_snapshotsToLog;
    NSObject<OS_dispatch_queue> *_ivarQueue;
    NSObject<OS_dispatch_queue> *_transportQueue;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithOptions:(id)options transportService:(id)service configurationService:(id)service;
- (id)initWithStreamzConfigurationService:(id)service streamzTransportService:(id)service options:(id)options;
- (void)dealloc;
- (void)logWithCounterValue:(id)value;
- (void)logWithEventMetricValue:(id)value;
- (void)flush;
- (void)handleAppToBackground;
- (id)snapshotAndClearStreamz;
- (void)flushAllIncludingCurrentStreamz:(_Bool)streamz;
- (void)flushSnapshotToTransport:(id)transport;
- (void)setupAutoFlushWithDelayInSeconds:(unsigned long long)seconds;
- (void)transportAllSynchronously;
- (_Bool)shouldIncrementCounterValue:(id)value;
- (_Bool)shouldRecordEventMetricValue:(id)value;

@end

#endif /* GSZInMemoryStreamzService_h */
