//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GTMFetcherAuthorizationProtocol_Protocol_h
#define GTMFetcherAuthorizationProtocol_Protocol_h
@import Foundation;

#include "GTMSessionFetcherServiceProtocol-Protocol.h"
#include "NSObject-Protocol.h"

@class NSString;

@protocol GTMFetcherAuthorizationProtocol <NSObject>

@required

@property (nonatomic, readonly) NSString *userEmail;
@property (nonatomic, readonly) _Bool canAuthorize;
@property (nonatomic) _Bool shouldAuthorizeAllRequests;
@property (nonatomic, weak) id <GTMSessionFetcherServiceProtocol> fetcherService;

/* required instance methods */
- (void)authorizeRequest:(id)request delegate:(id)delegate didFinishSelector:(SEL)selector;
- (void)authorizeRequest:(id)request delegate:(id)delegate didFinishSelector:(SEL)selector;
- (void)stopAuthorization;
- (void)stopAuthorizationForRequest:(id)request;
- (void)stopAuthorizationForRequest:(id)request;
- (_Bool)isAuthorizingRequest:(id)request;
- (_Bool)isAuthorizedRequest:(id)request;

@optional

/* optional instance methods */
- (void)authorizeRequest:(id)request completionHandler:(id /* block */)handler;
- (_Bool)primeForRefresh;

@end

#endif /* GTMFetcherAuthorizationProtocol_Protocol_h */
