@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GWA2DataValue_h
#define GWA2DataValue_h
@import Foundation;

#include "GWA2DataValue-Protocol.h"
#include "GWA2DataValueUpdateDelegate-Protocol.h"
#include "ORCH2DataValue.h"

@class NSObject, NSString;

@interface GWA2DataValue : NSObject <GWA2DataValue>

@property (readonly, nonatomic) ORCH2DataValue *proto;
@property (weak, nonatomic) id <GWA2DataValueUpdateDelegate> dataValueChangeDelegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithProto:(id)proto;
- (void)updateDataValueProto;
- (void)updateInitialStates;
- (void)resetDefaultState;

@end

#endif /* GWA2DataValue_h */
