  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef GWAUIFieldGroupingView_h
#define GWAUIFieldGroupingView_h
@import Foundation;

#include "GWAFormComponent-Protocol.h"
#include "GWAFormComponentDelegate-Protocol.h"
#include "GWAUIFieldGroupingViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIStackView;

@interface GWAUIFieldGroupingView : UIStackView <GWAFormComponent> {
    /* instance variables */
    NSMutableArray *_formFields;
}

@property (weak, nonatomic) id <GWAUIFieldGroupingViewDelegate> delegate;
@property (weak, nonatomic) id <GWAFormComponentDelegate> formComponentDelegate;
@property (nonatomic) _Bool componentHidden;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)addFormFieldArrangedSubview:(id)subview;
- (_Bool)isComponentHidden;
- (void)layoutSubviews;
- (void)onUIFieldFocus:(id)focus;
- (void)onUIFieldUnfocus:(id)unfocus;

@end

#endif /* GWAUIFieldGroupingView_h */
