  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef HAMDroppedFramesEvent_h
#define HAMDroppedFramesEvent_h
@import Foundation;

#include "HAMEvent.h"

@interface HAMDroppedFramesEvent : HAMEvent

@property (readonly, nonatomic) unsigned long long droppedFrameCount;

/* instance methods */
- (id)initWithPlayer:(id)player droppedFrameCount:(unsigned long long)count;
- (id)initWithPlayer:(id)player;

@end

#endif /* HAMDroppedFramesEvent_h */
