  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef HAMQueueingRootSampleBufferSource_h
#define HAMQueueingRootSampleBufferSource_h
@import Foundation;

#include "HAMABRPolicy-Protocol.h"
#include "HAMBaseComponent.h"
#include "HAMClock-Protocol.h"
#include "HAMFormat-Protocol.h"
#include "HAMMediaSourceDelegate-Protocol.h"
#include "HAMMediaTimeProvider-Protocol.h"
#include "HAMQueueingRootSampleBufferSourceTimelineProvider-Protocol.h"
#include "HAMRootMediaSource-Protocol.h"
#include "HAMRootMediaSourceEventCenter.h"
#include "HAMSampleBufferSource-Protocol.h"
#include "HAMSampleBufferSourceDelegate-Protocol.h"
#include "HAMSampleBufferSourceSegment.h"

@class NSMutableArray, NSString;

@interface HAMQueueingRootSampleBufferSource : HAMBaseComponent <HAMSampleBufferSourceDelegate, HAMMediaTimeProvider, HAMRootMediaSource, HAMSampleBufferSource> {
    /* instance variables */
    HAMSampleBufferSourceSegment *_fetchingSegment;
    NSMutableArray *_segments;
    float _rate;
    _Bool _suspended;
    double _lastABRPolicyUpdateTime;
    id <HAMClock> _clock;
    _Bool _delegateNotifiedOfFormatDescriptionChange;
    struct { struct { long long value; int timescale; unsigned int flags; long long epoch; } start; struct { long long value; int timescale; unsigned int flags; long long epoch; } duration; } _timeRange;
    _Bool _seekingToHead;
    _Bool _enableSegmentPTSFixes;
    _Bool _enableSampleBufferPTSFixes;
}

@property (weak, nonatomic) id <HAMMediaTimeProvider> mediaTimeProvider;
@property (readonly, nonatomic) HAMSampleBufferSourceSegment *readingSegment;
@property (weak, nonatomic) id <HAMQueueingRootSampleBufferSourceTimelineProvider> timelineProvider;
@property (nonatomic) _Bool rendererDisabled;
@property (nonatomic) struct { long long x0; int x1; unsigned int x2; long long x3; } lastReadMediaTime;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) int mediaContentType;
@property (readonly, nonatomic) _Bool isLive;
@property (readonly, nonatomic) struct { long long x0; int x1; unsigned int x2; long long x3; } bufferedTime;
@property (readonly, nonatomic) id <HAMFormat> format;
@property (readonly, nonatomic) HAMRootMediaSourceEventCenter *mediaSourceEventCenter;
@property (readonly, nonatomic) id <HAMABRPolicy> ABRPolicy;
@property (readonly, nonatomic) _Bool prepared;
@property (weak, nonatomic) id <HAMMediaSourceDelegate> delegate;

/* instance methods */
- (id)initWithContext:(id)context enableSegmentPTSFixes:(_Bool)ptsfixes enableSampleBufferPTSFixes:(_Bool)ptsfixes;
- (void)addSegment:(id)segment;
- (_Bool)removeSegment:(id)segment error:(id *)error;
- (void)removeAllSegments;
- (id)QOEDebugDetails;
- (void)setRate:(float)rate;
- (struct { long long x0; long long x1; int x2; })readNextWithOptions:(struct { int x0; struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; } x1; struct { long long x0; int x1; unsigned int x2; long long x3; } x2; long long x3; double x4; })options sampleBuffer:(id *)buffer error:(id *)error;
- (id)optimalSeekPositionsWithinRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })range;
- (void)continueBuffering;
- (void)suspend;
- (void)unsuspend;
- (_Bool)prepareAndReturnError:(id *)error;
- (struct { long long x0; int x1; unsigned int x2; long long x3; })seekToTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time toleranceBefore:(struct { long long x0; int x1; unsigned int x2; long long x3; })before toleranceAfter:(struct { long long x0; int x1; unsigned int x2; long long x3; })after;
- (void)sampleBufferSourceFormatDescriptionWillChange:(id)change;
- (void)mediaSource:(id)source setCurrentTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (void)mediaSource:(id)source didFailWithError:(id)error;
- (struct { long long x0; int x1; unsigned int x2; long long x3; })currentMediaTimeFor:(id)_for;
- (void)updateABRActionForSegments;
- (void)setFetchingSegment:(id)segment;
- (void)mediaSourceBufferedTimeDidChange:(id)change bufferedTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (id)segmentForMediaTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (void)getNewFetchingSegment:(id *)segment trimmingSegment:(id *)segment suspendCandidates:(id *)candidates;
- (_Bool)canUpdateFetchingSegment:(id)segment withTrimmingSegment:(id)segment;
- (void)updateABRAction:(id)abraction;
- (id)segmentsInRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })range;
- (void)timelineItemPeriodTimeRangeDidChange:(id)change;
- (void)updateSeekableTimeRange;

@end

#endif /* HAMQueueingRootSampleBufferSource_h */
