  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef IDCRecordDecisionRequest_h
#define IDCRecordDecisionRequest_h
@import Foundation;

#include "FOOTCRecordConsentDecisionRequest.h"
#include "GPBMessage.h"
#include "IDCConsentRequestMetadata.h"
#include "IDCMobileMetadata.h"
#include "IDCPrivacyPrimitiveConfig.h"
#include "IDCRecordDecisionRequest_FinalDecisionsMetadata.h"

@interface IDCRecordDecisionRequest : GPBMessage

@property (retain, nonatomic) FOOTCRecordConsentDecisionRequest *ftcRecordConsentDecisionRequest;
@property (nonatomic) _Bool hasFtcRecordConsentDecisionRequest;
@property (retain, nonatomic) IDCConsentRequestMetadata *metadata;
@property (nonatomic) _Bool hasMetadata;
@property (retain, nonatomic) IDCMobileMetadata *mobileMetadata;
@property (nonatomic) _Bool hasMobileMetadata;
@property (retain, nonatomic) IDCPrivacyPrimitiveConfig *privacyPrimitiveConfig;
@property (nonatomic) _Bool hasPrivacyPrimitiveConfig;
@property (nonatomic) _Bool hasNonFinalConsentDecision;
@property (nonatomic) _Bool hasHasNonFinalConsentDecision;
@property (retain, nonatomic) IDCRecordDecisionRequest_FinalDecisionsMetadata *finalDecisionsMetadata;
@property (nonatomic) _Bool hasFinalDecisionsMetadata;

/* class methods */
+ (id)descriptor;

@end

#endif /* IDCRecordDecisionRequest_h */
