@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef LDAdBlock_h
#define LDAdBlock_h
@import Foundation;

@class NSObject, UIView;

@interface LDAdBlock : NSObject

@property (nonatomic) struct LDAdState { double x0; double x1; struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } x2; struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } x3; struct CGSize { double x0; double x1; } x4; struct CGSize { double x0; double x1; } x5; } currentAdState;
@property (nonatomic) long long lastTime;
@property (nonatomic) long long firstTime;
@property (nonatomic) long long createdTime;
@property (nonatomic) double coverage;
@property (nonatomic) double screenShare;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } position;
@property (nonatomic) _Bool hasCreativeOffsetAndSize;
@property (nonatomic) struct CGVector { double x0; double x1; } creativeOffset;
@property (nonatomic) struct CGSize { double x0; double x1; } creativeSize;
@property (nonatomic) struct CGSize { double x0; double x1; } documentSize;
@property (nonatomic) struct CGSize { double x0; double x1; } windowSize;
@property (nonatomic) struct CGSize { double x0; double x1; } screenSize;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } lastContainerPosition;
@property (weak, nonatomic) UIView *monitoredView;
@property (nonatomic) _Bool fullscreen;
@property (nonatomic) _Bool backgrounded;

/* instance methods */
- (id)initWithView:(id)view;
- (_Bool)shouldAssumeFullyViewable;
- (void)addCommonMetricsWithMeasurementData:(id)data toDictionary:(id)dictionary;
- (_Bool)isFullscreen;
- (_Bool)isBackgrounded;

@end

#endif /* LDAdBlock_h */
