  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef LFEPresentationResult_h
#define LFEPresentationResult_h
@import Foundation;

#include "GPBMessage.h"
#include "LFEChipList.h"
#include "LFEHeader.h"
#include "LFEResultCard.h"

@interface LFEPresentationResult : GPBMessage

@property (readonly, nonatomic) int typeOneOfCase;
@property (retain, nonatomic) LFEHeader *header;
@property (nonatomic) _Bool hasHeader;
@property (retain, nonatomic) LFEChipList *chipList;
@property (nonatomic) _Bool hasChipList;
@property (retain, nonatomic) LFEResultCard *resultCard;
@property (nonatomic) _Bool hasResultCard;

/* class methods */
+ (id)descriptor;

@end

#endif /* LFEPresentationResult_h */
