  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef LNSAPITextLayout_Line_h
#define LNSAPITextLayout_Line_h
@import Foundation;

#include "GPBMessage.h"
#include "LNSAPIGeometry.h"

@class NSMutableArray;

@interface LNSAPITextLayout_Line : GPBMessage

@property (retain, nonatomic) NSMutableArray *wordsArray;
@property (readonly, nonatomic) unsigned long long wordsArray_Count;
@property (retain, nonatomic) LNSAPIGeometry *geometry;
@property (nonatomic) _Bool hasGeometry;
@property (retain, nonatomic) LNSAPIGeometry *textRenderingBox;
@property (nonatomic) _Bool hasTextRenderingBox;

/* class methods */
+ (id)descriptor;

@end

#endif /* LNSAPITextLayout_Line_h */
