@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef LNSPhotoOCRModel_h
#define LNSPhotoOCRModel_h
@import Foundation;

#include "LNSPhotoOCRModel-Protocol.h"

@class NSNumber, NSObject, NSString;

@interface LNSPhotoOCRModel : NSObject <LNSPhotoOCRModel>

@property (readonly, nonatomic) NSString *assetsDir;
@property (readonly, nonatomic) NSString *configLabel;
@property (readonly, nonatomic) NSNumber *deepParagraphingOverride;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithAssestsDir:(id)dir configLabel:(id)label;
- (id)initWithAssetsDir:(id)dir deepParagraphingOverride:(id)override;

@end

#endif /* LNSPhotoOCRModel_h */
