//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef LNSServiceAuthProvider_Protocol_h
#define LNSServiceAuthProvider_Protocol_h
@import Foundation;

#include "GTMFetcherAuthorizationProtocol-Protocol.h"
#include "NSObject-Protocol.h"

@protocol LNSServiceAuthProvider <NSObject>

@required

@property (readonly, nonatomic) id <GTMFetcherAuthorizationProtocol> authorization;

/* required instance methods */
- (void)lensServiceRefreshOAuthToken:(id /* block */)token;
- (id)accountID;
- (_Bool)shouldLogAnonymously;
- (_Bool)isSignedIn;
- (id)accountFullName;
- (id)accountEmail;

@optional

/* optional instance methods */
- (id)surveyAuthParams;
- (id)zwiebackCookieValue;
- (id)SOCSData;

@end

#endif /* LNSServiceAuthProvider_Protocol_h */
