  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef LNSSRPEnabledWebViewNavigationServiceImpl_h
#define LNSSRPEnabledWebViewNavigationServiceImpl_h
@import Foundation;

#include "GIPAccountID-Protocol.h"
#include "LNSExternalWebViewNavigationService-Protocol.h"
#include "LNSWebViewNavigationService-Protocol.h"

@class NSObject, NSString;

@interface LNSSRPEnabledWebViewNavigationServiceImpl : NSObject <LNSWebViewNavigationService> {
    /* instance variables */
    id <GIPAccountID> _accountID;
    id <LNSExternalWebViewNavigationService> _externalWebViewNavigationServiceOptional;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithAccountID:(id)id;
- (_Bool)shouldStartLoadingRequest:(id)request webContentController:(id)controller webViewURLHandler:(id)urlhandler originalRequest:(id)request delegate:(id)delegate;
- (void)didStartProvisionalNavigationFor:(id)_for navigation:(id)navigation;

@end

#endif /* LNSSRPEnabledWebViewNavigationServiceImpl_h */
