  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef LNSUnifiedStringFeatureFlag_h
#define LNSUnifiedStringFeatureFlag_h
@import Foundation;

#include "LNSFeatureFlagChoices-Protocol.h"
#include "LNSUnifiedFeatureFlag.h"

@class NSDictionary, NSString;

@interface LNSUnifiedStringFeatureFlag : LNSUnifiedFeatureFlag <LNSFeatureFlagChoices> // (Swift)

@property (nonatomic, copy) NSDictionary *choices;
@property (nonatomic) _Bool allowCustomChoice;
@property (nonatomic, copy) NSString *valueTip;
@property (nonatomic, readonly) NSString *value;

/* instance methods */

@end

#endif /* LNSUnifiedStringFeatureFlag_h */
