//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef MLABRPolicy_h
#define MLABRPolicy_h
@import Foundation;

#include "HAMBaseComponent.h"
#include "HAMClientABRPolicy-Protocol.h"
#include "HAMClientABRPolicyDelegate-Protocol.h"
#include "HAMDefaultABRPolicy.h"
#include "HAMDefaultABRPolicyDelegate-Protocol.h"
#include "HAMLoadRetryPolicy-Protocol.h"
#include "HAMMediaTimeProvider-Protocol.h"
#include "HAMViewportSize.h"
#include "MLABRNetworkTaskDelegate-Protocol.h"
#include "MLABRPolicyDelegate-Protocol.h"
#include "MLAuthorizedFormats.h"
#include "MLClientABRStateFiller.h"
#include "MLFormat.h"
#include "MLOnesieFormatKey.h"
#include "MLOnesieVideoData.h"
#include "MLProofOfOriginTokenManager-Protocol.h"
#include "MLQOEPingController.h"
#include "MLReadaheadPolicy-Protocol.h"
#include "YTHotConfig.h"
#include "YTIHamplayerABRConfig.h"
#include "YTIHamplayerConfig.h"
#include "YTNetworkActiveObserver-Protocol.h"
#include "YTReachabilityNetworkPropertiesObserver-Protocol.h"

@class NSArray, NSData, NSDictionary, NSString;

@interface MLABRPolicy : HAMBaseComponent <HAMDefaultABRPolicyDelegate, HAMMediaTimeProvider, MLABRNetworkTaskDelegate, MLABRPolicyDelegate, YTNetworkActiveObserver, YTReachabilityNetworkPropertiesObserver, HAMClientABRPolicy> {
    /* instance variables */
    HAMDefaultABRPolicy *_HAMDefaultABRPolicy;
    MLOnesieVideoData *_onesieVideoData;
    MLABRPolicy *_syncedABRPolicy;
    id <MLABRPolicyDelegate> _policyDelegate;
    MLQOEPingController *_QOEController;
    MLClientABRStateFiller *_clientABRStateFiller;
    MLAuthorizedFormats *_authorizedFormats;
    YTIHamplayerABRConfig *_config;
    YTIHamplayerConfig *_hamplayerConfig;
    struct HAMDefaultABRPolicyConfig { double maxMediaSecondsPerRequest; float downshiftScalar; float downshiftConstant; float upshiftScalar; float upshiftConstant; double maxDownshiftReadahead; double localMaxBitrateReadahead; double minReadaheadForAverageBitrate; double syncReadahead; double stunDuration; _Bool useHighReplicationFormatsWhileStunned; _Bool disableHDRInLowPowerMode; int maxConsecutiveErrors; double minUpshiftReplaceChunksReadahead; double bufferTrimBefore; double bufferTrimAfter; float oversendFactor; float higherPictureQualityOversendFactor; long long bufferMaxSizeBytes; long long lowMemoryWarnBufferSizeBytes; long long lowMemoryCriticalBufferSizeBytes; double lowMemoryBufferSizeCoolDown; double stallMaxBufferReadahead; double stallMinBufferReadahead; float stallBandwidthTweakScalar; int stallBandwidthTweakConstant; struct HAMSoftwareStreamFilter { int maxFPS; int maxArea; } softwareAV1Filter; struct HAMSoftwareStreamFilter { int maxFPS; int maxArea; } softwareVP9Filter; _Bool failIfAllFormatsAreFiltered; } _hamplayerDefaultConfig;
    YTHotConfig *_hotConfig;
    NSData *_videoPlaybackUstreamerConfig;
    NSData *_watchEndpointUstreamerConfig;
    MLFormat *_onesieFormat;
    MLOnesieFormatKey *_onesieFormatKey;
    _Bool _isText;
    NSArray *_allAvailableFormats;
    NSArray *_filteredSortedFormats;
    NSDictionary *_formatToData;
    HAMViewportSize *_viewportSize;
    int _playerVisibility;
    long long _bitrateCap;
    id <MLReadaheadPolicy> _readaheadPolicy;
    id <HAMLoadRetryPolicy> _loadRetryPolicy;
    int _videoConstraintQualitySetting;
    float _playbackRate;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct { union __rep { struct __short { signed char __data_[23]; unsigned int __size_:7; unsigned int __is_long_:1; } __s; struct __long { char *__data_; unsigned long long __size_; unsigned long long __cap_:63; unsigned int __is_long_:1; } __l; } __rep_; } x0; } _playbackCookie;
    NSString *_videoID;
    id <MLProofOfOriginTokenManager> _tokenManager;
    NSData *_proofOfOriginToken;
    int _spsRejectCount;
    _Bool _isMintingPoToken;
}

@property (readonly, nonatomic) int mediaContentType;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <HAMClientABRPolicyDelegate> delegate;
@property (readonly, nonatomic) struct { long long x0; int x1; unsigned int x2; long long x3; } bufferedTimeRangeEnd;
@property (weak, nonatomic) id <HAMMediaTimeProvider> mediaTimeProvider;
@property (nonatomic) struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; } queuedClipMediaTimeRange;
@property (readonly, nonatomic) _Bool stallLikely;
@property (nonatomic) _Bool suspended;

/* instance methods */
- (id)initWithContext:(id)context config:(id)config onesieVideoData:(id)data cache:(id)cache networkStatsProvider:(id)provider readaheadPolicy:(id)policy ustreamerRequestConfig:(id)config loadRetryPolicy:(id)policy policyDelegate:(id)delegate playerEventCenter:(id)center QOEController:(id)qoecontroller hamplayerConfig:(id)config watchEndpointUstreamerConfig:(id)config contentType:(int)type videoID:(id)id;
- (id)initWithContext:(id)context;
- (void)setBitrateCap:(long long)cap;
- (void)setReadaheadCap:(double)cap;
- (void)setPlayerVisibility:(int)visibility;
- (void)setSyncedABRPolicy:(id)abrpolicy;
- (void)setAuthorizedFormats:(id)formats;
- (id)QOEDebugDetails;
- (void)seekToTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (void)networkTaskForFormat:(id)format didCompleteWithError:(id)error;
- (void)onNextRequestPolicy:(const void *)policy;
- (void)onReloadPlayerResponse:(const void *)response;
- (void)onStreamProtectionStatus:(const void *)status;
- (void)networkDidChangeToActive;
- (void)reachabilityNetworkPropertiesDidChange:(id)change;
- (void)setViewportSize:(id)size;
- (void)setRate:(float)rate;
- (void)seekDidOccurToTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time toleranceBefore:(struct { long long x0; int x1; unsigned int x2; long long x3; })before toleranceAfter:(struct { long long x0; int x1; unsigned int x2; long long x3; })after;
- (void)setPlayerStatus:(long long)status;
- (void)terminate;
- (void)setChunkBuffer:(id)buffer;
- (void)setMediaChunkIndex:(id)index forFormat:(id)format;
- (void)setFormatConstraint:(id)constraint;
- (id)getABRActionAndReturnError:(id *)error;
- (void)setFormats:(id)formats;
- (void)ABRPolicy:(id)abrpolicy requestSeekToTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (void)ABRPolicy:(id)abrpolicy selectableFormatsDidChange:(id)change;
- (void)ABRPolicyDidRequestReloadPlayerResponse:(id)response;
- (_Bool)overrideFormatSelectionWithFormat:(id *)format;
- (id)ABRActionUserInfoForSelectedFormat:(id)format networkStats:(id)stats currentTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time mediaChunksToLoad:(id)load;
- (struct { long long x0; int x1; unsigned int x2; long long x3; })currentMediaTimeFor:(id)_for;
- (void)requestFormatReselection;
- (id)videoPlaybackRequestWrapperWithNetworkStats:(id)stats currentTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time mediaChunksToLoad:(id)load;
- (void)setNextRequestPolicy:(const void *)policy updateLoadRetryPolicy:(_Bool)policy;
- (void)pickOnesieFormatFromFormats:(id)formats;
- (void)onPoTokenMinted:(id)minted;

@end

#endif /* MLABRPolicy_h */
