        @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
        @protocol NSObject, NSCopying, NSCoding;
@interface MLHAMPlayerItem : NSObject <MLABRPolicyDelegate, MLAncillaryStreamStateObserver, MLBitrateCapDelegate, MLCaptionControllerDelegate, MLFairPlayContentKeyControllerDelegate, MLWidevineDRMControllerDelegate, MLHAMManifestlessSegmentMetadataFetcherDelegate, MLHAMVODCaptionPlaceholderSampleBufferSourceControlDelegate, MLManifestlessPartialResponseHandlerDelegate, MLOnesieVideoDataQOEErrorDelegate, MLServerABRLoaderDelegate, MLViewportSizeObserver, HAMCacheManagerDelegate, MLHAMPlayerItemProtocol> {
    /* instance variables */
    id <HAMClock> _clock;
    MLBitrateCap *_bitrateCap;
    id <HAMCache> _cache;
    MLOfflineRepo *_offlineRepo;
    id <HAMCacheManager> _cacheForCurrentUser;
    HAMCachePinHandle *_cachePinHandle;
    MLMediaDataLoader *_mediaDataLoader;
    HAMFormatSelection *_videoFormatSelection;
    HAMFormatSelection *_audioFormatSelection;
    HAMFormatSelection *_textFormatSelection;
    _Bool _sentFirstFormatChangeEvent;
    _Bool _isLiveHeadPlayable;
    _Bool _isPostLiveDvr;
    MLABRPolicy *_videoABRPolicy;
    MLABRPolicy *_audioABRPolicy;
    MLABRPolicy *_textABRPolicy;
    MLChunkLoader *_chunkLoader;
    id <MLChunkFactoryProvider> _chunkFactoryProvider;
    id <MLServerABRLoaderProtocol> _serverABRLoader;
    double _lastReportedCurrentTime;
    double _lastReportedBufferedTime;
    id <HAMNetworkStatsProvider> _networkStatsProvider;
    id <MLTextFormatConstraint> _textFormatConstraint;
    _Bool _usesAdaptiveCaptionFormats;
    MLFormat3Captions *_loadedFormat3Captions;
    double _readaheadCap;
    id <HAMNetworkRequestObserver> _networkRequestObserver;
    NSURL *_probeURLOnVideoPlay;
    int _activeFormatTypes;
    struct { struct { long long value; int timescale; unsigned int flags; long long epoch; } start; struct { long long value; int timescale; unsigned int flags; long long epoch; } duration; } _seekableTimeRange;
    MLQOEPingController *_QOEController;
    YTHotConfig *_hotConfig;
    YTIHamplayerHotConfig *_hamplayerHotConfig;
    YTIHamplayerConfig *_hamplayerConfig;
    MLFairPlayContentKeyController *_contentKeyController;
    MLWidevineDRMController *_DRMController;
    MLHAMManifestlessSegmentMetadataFetcher *_metadataFetcher;
    _Bool _noSelectableTextFormats;
    struct { _Bool enableAccurateSeek; int accurateSeekMaxSeekTimes; _Bool enableAccurateSeekAfterPrepared; } _seekConfig;
    id <MLHAMMetadataCollectorInternal> _metadataCollector;
    id <YTLatencyTickLoggerProtocol> _latencyLogger;
    MLPlayerReloadContext *_reloadContext;
    id <HAMABRController> _audioABRController;
    id <HAMABRController> _videoABRController;
    id <HAMABRController> _textABRController;
    id <MLAncillaryStreamStateProvider> _streamStateProvider;
    int _playerVisibility;
    id <MLViewportSizeProvider> _viewportSizeProvider;
    _Bool _enableTrackTypeFiltering;
    _Bool _setInitAndAudioTrackConstraint;
    NSMutableSet *_reportedCSITicks;
    MLMediaFetchControllerWrapper *_mediaFetchController;
    NSMutableDictionary *_formatDebugInfoTexts;
    HAMPlayerItemCPNSampler *_cpnSampler;
    _Bool _enableOfflineImmediatePrefetchWorkaround;
    _Bool _shouldCheckPlayerStateForReadaheadPolicy;
    _Bool _hasSentPrefetchSignal;
    _Bool _currentVideoIsLocal;
    _Bool _isLive;
    _Bool _isDRM;
    _Bool _peggedToLive;
    _Bool _active;
    _Bool _allStreamsAreLocal;
    _Bool _textTrackDisabled;
    _Bool _videoTrackDisabled;
    int _timescale;
    id <MLAudioFormatConstraint> _audioFormatConstraint;
    double _bufferedMediaTime;
    id <MLCaptionDisplayController> _captionDisplayController;
    id <MLPlayerConfig> _config;
    HAMPlayerContext *_context;
    id <MLPlayerItemDelegate> _delegate;
    long long _itemState;
    double _maximumSeekableTime;
    double _minimumSeekableTime;
    MLPlayerItemEventCenter *_playerItemEventCenter;
    MLSegmentTimeline *_segmentTimeline;
    NSArray *_selectableAudioFormats;
    NSArray *_selectableVideoFormats;
    MLFormat *_selectedAudioFormat;
    MLFormat *_selectedVideoFormat;
    MLVideo *_video;
    id <MLVideoFormatConstraint> _videoFormatConstraint;
    id <MLSSDAIDataProvider> _decoratedURLProvider;
    id <MLCaptionController> _captionController;
    MLPlaybackControllerWrapper *_playbackController;
    NSMutableArray *_errorsWhenInactive;
    MLPlayerReloadContext *_reloadContextWhenInactive;
    id <MLRecompositeProvider> _recompositeProvider;
    id <HAMPeriodSampleBufferSource> _audioSampleBufferSource;
    HAMEventCenter *_hamEventCenter;
    NSError *_error;
    MLOnesieVideoData *_onesieVideoData;
    long long _periodID;
    id <MLPlayerInternal> _player;
    id <MLHAMPlayerItemPlayerBridge> _playerBridge;
    NSObject<OS_dispatch_queue> *_playerQueue;
    id <HAMTrackRendererResyncPolicy> _resyncPolicy;
    MLHAMQueuePlayerSegmentList *_segmentList;
    id <HAMPeriodSampleBufferSource> _textSampleBufferSource;
    id <HAMPeriodSampleBufferSource> _videoSampleBufferSource;
    id /* block */ _audioSampleBufferSourceCreationBlock;
    id /* block */ _videoSampleBufferSourceCreationBlock;
    id /* block */ _textSampleBufferSourceCreationBlock;
    id /* block */ _placeholderTextSampleBufferSourceCreationBlock;
    id /* block */ _audioABRPolicyCreationBlock;
    id /* block */ _videoABRPolicyCreationBlock;
    id /* block */ _textABRPolicyCreationBlock;
    id /* block */ _metadataFetcherCreationBlock;
    id /* block */ _metadataCollectorCreationBlock;
    id /* block */ _serverABRLoaderCreationBlock;
    struct { double time; double productionTime; double absoluteTime; } _currentTime;
}

@property (copy, nonatomic) id /* block */ audioSampleBufferSourceCreationBlock;
@property (copy, nonatomic) id /* block */ videoSampleBufferSourceCreationBlock;
@property (copy, nonatomic) id /* block */ textSampleBufferSourceCreationBlock;
@property (copy, nonatomic) id /* block */ placeholderTextSampleBufferSourceCreationBlock;
@property (copy, nonatomic) id /* block */ audioABRPolicyCreationBlock;
@property (copy, nonatomic) id /* block */ videoABRPolicyCreationBlock;
@property (copy, nonatomic) id /* block */ textABRPolicyCreationBlock;
@property (copy, nonatomic) id /* block */ metadataFetcherCreationBlock;
@property (copy, nonatomic) id /* block */ metadataCollectorCreationBlock;
@property (copy, nonatomic) id /* block */ serverABRLoaderCreationBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) long long periodID;
@property (readonly, nonatomic) _Bool isLive;
@property (readonly, nonatomic) _Bool isLiveHeadPlayable;
@property (readonly, nonatomic) _Bool isSeekingToLiveHead;
@property (readonly, nonatomic) _Bool isDRM;
@property (nonatomic) _Bool active;
@property (nonatomic) _Bool peggedToLive;
@property (weak, nonatomic) id <MLHAMPlayerItemPlayerBridge> playerBridge;
@property (weak, nonatomic) MLHAMQueuePlayerSegmentList *segmentList;
@property (readonly, nonatomic) HAMEventCenter *hamEventCenter;
@property (readonly, nonatomic) id <MLPlayerConfig> config;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *playerQueue;
@property (readonly, nonatomic) MLOnesieVideoData *onesieVideoData;
@property (readonly, nonatomic) id <HAMPeriodSampleBufferSource> videoSampleBufferSource;
@property (readonly, nonatomic) id <HAMPeriodSampleBufferSource> audioSampleBufferSource;
@property (readonly, nonatomic) id <HAMPeriodSampleBufferSource> textSampleBufferSource;
@property (readonly, nonatomic) id <HAMTrackRendererResyncPolicy> resyncPolicy;
@property (readonly, nonatomic) NSError *error;
@property (readonly, nonatomic) _Bool allStreamsAreLocal;
@property (readonly, weak, nonatomic) id <MLPlayerInternal> player;
@property (readonly, nonatomic) HAMPlayerContext *context;
@property (readonly, nonatomic) _Bool textTrackDisabled;
@property (readonly, nonatomic) _Bool videoTrackDisabled;
@property (retain, nonatomic) NSMutableArray *errorsWhenInactive;
@property (retain, nonatomic) MLPlayerReloadContext *reloadContextWhenInactive;
@property (readonly, nonatomic) int timescale;
@property (readonly, nonatomic) MLPlaybackControllerWrapper *playbackController;
@property (readonly, nonatomic) MLQOEPingController *qoeController;
@property (readonly, weak, nonatomic) id <MLRecompositeProvider> recompositeProvider;
@property (readonly, nonatomic) MLPlayerItemEventCenter *playerItemEventCenter;
@property (readonly, nonatomic) long long bitrate;
@property (readonly, nonatomic) float oversendFactor;
@property (readonly, nonatomic) double bufferedMediaTime;
@property (readonly, nonatomic) struct { double x0; double x1; double x2; } currentTime;
@property (readonly, nonatomic) NSArray *selectableAudioFormats;
@property (readonly, nonatomic) NSArray *selectableVideoFormats;
@property (readonly, nonatomic) long long DAIType;
@property (readonly, nonatomic) id <MLSSDAIDataProvider> decoratedURLProvider;
@property (readonly, nonatomic) NSString *formatDebugInfo;
@property (weak, nonatomic) id <MLPlayerItemDelegate> playerItemDelegate;
@property (readonly, nonatomic) long long itemState;
@property (readonly, nonatomic) double totalMediaTime;
@property (readonly, nonatomic) double minimumSeekableTime;
@property (readonly, nonatomic) double maximumSeekableTime;
@property (readonly, nonatomic) MLFormat *selectedAudioFormat;
@property (readonly, nonatomic) MLFormat *selectedVideoFormat;
@property (retain, nonatomic) id <MLVideoFormatConstraint> videoFormatConstraint;
@property (retain, nonatomic) id <MLAudioFormatConstraint> audioFormatConstraint;
@property (readonly, nonatomic) id <MLCaptionTrack> activeCaptionTrack;
@property (readonly, nonatomic) NSArray *availableCaptionTracks;
@property (readonly, nonatomic) MLVideo *video;
@property (readonly, nonatomic) _Bool currentVideoIsLocal;
@property (readonly, nonatomic) _Bool usingServerABR;
@property (readonly, nonatomic) MLSegmentTimeline *segmentTimeline;
@property (readonly, nonatomic) id <MLCaptionDisplayController> captionDisplayController;
@property (readonly, nonatomic) id <MLManifestlessMetadataCollector> metadataCollector;
@property (readonly, nonatomic) id <MLCaptionController> captionController;
@property (readonly, nonatomic) float maximumSupportedPlaybackRate;
@property (readonly, nonatomic) id <MLCuepointDataStore> cuepointDataStore;

/* instance methods */
- (id)initWithVideo:(id)video playerConfig:(id)config playerQueue:(id)queue periodID:(long long)id player:(id)player onesieVideoData:(id)data latencyLogger:(id)logger reloadContext:(id)context SSDAIDataProvider:(id)provider mediaFetchController:(id)controller recompositeProvider:(id)provider;
- (void)restartPrefetchEvaluation;
- (_Bool)playerResponseIsLive;
- (_Bool)containsFormat:(id)format;
- (void)terminateWithStoppageReason:(int)reason;
- (void)updateBufferedTime;
- (void)setCurrentTime:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; double x1; double x2; })time;
- (void)handleStartedTrackRenderersChanged:(int)changed to:(int)to;
- (void)handleTrackRenderer:(id)renderer statusDidChangeTo:(long long)to absoluteTime:(double)time;
- (void)updateSeekableTimeRange;
- (void)setActive:(_Bool)active;
- (void)emitQOEError:(id)qoeerror fatal:(_Bool)fatal;
- (id)QOEDebugDetails;
- (_Bool)isSeekingToLiveHead;
- (id)qoeController;
- (void)load;
- (void)loadWithInitialSeekRequired:(_Bool)required initialSeekTime:(double)time;
- (void)setViewportSizeProvider:(id)provider;
- (void)playerStateDidChangeFrom:(long long)from to:(long long)to;
- (void)setVideoFormatConstraint:(id)constraint;
- (void)setAudioFormatConstraint:(id)constraint;
- (void)setTextFormatConstraint:(id)constraint;
- (void)updateABRPoliciesWithBitrateCap:(long long)cap;
- (void)setPreferredMaxReadahead:(double)readahead;
- (void)setState:(long long)state;
- (void)setActiveTrackRendererTypes:(int)types;
- (double)totalMediaTime;
- (float)maximumSupportedPlaybackRate;
- (void)setAncillaryStreamStateProvider:(id)provider;
- (void)registerQOEController:(id)qoecontroller;
- (id)metadataCollector;
- (int)timescale;
- (void)setPlayerVisibility:(int)visibility;
- (id)currentVideoFormatItag;
- (id)formatDebugInfo;
- (long long)bitrate;
- (float)oversendFactor;
- (void)flushEvents;
- (id)activeCaptionTrack;
- (id)availableCaptionTracks;
- (void)enableCaptionsIfAvailableWithSelectionReason:(long long)reason;
- (void)setLiveCaptionsVerticalRatio:(double)ratio;
- (long long)DAIType;
- (id)cuepointDataStore;
- (void)bitrateCapDidChange:(long long)change formatPacingBitrateCap:(long long)cap;
- (void)ABRPolicy:(id)abrpolicy selectableFormatsDidChange:(id)change;
- (void)ABRPolicy:(id)abrpolicy requestSeekToTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (void)ABRPolicyDidRequestReloadPlayerResponse:(id)response;
- (void)contentKeyController:(id)controller didFailWithError:(id)error;
- (void)contentKeyController:(id)controller didReceiveAuthorizedFormats:(id)formats;
- (void)DRMController:(id)drmcontroller didFailWithCDMError:(id)cdmerror;
- (void)DRMController:(id)drmcontroller didFailWithITDRMError:(id)itdrmerror;
- (void)rejoinStreamForMediaChunk:(id)chunk;
- (void)recordNonFatalQOEError:(id)qoeerror;
- (void)activeCaptionTrackDidChange:(id)change reason:(long long)reason;
- (void)availableCaptionTracksDidChange:(id)change;
- (void)captionControllerDidFailWithError:(id)error;
- (void)didLoadFormat3Captions:(id)captions;
- (void)selectedCaptionTrackDidChange:(id)change selectionReason:(long long)reason;
- (void)metadataFetcherReportNonFatalError:(id)error;
- (void)didReadDataFromPlaceholderSampleBufferSource;
- (void)serverABRLoader:(id)abrloader didChangeSelectableAudioFormats:(id)formats selectableVideoFormats:(id)formats selectableTextFormats:(id)formats;
- (void)serverABRLoader:(id)abrloader didFailWithError:(id)error allowFallback:(_Bool)fallback platypusFallbackConfig:(struct optional<youtube::media::interfaces::FallbackConfig> { union { signed char x0; struct FallbackConfig { int x0; _Bool x1; _Bool x2; _Bool x3; } x1; } x0; _Bool x1; })config;
- (void)serverABRLoader:(id)abrloader didEncounterNonFatalError:(id)error;
- (void)serverABRLoader:(id)abrloader requestSeekToTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time seekSource:(int)source;
- (void)serverABRLoader:(id)abrloader didRequestReloadPlayerResponseWithToken:(id)token;
- (void)serverABRLoader:(id)abrloader didParseFormatDebugInfo:(id)info formatID:(id)id;
- (void)serverABRLoader:(id)abrloader didParseStitchedSegmentsMetadataList:(const void *)list;
- (void)provider:(id)provider streamStateDidChange:(long long)change;
- (void)viewportSizeDidChange:(id)change;
- (void)addTimeObservers;
- (void)updateLocalStateFromMPD:(id)mpd;
- (void)setupVideoWithMPDProvider:(id)mpdprovider;
- (void)setupAudioWithMPDProvider:(id)mpdprovider;
- (id)createChunkLoaderWithDataLoader:(id)loader manifestlessMPD:(id)mpd;
- (void)setupTextWithMPDProvider:(id)mpdprovider isManifestless:(_Bool)manifestless;
- (void)updateABRPoliciesWithReadaheadCap;
- (void)registerWithEventCenter;
- (void)onFormatSelectionEvent:(id)event;
- (void)emitQOEErrorWithNSError:(id)nserror fatal:(_Bool)fatal;
- (void)updateCaptionControllerAudioTrack;
- (void)setActiveCaptionTrack:(id)track selectionReason:(long long)reason;
- (void)updateNetworkUsageNotifierForPlayerState:(long long)state;
- (void)updatePeggedToLive;
- (void)setPeggedToLive:(_Bool)live;
- (void)updateSelectedFormatsWithFormatSelectionReason:(long long)reason requestIdentifierToken:(id)token;
- (void)broadcastDebugInfo;
- (void)setUpCaptionController;
- (void)setUpCaptionDisplayController;
- (void)maybeUpdateTextFormatConstraint;
- (struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })liveSeekableTimeRangeForSeekableTimeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })range;
- (void)setSeekableTimeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })range isLive:(_Bool)live;
- (void)setupManifestlessMetadataFetcherWithMPD:(id)mpd;
- (void)fetchStatusChanged:(_Bool)changed;
- (_Bool)DAIEnabled;
- (void)onSelectableAudioFormats:(id)formats;
- (void)onSelectableTextFormats:(id)formats;
- (void)onSelectableVideoFormats:(id)formats;
- (void)updateTextTrackDisabled;
- (void)updateVideoTrackDisabled;
- (void)startMetadataFetcher:(_Bool)fetcher;
- (_Bool)usingServerABR;
- (void)requestReloadPlayerResponseWithToken:(id)token;
- (void)setViewportSize:(id)size;
- (long long)reloadContextFirstRequestNumber;
- (void)maybeLogCSITicksForTrackRenderer:(id)renderer withStatus:(long long)status absoluteTime:(double)time;
- (void)maybeBroadcastActiveCaptionTrackChanged;
- (void)didFailWithError:(id)error;
- (void)requestPlayerReloadWithContext:(id)context;
- (void)evaluateOfflinePrefetchWorkaround;
- (id)compositeVideoDefaultAudioTrackId;
- (struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })seekableTimeRange;
- (void)cacheManager:(id)manager didEncounterNonFatalError:(id)error;
- (id)audioABRPolicy;
- (id)textABRPolicy;
- (id)videoABRPolicy;
- (int)playerVisibility;
- (id)audioFormatConstraint;
- (double)bufferedMediaTime;
- (id)captionDisplayController;
- (id)config;
- (id)context;
- (struct { double x0; double x1; double x2; })currentTime;
- (_Bool)currentVideoIsLocal;
- (id)playerItemDelegate;
- (void)setPlayerItemDelegate:(id)delegate;
- (_Bool)isLive;
- (_Bool)isLiveHeadPlayable;
- (_Bool)isDRM;
- (long long)itemState;
- (double)maximumSeekableTime;
- (double)minimumSeekableTime;
- (_Bool)peggedToLive;
- (id)playerItemEventCenter;
- (id)segmentTimeline;
- (id)selectableAudioFormats;
- (id)selectableVideoFormats;
- (id)selectedAudioFormat;
- (id)selectedVideoFormat;
- (id)video;
- (id)videoFormatConstraint;
- (id)decoratedURLProvider;
- (id)captionController;
- (id)playbackController;
- (id)errorsWhenInactive;
- (void)setErrorsWhenInactive:(id)inactive;
- (id)reloadContextWhenInactive;
- (void)setReloadContextWhenInactive:(id)inactive;
- (id)recompositeProvider;
- (_Bool)active;
- (_Bool)allStreamsAreLocal;
- (id)audioSampleBufferSource;
- (id)hamEventCenter;
- (id)error;
- (id)onesieVideoData;
- (long long)periodID;
- (id)player;
- (id)playerBridge;
- (void)setPlayerBridge:(id)bridge;
- (id)playerQueue;
- (id)resyncPolicy;
- (id)segmentList;
- (void)setSegmentList:(id)list;
- (id)textSampleBufferSource;
- (_Bool)textTrackDisabled;
- (id)videoSampleBufferSource;
- (_Bool)videoTrackDisabled;
- (id /* block */)audioSampleBufferSourceCreationBlock;
- (void)setAudioSampleBufferSourceCreationBlock:(id /* block */)block;
- (id /* block */)videoSampleBufferSourceCreationBlock;
- (void)setVideoSampleBufferSourceCreationBlock:(id /* block */)block;
- (id /* block */)textSampleBufferSourceCreationBlock;
- (void)setTextSampleBufferSourceCreationBlock:(id /* block */)block;
- (id /* block */)placeholderTextSampleBufferSourceCreationBlock;
- (void)setPlaceholderTextSampleBufferSourceCreationBlock:(id /* block */)block;
- (id /* block */)audioABRPolicyCreationBlock;
- (void)setAudioABRPolicyCreationBlock:(id /* block */)block;
- (id /* block */)videoABRPolicyCreationBlock;
- (void)setVideoABRPolicyCreationBlock:(id /* block */)block;
- (id /* block */)textABRPolicyCreationBlock;
- (void)setTextABRPolicyCreationBlock:(id /* block */)block;
- (id /* block */)metadataFetcherCreationBlock;
- (void)setMetadataFetcherCreationBlock:(id /* block */)block;
- (id /* block */)metadataCollectorCreationBlock;
- (void)setMetadataCollectorCreationBlock:(id /* block */)block;
- (id /* block */)serverABRLoaderCreationBlock;
- (void)setServerABRLoaderCreationBlock:(id /* block */)block;

@end

@interface MLHAMPlayerItemSegment : NSObject <MLPlayerItemSegment> {
    /* instance variables */
    struct { struct { long long value; int timescale; unsigned int flags; long long epoch; } start; struct { long long value; int timescale; unsigned int flags; long long epoch; } duration; } _playerItemSeekableTimeRange;
    _Bool _autoStartPlayback;
    _Bool _shouldAutoStartAfterBlocking;
    _Bool _playToEnd;
    HAMSampleBufferSourceSegment *_audioSegment;
    double _duration;
    double _playerPeriodStartTime;
    double _startTime;
    HAMSampleBufferSourceSegment *_textSegment;
    HAMSampleBufferSourceSegment *_videoSegment;
    id <MLHAMPlayerItemProtocol> _playerItem;
    HAMSampleBufferSourceTimelineItem *_timeline;
    struct shared_ptr<youtube::media::interfaces::VideoClip> { struct VideoClip *__ptr_; struct __shared_weak_count *__cntrl_; } _platypusVideoClip;
}

@property (nonatomic) struct shared_ptr<youtube::media::interfaces::VideoClip> { struct VideoClip *x0; struct __shared_weak_count *x1; } platypusVideoClip;
@property (readonly, nonatomic) id <MLHAMPlayerItemProtocol> playerItem;
@property (readonly, nonatomic) HAMSampleBufferSourceTimelineItem *timeline;
@property (readonly, nonatomic) HAMSampleBufferSourceSegment *videoSegment;
@property (readonly, nonatomic) HAMSampleBufferSourceSegment *audioSegment;
@property (readonly, nonatomic) HAMSampleBufferSourceSegment *textSegment;
@property (nonatomic) double playerPeriodStartTime;
@property (readonly, nonatomic) _Bool playToEnd;
@property (readonly, nonatomic) double startTime;
@property (readonly, nonatomic) double duration;
@property (readonly, nonatomic) _Bool autoStartPlayback;
@property (readonly, nonatomic) _Bool shouldAutoStartAfterBlocking;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithPlayerItem:(id)item startTime:(double)time duration:(double)duration autoStartPlayback:(_Bool)playback shouldAutoStartAfterBlocking:(_Bool)blocking;
- (id)videoSegment;
- (id)audioSegment;
- (id)textSegment;
- (_Bool)updatePlayerItemSeekableTimeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })range;
- (_Bool)clipToStartTime:(double)time duration:(double)duration;
- (_Bool)updatePeriodTimeline;
- (void)updatePlayerPeriodStartTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (double)playerTimeToPeriodTime:(double)time;
- (double)playerPeriodStartTime;
- (void)setPlayerPeriodStartTime:(double)time;
- (_Bool)autoStartPlayback;
- (double)duration;
- (double)startTime;
- (_Bool)shouldAutoStartAfterBlocking;
- (id)playerItem;
- (id)timeline;
- (_Bool)playToEnd;
- (struct shared_ptr<youtube::media::interfaces::VideoClip> { struct VideoClip *x0; struct __shared_weak_count *x1; })platypusVideoClip;
- (void)setPlatypusVideoClip:(struct shared_ptr<youtube::media::interfaces::VideoClip> { struct VideoClip *x0; struct __shared_weak_count *x1; })clip;

@end

