  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef MSPTextStyle_h
#define MSPTextStyle_h
@import Foundation;

#include "GPBMessage.h"
#include "GTPColor.h"
#include "MSPFontSize.h"
#include "MSPFontStyle.h"
#include "MSPFontWeight.h"

@class NSString;

@interface MSPTextStyle : GPBMessage

@property (retain, nonatomic) MSPFontWeight *fontWeight;
@property (nonatomic) _Bool hasFontWeight;
@property (retain, nonatomic) GTPColor *color;
@property (nonatomic) _Bool hasColor;
@property (nonatomic) int baselineOffset;
@property (nonatomic) _Bool hasBaselineOffset;
@property (nonatomic) int directionality;
@property (nonatomic) _Bool hasDirectionality;
@property (retain, nonatomic) MSPFontSize *fontSize;
@property (nonatomic) _Bool hasFontSize;
@property (retain, nonatomic) MSPFontStyle *fontStyle;
@property (nonatomic) _Bool hasFontStyle;
@property (nonatomic) _Bool emphasis;
@property (nonatomic) _Bool hasEmphasis;
@property (nonatomic) _Bool underline;
@property (nonatomic) _Bool hasUnderline;
@property (nonatomic) _Bool strikeThrough;
@property (nonatomic) _Bool hasStrikeThrough;
@property (copy, nonatomic) NSString *backgroundColor;
@property (nonatomic) _Bool hasBackgroundColor;

/* class methods */
+ (id)descriptor;

@end

#endif /* MSPTextStyle_h */
