@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef NFDRenderContext_DeviceInfo_IosNotificationPermissions_h
#define NFDRenderContext_DeviceInfo_IosNotificationPermissions_h
@import Foundation;

#include "GPBMessage.h"

@interface NFDRenderContext_DeviceInfo_IosNotificationPermissions : GPBMessage

@property (nonatomic) int soundSetting;
@property (nonatomic) _Bool hasSoundSetting;
@property (nonatomic) int badgeSetting;
@property (nonatomic) _Bool hasBadgeSetting;
@property (nonatomic) int alertSetting;
@property (nonatomic) _Bool hasAlertSetting;
@property (nonatomic) int notificationCenterSetting;
@property (nonatomic) _Bool hasNotificationCenterSetting;
@property (nonatomic) int lockScreenSetting;
@property (nonatomic) _Bool hasLockScreenSetting;
@property (nonatomic) int carPlaySetting;
@property (nonatomic) _Bool hasCarPlaySetting;
@property (nonatomic) int alertStyle;
@property (nonatomic) _Bool hasAlertStyle;
@property (nonatomic) int showPreviewsSetting;
@property (nonatomic) _Bool hasShowPreviewsSetting;
@property (nonatomic) int criticalAlertSetting;
@property (nonatomic) _Bool hasCriticalAlertSetting;
@property (nonatomic) int scheduledDeliverySetting;
@property (nonatomic) _Bool hasScheduledDeliverySetting;
@property (nonatomic) int timeSensitiveSetting;
@property (nonatomic) _Bool hasTimeSensitiveSetting;
@property (nonatomic) int announcementSetting;
@property (nonatomic) _Bool hasAnnouncementSetting;
@property (nonatomic) int aiSummarizationSetting;
@property (nonatomic) _Bool hasAiSummarizationSetting;
@property (nonatomic) int aiPrioritizationSetting;
@property (nonatomic) _Bool hasAiPrioritizationSetting;

/* class methods */
+ (id)descriptor;

@end

#endif /* NFDRenderContext_DeviceInfo_IosNotificationPermissions_h */
