  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef OGLAccountMenuTopSectionHeaderView_h
#define OGLAccountMenuTopSectionHeaderView_h
@import Foundation;

#include "OGLGM2AccountSelectorHeaderView.h"
#include "OGLThemeRoot-Protocol.h"
#include "OGLTheming-Protocol.h"

@class NSString, UIView;

@interface OGLAccountMenuTopSectionHeaderView : UIView <OGLThemeRoot>

@property (readonly, nonatomic) OGLGM2AccountSelectorHeaderView *accountMenuHeaderView;
@property (readonly, nonatomic) UIView *backgroundView;
@property (nonatomic) double topSafeAreaInset;
@property (retain, nonatomic) id <OGLTheming> oglTheme;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)createAccountMenuHeaderViewWithChooseAnAccountDisplay:(_Bool)display textSize:(unsigned long long)size;

/* instance methods */
- (id)initWithChooseAnAccountDisplay:(_Bool)display textSize:(unsigned long long)size oglTheme:(id)theme;
- (void)layoutSubviews;
- (double)preferredHeightForWidth:(double)width;
- (void)addTarget:(id)target actionForCloseButtonEvent:(SEL)event;
- (void)applyTheme;
- (void)setUpperCornerRadius:(double)radius;

@end

#endif /* OGLAccountMenuTopSectionHeaderView_h */
