  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef OGLAccountMenuActionHandler_h
#define OGLAccountMenuActionHandler_h
@import Foundation;

#include "OGLAccountMenuActionHandler-Protocol.h"
#include "OGLAccountMenuSessionInternal-Protocol.h"

@class NSObject, NSString;

@interface OGLAccountMenuActionHandler : NSObject <OGLAccountMenuActionHandler>

@property (readonly, weak, nonatomic) id <OGLAccountMenuSessionInternal> session;
@property (nonatomic) _Bool supportMarkAccounts;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithSession:(id)session;
- (void)triggerSwitchFromAccount:(id)account toAccount:(id)account completion:(id /* block */)completion;
- (void)triggerSignInWithPresentingVC:(id)vc accountToReauthenticate:(id)reauthenticate completion:(id /* block */)completion;
- (void)triggerSwitchToNoAccountFromAccount:(id)account completion:(id /* block */)completion;
- (void)triggerRemoveAccount:(id)account presentingViewController:(id)controller completion:(id /* block */)completion;
- (void)triggerMyAccountFlow:(id)flow presentingViewController:(id)controller completion:(id /* block */)completion;
- (void)triggerAccountSettingsFlow:(id)flow resourceId:(int)id presentingViewController:(id)controller completion:(id /* block */)completion;
- (void)handleInAppMessage:(id)message presentingViewController:(id)controller completion:(id /* block */)completion;
- (void)triggerToggleAccount:(id)account on:(_Bool)on completion:(id /* block */)completion;
- (void)triggerUpdateAccountsEventWithOriginallySelectedAccounts:(id)accounts selectedAccounts:(id)accounts completion:(id /* block */)completion;
- (void)triggerToggleIncognitoMode:(_Bool)mode completion:(id /* block */)completion;
- (void)triggerDefaultAccountFlowWithPresentingVC:(id)vc completion:(id /* block */)completion;
- (void)triggerCustomActionWithIndexPath:(id)path accountMenuViewController:(id)controller;
- (void)triggerActionForCommonItem:(unsigned long long)item accountMenuPresenter:(id)presenter;
- (_Bool)triggerSessionShouldStart;
- (void)triggerSessionDidEnd;
- (void)invokeDelegateOfSession:(id)session shouldSwitchFromAccount:(id)account toAccount:(id)account callback:(id /* block */)callback;
- (void)invokeDelegateOfSession:(id)session switchFromAccount:(id)account toAccount:(id)account;
- (void)invokeDelegateOfSession:(id)session addedAccount:(id)account;
- (void)invokeDelegateOfSession:(id)session switchToNoAccountFromAccount:(id)account;
- (void)invokeDelegateOfSession:(id)session removeAccount:(id)account;
- (void)invokeDelegateOfSession:(id)session didFailAddRemoveAccountWithError:(id)error;
- (void)invokeDelegateOfSession:(id)session toggleAccount:(id)account on:(_Bool)on callback:(id /* block */)callback;
- (void)invokeDelegateOfSession:(id)session didUpdateFromSelectedAccounts:(id)accounts toSelectedAccounts:(id)accounts;
- (void)invokeDelegateOfSession:(id)session shouldToggleIncognitoMode:(_Bool)mode callback:(id /* block */)callback;
- (void)invokeDelegateOfSession:(id)session toggleIncognitoMode:(_Bool)mode;
- (_Bool)invokeDelegateOfSessionDidStart:(id)start;
- (void)invokeDelegateOfSessionDidEnd:(id)end;

@end

#endif /* OGLAccountMenuActionHandler_h */
