  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ORCH2SmsSenderData_h
#define ORCH2SmsSenderData_h
@import Foundation;

#include "GPBMessage.h"
#include "ORCH2PhoneNumber.h"

@class NSString;

@interface ORCH2SmsSenderData : GPBMessage

@property (retain, nonatomic) ORCH2PhoneNumber *smsPhoneNumber;
@property (nonatomic) _Bool hasSmsPhoneNumber;
@property (copy, nonatomic) NSString *smsMessage;
@property (nonatomic) _Bool hasSmsMessage;
@property (nonatomic) int subscriptionId;
@property (nonatomic) _Bool hasSubscriptionId;

/* class methods */
+ (id)descriptor;

@end

#endif /* ORCH2SmsSenderData_h */
