  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ORCH2UpdatePageClientCallbackDataValue_h
#define ORCH2UpdatePageClientCallbackDataValue_h
@import Foundation;

#include "GPBMessage.h"
#include "ORCH2IntegratorClientCallbackData.h"

@class NSMutableArray, NSString;

@interface ORCH2UpdatePageClientCallbackDataValue : GPBMessage

@property (retain, nonatomic) ORCH2IntegratorClientCallbackData *paymentData;
@property (nonatomic) _Bool hasPaymentData;
@property (copy, nonatomic) NSString *defaultSelectedShippingOptionName;
@property (nonatomic) _Bool hasDefaultSelectedShippingOptionName;
@property (retain, nonatomic) NSMutableArray *updatedCartItemsArray;
@property (readonly, nonatomic) unsigned long long updatedCartItemsArray_Count;
@property (copy, nonatomic) NSString *cartTotalPrice;
@property (nonatomic) _Bool hasCartTotalPrice;
@property (copy, nonatomic) NSString *cartTotalPriceLabel;
@property (nonatomic) _Bool hasCartTotalPriceLabel;

/* class methods */
+ (id)descriptor;

@end

#endif /* ORCH2UpdatePageClientCallbackDataValue_h */
