  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef OrchCardFieldValue_h
#define OrchCardFieldValue_h
@import Foundation;

#include "GPBMessage.h"
#include "OrchAddressFormValue.h"
#include "OrchOtpFieldValue.h"
#include "OrchUiFieldValue.h"

@interface OrchCardFieldValue : GPBMessage

@property (readonly, nonatomic) int cardFieldValueOneOfCase;
@property (retain, nonatomic) OrchUiFieldValue *uiFieldValue;
@property (nonatomic) _Bool hasUiFieldValue;
@property (retain, nonatomic) OrchAddressFormValue *addressFormValue;
@property (nonatomic) _Bool hasAddressFormValue;
@property (retain, nonatomic) OrchOtpFieldValue *otpFieldValue;
@property (nonatomic) _Bool hasOtpFieldValue;

/* class methods */
+ (id)descriptor;

@end

#endif /* OrchCardFieldValue_h */
