//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef OrchDebugGetPaymentMethodsParametersRequest_h
#define OrchDebugGetPaymentMethodsParametersRequest_h
@import Foundation;

#include "GPBMessage.h"
#include "OrchRequestContext.h"
#include "PaymentMethodsParameters.h"

@interface OrchDebugGetPaymentMethodsParametersRequest : GPBMessage

@property (retain, nonatomic) OrchRequestContext *context;
@property (nonatomic) _Bool hasContext;
@property (retain, nonatomic) PaymentMethodsParameters *parameters;
@property (nonatomic) _Bool hasParameters;

/* class methods */
+ (id)descriptor;

@end

#endif /* OrchDebugGetPaymentMethodsParametersRequest_h */
