  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ORCH2ExpectedLog_h
#define ORCH2ExpectedLog_h
@import Foundation;

#include "GPBMessage.h"
#include "ORCH2ExpectedLog_ExpectedFieldLog.h"
#include "ORCH2ExpectedLog_ExpectedVeLog.h"

@interface ORCH2ExpectedLog : GPBMessage

@property (readonly, nonatomic) int logOneOfCase;
@property (retain, nonatomic) ORCH2ExpectedLog_ExpectedVeLog *expectedVeLog;
@property (nonatomic) _Bool hasExpectedVeLog;
@property (retain, nonatomic) ORCH2ExpectedLog_ExpectedFieldLog *expectedFieldLog;
@property (nonatomic) _Bool hasExpectedFieldLog;
@property (nonatomic) int index;
@property (nonatomic) _Bool hasIndex;

/* class methods */
+ (id)descriptor;

@end

#endif /* ORCH2ExpectedLog_h */
