  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PHTBasePhenotypeFlagsProtocol_Protocol_h
#define PHTBasePhenotypeFlagsProtocol_Protocol_h
@import Foundation;

#include "PHTPhenotypeExperimentTokens.h"

@class NSString;

@protocol PHTBasePhenotypeFlagsProtocol

@required

@property (readonly, copy, nonatomic) NSString *packageName;
@property (readonly, copy, nonatomic) NSString *serverToken;
@property (readonly, nonatomic) PHTPhenotypeExperimentTokens *tokens;
@property (readonly, nonatomic) long long configurationVersion;

/* required instance methods */
- (void)startLoading;
- (id)valueForFlagName:(id)name withDefault:(id)_default;
- (id)stringForFlagName:(id)name defaultValue:(id)value;
- (id)numberForFlagName:(id)name defaultValue:(id)value;
- (id)dataForFlagName:(id)name defaultValue:(id)value;
- (id)stringArrayForFlagName:(id)name withDefault:(id)_default;
- (id)numberArrayForFlagName:(id)name withDefault:(id)_default;
- (id)snapshot;

@optional

@end

#endif /* PHTBasePhenotypeFlagsProtocol_Protocol_h */
