  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PHTInternalPhenotypeFlags_h
#define PHTInternalPhenotypeFlags_h
@import Foundation;

#include "OS_dispatch_queue-Protocol.h"
#include "PHTInternalPhenotypeFlagsProtocol-Protocol.h"
#include "PHTPhenotypeExperimentTokens.h"
#include "PHTPhenotypeFlagsSnapshot.h"

@class NSCondition, NSObject, NSString;

@interface PHTInternalPhenotypeFlags : NSObject <PHTInternalPhenotypeFlagsProtocol> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_workQueue;
}

@property (readonly, nonatomic) NSCondition *configsLoadedCondition;
@property (nonatomic) _Bool configsLoaded;
@property (nonatomic) _Bool startedLoading;
@property (retain) PHTPhenotypeFlagsSnapshot *atomicSnapshot;
@property (readonly, copy, nonatomic) NSString *packageName;
@property (readonly, copy, nonatomic) NSString *serverToken;
@property (readonly, nonatomic) PHTPhenotypeExperimentTokens *tokens;
@property (readonly, nonatomic) long long configurationVersion;

/* class methods */
+ (id)sharedInstance;
+ (id)resetSharedInstance;

/* instance methods */
- (id)initWithStartLoading:(_Bool)loading;
- (id)init;
- (id)initWithEmptySnapshot;
- (void)startLoading;
- (void)committedConfiguration:(id /* block */)configuration;
- (void)waitForConfigsToLoad;
- (void)configsFinishedLoading;
- (id)valueForFlagName:(id)name withDefault:(id)_default;
- (id)stringForFlagName:(id)name defaultValue:(id)value;
- (id)numberForFlagName:(id)name defaultValue:(id)value;
- (id)dataForFlagName:(id)name defaultValue:(id)value;
- (id)stringArrayForFlagName:(id)name withDefault:(id)_default;
- (id)numberArrayForFlagName:(id)name withDefault:(id)_default;
- (id)snapshot;
- (void)updateWithConfiguration:(id)configuration error:(id)error;
- (void)prepareForCommit;

@end

#endif /* PHTInternalPhenotypeFlags_h */
