  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PKTPeoplePickerStringsImpl_h
#define PKTPeoplePickerStringsImpl_h
@import Foundation;

#include "PKTPeoplePickerStrings-Protocol.h"

@class NSObject, NSString;

@interface PKTPeoplePickerStringsImpl : NSObject <PKTPeoplePickerStrings>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)suggestionsLabelText;
- (id)infoIconAccessibilityText;
- (id)previouslySelectedContactText;
- (id)aboutSuggestedPeopleAction;
- (id)aboutSuggestedPeopleTitle;
- (id)aboutSuggestedPeopleDescription;
- (id)aboutSuggestedPeopleLegaleseLinkText;
- (id)aboutSuggestedPeopleLegalese;
- (id)cancelText;
- (id)shareText;
- (id)selectPeopleText;
- (id)showDeviceContactsLabel;
- (id)showHiddenSuggestionsLabel;
- (id)phoneContactsLabel;
- (id)invalidRecipientTitle;
- (id)invalidRecipientDescription;
- (id)okAction;
- (id)hideContactSuggestionTitle;
- (id)hideContactSuggestionDescription;
- (id)hideText;
- (id)closeText;
- (id)expandButtonAccessibilityText;
- (id)settingsButtonText;
- (id)cantHideDeviceContactTitleText;
- (id)cantHideDeviceContactDescriptionText;
- (id)hideContactNoInternetTitle;
- (id)hideContactNoInternetDescription;
- (id)hideContactGenericErrorTitle;
- (id)hideContactGenericErrorDescription;
- (id)hideLargeGroupContactErrorTitle;
- (id)hideLargeGroupContactErrorDescription;
- (id)errorToast;
- (id)contextMenuIconAccessibilityText;
- (id)bundle;
- (id)searchResultsLabelText;

@end

#endif /* PKTPeoplePickerStringsImpl_h */
