@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PKTPopulousCoalescedContactImpl_h
#define PKTPopulousCoalescedContactImpl_h
@import Foundation;

#include "PDLPerson-Protocol.h"
#include "PKTContactImageOverride-Protocol.h"
#include "PKTDisjointContactMetadata.h"
#include "PKTPopulousCoalescedContact-Protocol.h"

@class NSObject, NSOrderedSet, NSString, NSURL, UIImage;

@interface PKTPopulousCoalescedContactImpl : NSObject <PKTPopulousCoalescedContact>

@property (readonly, nonatomic) id <PDLPerson> person;
@property (readonly, nonatomic) NSString *gaiaOverride;
@property (readonly, nonatomic) NSString *displayName;
@property (readonly, nonatomic) NSString *contactMethodValue;
@property (readonly, nonatomic) NSString *primaryDisplayableField;
@property (readonly, nonatomic) NSString *secondaryDisplayableField;
@property (readonly, nonatomic) NSString *disambigLabel;
@property (readonly, nonatomic) NSURL *photoUrl;
@property (readonly, nonatomic) unsigned int contactStructure;
@property (readonly, nonatomic) unsigned int provenance;
@property (readonly, nonatomic) NSString *identifier;
@property (readonly, nonatomic) int imageType;
@property (readonly, nonatomic) UIImage *badgeImage;
@property (readonly, nonatomic) unsigned long long attributes;
@property (readonly, nonatomic) id <PKTContactImageOverride> contactImageOverride;
@property (readonly, nonatomic) PKTDisjointContactMetadata *disjointContactMetadata;
@property (readonly, nonatomic) unsigned int hideCapability;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSOrderedSet *orderedContactMethods;

/* instance methods */
- (id)initWithContactMethods:(id)methods person:(id)person;
- (id)coalescedContact;
- (id)photoUrlForSize:(struct CGSize { double x0; double x1; })size;
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isEqual:(id)equal;

@end

#endif /* PKTPopulousCoalescedContactImpl_h */
