//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PLUPeopleLookupIos_Protocol_h
#define PLUPeopleLookupIos_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"
#include "PHTExperimentState-Protocol.h"

@protocol PLUPeopleLookupIos <NSObject, PHTExperimentState>

@required

@property (readonly, nonatomic) long long CacheValues__expired_data_interval_s;
@property (readonly, nonatomic) long long CacheValues__max_bulk_delete_row_limit;
@property (readonly, nonatomic) long long CacheValues__max_persistent_database_size;
@property (readonly, nonatomic) long long CacheValues__max_promise_cache_size;
@property (readonly, nonatomic) long long CacheValues__max_value_cache_size;
@property (readonly, nonatomic) long long CacheValues__persistent_database_cleanup_interval_s;
@property (readonly, nonatomic) long long CacheValues__persistent_database_cleanup_triggered_after_lookup_interval_s;
@property (readonly, nonatomic) long long CacheValues__stale_data_interval_s;
@property (readonly, nonatomic) long long OrphanFileCleanup__cleanup_interval_s;
@property (readonly, nonatomic) _Bool OrphanFileCleanup__enable_deleting_orphan_files;
@property (readonly, nonatomic) _Bool OrphanFileCleanup__enable_logging;
@property (readonly, nonatomic) _Bool EnableSelfProfileRefreshing__enable_self_profile_refreshing;
@property (readonly, nonatomic) _Bool EnableSelfProfileRefreshing__log_out_of_date_self;
@property (readonly, nonatomic) _Bool EnableSelfProfileRefreshing__remove_self_from_gmail_cache;

@optional

@end

#endif /* PLUPeopleLookupIos_Protocol_h */
