@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef POEMHangoutsExtendedData_h
#define POEMHangoutsExtendedData_h
@import Foundation;

#include "GPBMessage.h"

@interface POEMHangoutsExtendedData : GPBMessage

@property (nonatomic) _Bool isPinned;
@property (nonatomic) _Bool hasIsPinned;
@property (nonatomic) _Bool isFavorite;
@property (nonatomic) _Bool hasIsFavorite;
@property (nonatomic) _Bool isDismissed;
@property (nonatomic) _Bool hasIsDismissed;
@property (nonatomic) int hadPastHangoutState;
@property (nonatomic) _Bool hasHadPastHangoutState;
@property (nonatomic) int invitationStatus;
@property (nonatomic) _Bool hasInvitationStatus;
@property (nonatomic) int userType;
@property (nonatomic) _Bool hasUserType;
@property (nonatomic) _Bool isBot;
@property (nonatomic) _Bool hasIsBot;

/* class methods */
+ (id)descriptor;

@end

#endif /* POEMHangoutsExtendedData_h */
