@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PRDWebViewEventData_NativeNavigationButtonVisibility_h
#define PRDWebViewEventData_NativeNavigationButtonVisibility_h
@import Foundation;

#include "GPBMessage.h"

@interface PRDWebViewEventData_NativeNavigationButtonVisibility : GPBMessage

@property (nonatomic) _Bool showBackButton;
@property (nonatomic) _Bool hasShowBackButton;
@property (nonatomic) _Bool showCloseButton;
@property (nonatomic) _Bool hasShowCloseButton;
@property (nonatomic) _Bool showNavigationBar;
@property (nonatomic) _Bool hasShowNavigationBar;

/* class methods */
+ (id)descriptor;

@end

#endif /* PRDWebViewEventData_NativeNavigationButtonVisibility_h */
