  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PRMCoreManager_h
#define PRMCoreManager_h
@import Foundation;

#include "GIPPseudonymousEnableListener-Protocol.h"
#include "OS_dispatch_queue-Protocol.h"
#include "PRMApplicationStateService-Protocol.h"
#include "PRMCollectibleProvider-Protocol.h"
#include "PRMFlightRecorderCleanupService-Protocol.h"
#include "PRMInstantCollectible-Protocol.h"
#include "PRMLoggerProvider-Protocol.h"
#include "PRMLowPowerModeService.h"
#include "PRMManager-Protocol.h"
#include "PRMManagerPrivate-Protocol.h"
#include "PRMMemoryCollectionOptions.h"
#include "PRMPrimesIos-Protocol.h"
#include "PRMSamplingManager.h"
#include "PRMScheduler.h"
#include "SRLClassFilterableForGIPPseudonymousEnableListener-Protocol.h"

@class NSMapTable, NSMutableArray, NSMutableOrderedSet, NSObject, NSString;
@protocol PRMManagerDelegate;

@interface PRMCoreManager : NSObject <PRMManager, PRMManagerPrivate, GIPPseudonymousEnableListener, SRLClassFilterableForGIPPseudonymousEnableListener> {
    /* instance variables */
    id <PRMApplicationStateService> _applicationStateService;
    id <PRMPrimesIos> _flags;
    PRMLowPowerModeService *_lowPowerModeService;
    PRMSamplingManager *_samplingManager;
    PRMScheduler *_scheduler;
    id <PRMCollectibleProvider> _collectibleProvider;
    id <PRMLoggerProvider> _loggerProvider;
    NSMutableOrderedSet *_transmitters;
    NSMapTable *_collectionOptions;
    _Bool _isLaunched;
    int _eventTransmissionMode;
    NSMutableArray *_queuedEvents;
    NSObject<OS_dispatch_queue> *_transmitCompletionQueue;
    NSObject<OS_dispatch_queue> *_launchQueue;
    id <PRMInstantCollectible> _crashpadInstantCollectible;
    id /* block */ _flightRecorderInjector;
    id <PRMFlightRecorderCleanupService> _flightRecorderCleanupService;
}

@property (readonly, nonatomic) _Bool isStarted;
@property (readonly, copy) NSString *gaiaIdentifierForTransmission;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) PRMMemoryCollectionOptions *memoryCollectionOptions;
@property (weak, nonatomic) id <PRMManagerDelegate> delegate;

/* class methods */
+ (_Bool)isIncludedForGIPPseudonymousEnableListener;

/* instance methods */
- (id)initWithApplicationStateService:(id)service collectibleProvider:(id)provider flags:(id)flags flightRecorderCleanupService:(id)service loggerProvider:(id)provider flightRecorderInjector:(id /* block */)injector;
- (void)launch;
- (void)launchWithEventTransmissionMode:(int)mode;
- (void)setUpLoggingIfNeeded;
- (void)denylistDefaultCollectibleSetupwithClass:(Class)_class;
- (void)allowlistDefaultCollectibleSetupwithClass:(Class)_class;
- (id)scheduler;
- (void)addTransmitter:(id)transmitter;
- (void)startCollectingType:(unsigned long long)type onEventWithName:(id)name;
- (void)stopCollectingType:(unsigned long long)type onEventWithName:(id)name;
- (void)collectType:(unsigned long long)type onEventWithName:(id)name;
- (id)applicationStateService;
- (id)lowPowerModeService;
- (id)samplingManager;
- (void)transmitCollectedMetric:(id)metric eventContext:(id)context;
- (void)transmitCollectedMetric:(id)metric eventContext:(id)context completion:(id /* block */)completion;
- (void)setEventTransmissionMode:(int)mode;
- (id)optionsForOptionsClass:(Class)_class;
- (void)pseudonymousIDWasEnabled;

@end

#endif /* PRMCoreManager_h */
