//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PRMLowPowerModeService_Protocol_h
#define PRMLowPowerModeService_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol PRMLowPowerModeService <NSObject>

@required

@property (readonly) long long lowPowerMode;

@optional

@end

#endif /* PRMLowPowerModeService_Protocol_h */
