@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PRMTraceConfigurationBuilder_h
#define PRMTraceConfigurationBuilder_h
@import Foundation;

@class NSObject;

@interface PRMTraceConfigurationBuilder : NSObject {
    /* instance variables */
    _Bool _captureCPUTimeForTraceContextRoots_34;
    _Bool _benchmarkingMode_16;
    _Bool _enableSignposts_15;
    unsigned int _maxEntities_11;
    double _timeout_7;
    double _traceSamplingRate_17;
}

@property (nonatomic) _Bool vgn__timeout_hazzer;
@property (nonatomic) _Bool vgn__maxEntities_hazzer;
@property (nonatomic) double traceSamplingRate;
@property (nonatomic) _Bool captureCPUTimeForTraceContextRoots;
@property (nonatomic) _Bool benchmarkingMode;
@property (nonatomic) _Bool enableSignposts;
@property (nonatomic) double timeout;
@property (nonatomic) unsigned int maxEntities;

/* class methods */
+ (id)builder;
+ (id)builderFromExistingObject:(id)object;

/* instance methods */
- (id)init;
- (id)build;

@end

#endif /* PRMTraceConfigurationBuilder_h */
