//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PUDUISuggestionInteractionRequest_h
#define PUDUISuggestionInteractionRequest_h
@import Foundation;

#include "GPBMessage.h"

@class NSString;

@interface PUDUISuggestionInteractionRequest : GPBMessage

@property (copy, nonatomic) NSString *predictionId;
@property (nonatomic) _Bool hasPredictionId;
@property (copy, nonatomic) NSString *reportingId;
@property (nonatomic) _Bool hasReportingId;
@property (nonatomic) int userAction;
@property (nonatomic) _Bool hasUserAction;

/* class methods */
+ (id)descriptor;

@end

#endif /* PUDUISuggestionInteractionRequest_h */
