@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef SAFPAppEvent_h
#define SAFPAppEvent_h
@import Foundation;

#include "GPBMessage.h"
#include "SAFPAppEventExtension.h"
#include "SAFPEventType.h"
#include "SLOEvent_Result.h"

@interface SAFPAppEvent : GPBMessage

@property (retain, nonatomic) SAFPEventType *type;
@property (nonatomic) _Bool hasType;
@property (retain, nonatomic) SLOEvent_Result *result;
@property (nonatomic) _Bool hasResult;
@property (retain, nonatomic) SAFPAppEventExtension *details;
@property (nonatomic) _Bool hasDetails;
@property (nonatomic) unsigned long long tiktokTraceUuidMostSignificantBits;
@property (nonatomic) _Bool hasTiktokTraceUuidMostSignificantBits;
@property (nonatomic) unsigned long long tiktokTraceUuidLeastSignificantBits;
@property (nonatomic) _Bool hasTiktokTraceUuidLeastSignificantBits;
@property (nonatomic) int tiktokTraceSpanId;
@property (nonatomic) _Bool hasTiktokTraceSpanId;

/* class methods */
+ (id)descriptor;

@end

#endif /* SAFPAppEvent_h */
