  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef SLOGSocialAffinityExtension_SmartAddressEntityMetadata_h
#define SLOGSocialAffinityExtension_SmartAddressEntityMetadata_h
@import Foundation;

#include "GPBMessage.h"
#include "SLOGSocialAffinityExtension_SocialAffinityEntityPosition.h"

@class NSString;

@interface SLOGSocialAffinityExtension_SmartAddressEntityMetadata : GPBMessage

@property (nonatomic) int existingSelectionsCount;
@property (nonatomic) _Bool hasExistingSelectionsCount;
@property (retain, nonatomic) SLOGSocialAffinityExtension_SocialAffinityEntityPosition *position;
@property (nonatomic) _Bool hasPosition;
@property (copy, nonatomic) NSString *replacementOriginEmailAddress;
@property (nonatomic) _Bool hasReplacementOriginEmailAddress;
@property (copy, nonatomic) NSString *replacementDestinationEmailAddress;
@property (nonatomic) _Bool hasReplacementDestinationEmailAddress;

/* class methods */
+ (id)descriptor;

@end

#endif /* SLOGSocialAffinityExtension_SmartAddressEntityMetadata_h */
