@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef SSOFolsomSwiftEnrollPublicKeyServiceImpl_h
#define SSOFolsomSwiftEnrollPublicKeyServiceImpl_h
@import Foundation;

#include "SSOFolsomPublicKeyResponse.h"
#include "SSOFolsomSwiftEnrollPublicKeyLoggerDelegate-Protocol.h"
#include "SSOFolsomSwiftEnrollPublicKeyService-Protocol.h"

@class NSObject, lifecycleConfigurationService;

@interface SSOFolsomSwiftEnrollPublicKeyServiceImpl : NSObject <SSOFolsomSwiftEnrollPublicKeyService> { // (Swift)
    /* instance variables */
    lifecycleConfigurationService gaiaAccountID;
    lifecycleConfigurationService rpcService;
    lifecycleConfigurationService sharedKeysService;
}

/* instance methods */
- (void)enrollWithPublicKeyResponse:(SSOFolsomPublicKeyResponse *)response loggerDelegate:(<SSOFolsomSwiftEnrollPublicKeyLoggerDelegate> *)delegate completionHandler:(id /* block */)handler;
- (id)init;

@end

#endif /* SSOFolsomSwiftEnrollPublicKeyServiceImpl_h */
