  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef SSOFolsomFlagService_Protocol_h
#define SSOFolsomFlagService_Protocol_h
@import Foundation;

@protocol SSOFolsomFlagService

@required

@property (nonatomic, readonly) _Bool isPhysicalDeviceEnrollmentEnabledInOpportunisticRetrieval;
@property (nonatomic, readonly) long long syncThrottleRateHours;
@property (nonatomic, readonly) long long gpmPinSyncFrequencyDays;
@property (nonatomic, readonly) _Bool enableGPMPinSync;
@property (nonatomic, readonly) _Bool enableRemovePreEnrollmentWaveAfterReset;
@property (nonatomic, readonly) _Bool enableActionHandlerForGpmPinUi;
@property (nonatomic, readonly) _Bool enableWriteKeyStalenessToKeychain;
@property (nonatomic, readonly) long long syncLocalKeysThrottleRateSeconds;
@property (nonatomic, readonly) _Bool enableHandlingConstantKeyDuringIcloudKeychainRetrieval;
@property (nonatomic, readonly) _Bool enableSyncDomainStateInSetup;
@property (nonatomic, readonly) _Bool enableKeyRetrievalWithForceSync;
@property (nonatomic, readonly) _Bool enableMaybePreEnroll;
@property (nonatomic, readonly) _Bool enablePreEnrollmentForODLH;
@property (nonatomic, readonly) _Bool enableIcloudKeychainPreEnrollmentForChromesync;

@optional

@end

#endif /* SSOFolsomFlagService_Protocol_h */
