  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef SSOFolsomKeychainService_Protocol_h
#define SSOFolsomKeychainService_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol SSOFolsomKeychainService <NSObject>

@required

/* required instance methods */
- (_Bool)writeSharedKeys:(id)keys forSecurityDomain:(id)domain error:(id *)error;
- (void)writeSharedKeys:(id)keys forSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (id)sharedKeysForSecurityDomain:(id)domain error:(id *)error;
- (void)getSharedKeysForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (_Bool)removeSharedKeysForSecurityDomain:(id)domain error:(id *)error;
- (void)removeSharedKeysForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (_Bool)writeEncryptionPrivateKey:(id)key error:(id *)error;
- (_Bool)writeEncryptionPrivateKeyAndWait:(id)wait error:(id *)error;
- (void)writeEncryptionPrivateKey:(id)key completionQueue:(id)queue completion:(id /* block */)completion;
- (id)encryptionPrivateKeyWithError:(id *)error;
- (id)getEncryptionPrivateKeyAndWaitWithError:(id *)error;
- (void)getEncryptionPrivateKeyWithCompletionQueue:(id)queue completion:(id /* block */)completion;
- (void)writeCloudPrivateKey:(id)key forPublicKey:(id)key securityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)cloudPrivateKeyForPublicKey:(id)key securityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)removeCloudPrivateKeyForPublicKey:(id)key completionQueue:(id)queue completion:(id /* block */)completion;
- (void)writeKeyStaleness:(_Bool)staleness forSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)getKeyStalenessForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (_Bool)writeJoinVersion:(id)version forSecurityDomain:(id)domain error:(id *)error;
- (void)writeJoinVersion:(id)version forSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (id)joinVersionForSecurityDomain:(id)domain error:(id *)error;
- (void)joinVersionForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (_Bool)removeJoinVersionForSecurityDomain:(id)domain error:(id *)error;
- (void)removeJoinVersionForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (_Bool)writePreEnrollmentWave:(id)wave forSecurityDomain:(id)domain error:(id *)error;
- (void)writePreEnrollmentWave:(id)wave forSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (id)preEnrollmentWaveForSecurityDomain:(id)domain error:(id *)error;
- (void)preEnrollmentWaveForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (_Bool)removePreEnrollmentWaveForSecurityDomain:(id)domain error:(id *)error;
- (void)removePreEnrollmentWaveForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)writeLastSyncDate:(id)date forSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)lastSyncDateForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)removeLastSyncDateForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)writeLastGPMPinSyncDate:(id)date forSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)getLastGPMPinSyncDateForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)removeLastGPMPinSyncDateForSecurityDomain:(id)domain completionQueue:(id)queue completion:(id /* block */)completion;
- (void)writeLastProviderKeypairSyncDate:(id)date completionQueue:(id)queue completion:(id /* block */)completion;
- (void)getLastProviderKeypairSyncDateWithCompletionQueue:(id)queue completion:(id /* block */)completion;
- (void)removeLastProviderKeypairSyncDateWithCompletionQueue:(id)queue completion:(id /* block */)completion;
- (_Bool)removeAllDataWithError:(id *)error;
- (void)removeAllDataWithCompletionQueue:(id)queue completion:(id /* block */)completion;

@optional

@end

#endif /* SSOFolsomKeychainService_Protocol_h */
