//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef SSOLoginScopedAuthorizationArgs_h
#define SSOLoginScopedAuthorizationArgs_h
@import Foundation;

@class NSError, NSMutableURLRequest, NSObject, NSThread;

@interface SSOLoginScopedAuthorizationArgs : NSObject

@property (retain) NSMutableURLRequest *request;
@property (copy) id /* block */ handler;
@property (retain) id delegate;
@property SEL selector;
@property (retain) NSThread *thread;
@property (retain) NSError *error;

/* class methods */
+ (id)argsWithRequest:(id)request handler:(id /* block */)handler delegate:(id)delegate selector:(SEL)selector thread:(id)thread;

/* instance methods */

@end

#endif /* SSOLoginScopedAuthorizationArgs_h */
