  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef SSOMacaroonAccessToken_h
#define SSOMacaroonAccessToken_h
@import Foundation;

#include "GPBMessage.h"

@class NSData, NSMutableArray;

@interface SSOMacaroonAccessToken : GPBMessage

@property (copy, nonatomic) NSData *opaqueData;
@property (nonatomic) _Bool hasOpaqueData;
@property (retain, nonatomic) NSMutableArray *caveatsArray;
@property (readonly, nonatomic) unsigned long long caveatsArray_Count;
@property (copy, nonatomic) NSData *mac;
@property (nonatomic) _Bool hasMac;
@property (copy, nonatomic) NSData *header;
@property (nonatomic) _Bool hasHeader;
@property (copy, nonatomic) NSData *credentialAttributes;
@property (nonatomic) _Bool hasCredentialAttributes;
@property (nonatomic) _Bool isExperimentalToken;
@property (nonatomic) _Bool hasIsExperimentalToken;

/* class methods */
+ (id)descriptor;

@end

#endif /* SSOMacaroonAccessToken_h */
