  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef SUPSupportWebContentsController_h
#define SUPSupportWebContentsController_h
@import Foundation;

#include "SUPSupportContentService.h"
#include "SUPSupportWebContentsControllerDelegate-Protocol.h"
#include "SUPSupportWebContentsView.h"
#include "WKNavigationDelegate-Protocol.h"

@class NSMutableArray, NSObject, NSString;

@interface SUPSupportWebContentsController : NSObject <WKNavigationDelegate> {
    /* instance variables */
    SUPSupportContentService *_supportContentService;
    NSMutableArray *_webContentObjects;
}

@property (nonatomic) _Bool loadingSupportContent;
@property (weak, nonatomic) id <SUPSupportWebContentsControllerDelegate> delegate;
@property (readonly, nonatomic) SUPSupportWebContentsView *view;
@property (nonatomic) unsigned long long colorTheme;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame supportContentService:(id)service;
- (void)webView:(id)view decidePolicyForNavigationAction:(id)action decisionHandler:(id /* block */)handler;
- (void)webView:(id)view didStartProvisionalNavigation:(id)navigation;
- (void)displaySupportWebContentForURL:(id)url overrideTitle:(id)title;
- (void)popSupportWebContentFromStack;
- (unsigned long long)webViewStackCount;
- (void)cleanupWebContents;
- (void)updateWebViewFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)handleLinkURL:(id)url fromURL:(id)url overrideTitle:(id)title;
- (id)webViewFromHTML:(id)html baseURL:(id)url;
- (void)fetchRenderedContent:(id)content isDeepLink:(_Bool)link overrideTitle:(id)title;
- (id)displayedSupportWebContentTitle;
- (id)displayedSupportWebContentURL;
- (void)updateSupportWebContentWithRequestedURL:(id)url;
- (void)displayWebContentObjectWithWebView:(id)view title:(id)title;

@end

#endif /* SUPSupportWebContentsController_h */
