  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef TCLPackageDownloadInfo_h
#define TCLPackageDownloadInfo_h
@import Foundation;

#include "GPBMessage.h"

@class NSString;

@interface TCLPackageDownloadInfo : GPBMessage

@property (copy, nonatomic) NSString *sourceLanguage;
@property (nonatomic) _Bool hasSourceLanguage;
@property (copy, nonatomic) NSString *targetLanguage;
@property (nonatomic) _Bool hasTargetLanguage;
@property (nonatomic) int downloadObject;
@property (nonatomic) _Bool hasDownloadObject;
@property (nonatomic) int downloadType;
@property (nonatomic) _Bool hasDownloadType;
@property (nonatomic) int downloadInitiationLocation;
@property (nonatomic) _Bool hasDownloadInitiationLocation;
@property (nonatomic) int downloadMode;
@property (nonatomic) _Bool hasDownloadMode;
@property (nonatomic) int downloadStatus;
@property (nonatomic) _Bool hasDownloadStatus;
@property (nonatomic) int minorVersion;
@property (nonatomic) _Bool hasMinorVersion;
@property (nonatomic) int majorVersion;
@property (nonatomic) _Bool hasMajorVersion;
@property (nonatomic) _Bool retry;
@property (nonatomic) _Bool hasRetry;
@property (nonatomic) _Bool background;
@property (nonatomic) _Bool hasBackground;

/* class methods */
+ (id)descriptor;

@end

#endif /* TCLPackageDownloadInfo_h */
