@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef UFRSportsFeedbackContext_h
#define UFRSportsFeedbackContext_h
@import Foundation;

#include "GPBMessage.h"

@class NSString;

@interface UFRSportsFeedbackContext : GPBMessage

@property (copy, nonatomic) NSString *transcript;
@property (nonatomic) _Bool hasTranscript;
@property (nonatomic) int matchStatus;
@property (nonatomic) _Bool hasMatchStatus;
@property (copy, nonatomic) NSString *languageSelected;
@property (nonatomic) _Bool hasLanguageSelected;
@property (nonatomic) _Bool captionEnabled;
@property (nonatomic) _Bool hasCaptionEnabled;
@property (nonatomic) int inGameTimeMinutes;
@property (nonatomic) _Bool hasInGameTimeMinutes;
@property (nonatomic) int inGameTimeSeconds;
@property (nonatomic) _Bool hasInGameTimeSeconds;
@property (nonatomic) int firstTeamScore;
@property (nonatomic) _Bool hasFirstTeamScore;
@property (nonatomic) int secondTeamScore;
@property (nonatomic) _Bool hasSecondTeamScore;
@property (nonatomic) _Bool firstTeamWon;
@property (nonatomic) _Bool hasFirstTeamWon;
@property (nonatomic) _Bool secondTeamWon;
@property (nonatomic) _Bool hasSecondTeamWon;
@property (nonatomic) _Bool isMatchLive;
@property (nonatomic) _Bool hasIsMatchLive;
@property (nonatomic) _Bool isPreMatch;
@property (nonatomic) _Bool hasIsPreMatch;
@property (nonatomic) _Bool isPostMatch;
@property (nonatomic) _Bool hasIsPostMatch;
@property (copy, nonatomic) NSString *matchEndTime;
@property (nonatomic) _Bool hasMatchEndTime;
@property (copy, nonatomic) NSString *firstTeamScoreString;
@property (nonatomic) _Bool hasFirstTeamScoreString;
@property (copy, nonatomic) NSString *secondTeamScoreString;
@property (nonatomic) _Bool hasSecondTeamScoreString;
@property (copy, nonatomic) NSString *feedbackRecordedTimestamp;
@property (nonatomic) _Bool hasFeedbackRecordedTimestamp;
@property (copy, nonatomic) NSString *leagueName;
@property (nonatomic) _Bool hasLeagueName;
@property (copy, nonatomic) NSString *leagueId;
@property (nonatomic) _Bool hasLeagueId;
@property (copy, nonatomic) NSString *matchId;
@property (nonatomic) _Bool hasMatchId;
@property (nonatomic) _Bool hasLiveInGameUpdates;
@property (nonatomic) _Bool hasHasLiveInGameUpdates;
@property (copy, nonatomic) NSString *firstTeamName;
@property (nonatomic) _Bool hasFirstTeamName;
@property (copy, nonatomic) NSString *secondTeamName;
@property (nonatomic) _Bool hasSecondTeamName;
@property (copy, nonatomic) NSString *URLToMatchOsrp;
@property (nonatomic) _Bool hasURLToMatchOsrp;
@property (copy, nonatomic) NSString *localizedStartDateAndTime;
@property (nonatomic) _Bool hasLocalizedStartDateAndTime;
@property (copy, nonatomic) NSString *matchStartTime;
@property (nonatomic) _Bool hasMatchStartTime;

/* class methods */
+ (id)descriptor;

@end

#endif /* UFRSportsFeedbackContext_h */
