@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef UIPopoverPresentationControllerDelegate_Protocol_h
#define UIPopoverPresentationControllerDelegate_Protocol_h
@import Foundation;

#include "UIAdaptivePresentationControllerDelegate-Protocol.h"

@protocol UIPopoverPresentationControllerDelegate <UIAdaptivePresentationControllerDelegate>

@required

@optional

/* optional instance methods */
- (void)prepareForPopoverPresentation:(id)presentation;
- (_Bool)popoverPresentationControllerShouldDismissPopover:(id)popover;
- (void)popoverPresentationControllerDidDismissPopover:(id)popover;
- (void)popoverPresentationController:(id)controller willRepositionPopoverToRect:(inout struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } *)rect inView:(inout id *)view;
- (void)popoverPresentationController:(id)controller willRepositionPopoverToRect:(inout struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } *)rect inView:(inout id *)view;

@end

#endif /* UIPopoverPresentationControllerDelegate_Protocol_h */
