@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef UVSCheckableTextContentView_h
#define UVSCheckableTextContentView_h
@import Foundation;

#include "GOOBaseContentView.h"
#include "GOOTextField.h"
#include "SUPCheckbox.h"
#include "SUPCheckboxDelegate-Protocol.h"
#include "UITextFieldDelegate-Protocol.h"
#include "UVSCheckableTextObjectInternalObserver-Protocol.h"

@class NSString, UILabel;

@interface UVSCheckableTextContentView : GOOBaseContentView <UVSCheckableTextObjectInternalObserver, SUPCheckboxDelegate, UITextFieldDelegate> {
    /* instance variables */
    SUPCheckbox *_checkbox;
    UILabel *_textLabel;
    GOOTextField *_textField;
    NSString *_previousWriteInText;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (double)heightForObject:(id)object constrainedToWidth:(double)width;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)prepareForReuse;
- (void)traitCollectionDidChange:(id)change;
- (void)updateViewWithObject:(id)object;
- (id)accessibilityLabel;
- (void)checkableTextObject:(id)object didUpdateChecked:(_Bool)checked;
- (void)didTapCheckbox:(id)checkbox checked:(_Bool)checked;
- (void)textFieldDidBeginEditing:(id)editing;
- (void)textFieldDidEndEditing:(id)editing;
- (_Bool)textFieldShouldReturn:(id)_return;
- (void)updateObjectCheckState:(_Bool)state;
- (void)setUpCheckboxConstraints;
- (void)setUpConstraintsForTextView:(id)view topPadding:(double)padding leadingPadding:(double)padding;
- (void)textDidChange:(id)change;
- (id)textLabelWithObject:(id)object;
- (id)textFieldWithObject:(id)object;
- (void)updateSubviewsWithObject:(id)object;
- (void)updateAccessibilityTraits;

@end

#endif /* UVSCheckableTextContentView_h */
