@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YCHLiveChatPriorityQueue_h
#define YCHLiveChatPriorityQueue_h
@import Foundation;

@class NSMutableArray, NSObject;

@interface YCHLiveChatPriorityQueue : NSObject {
    /* instance variables */
    NSMutableArray *_queue;
}

/* instance methods */
- (id)init;
- (void)enqueue:(id)enqueue;
- (id)dequeue;
- (id)peek;
- (id)filteredQueue:(id)queue;
- (id)firstEntryMatchingPredicate:(id)predicate;
- (void)remove:(id)remove;
- (unsigned long long)count;
- (void)clear;

@end

#endif /* YCHLiveChatPriorityQueue_h */
