@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTActiveViewExtension_h
#define YTActiveViewExtension_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSArray, NSObject;

@interface YTActiveViewExtension : NSObject <NSCopying>

@property (readonly, nonatomic) NSArray *viewableImpressionPings;
@property (readonly, nonatomic) NSArray *measurableImpressionPings;
@property (readonly, nonatomic) NSArray *groupMImpressionPings;
@property (readonly, nonatomic) NSArray *audioMeasurablePings;
@property (readonly, nonatomic) NSArray *audioAudiblePings;
@property (readonly, nonatomic) int trafficType;

/* instance methods */
- (id)initWithViewableImpressionPings:(id)pings measurableImpressionPings:(id)pings groupMImpressionPings:(id)pings audioAudiblePings:(id)pings audioMeasurablePings:(id)pings trafficType:(int)type;
- (id)init;
- (id)merge:(id)merge;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* YTActiveViewExtension_h */
