  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTAdEngagementPanelActionTriggerAdapterImpl_h
#define YTAdEngagementPanelActionTriggerAdapterImpl_h
@import Foundation;

#include "YTAdEngagementPanelActionTriggerAdapter-Protocol.h"
#include "YTEngagementPanelEventObserver-Protocol.h"
#include "YTLayoutEnteredEventListener-Protocol.h"
#include "YTLayoutExitedEventListener-Protocol.h"
#include "YTTriggerAdapter-Protocol.h"
#include "YTTriggerAdapterDelegate-Protocol.h"

@class NSMutableDictionary, NSMutableSet, NSObject, NSString;

@interface YTAdEngagementPanelActionTriggerAdapterImpl : NSObject <YTTriggerAdapter, YTLayoutEnteredEventListener, YTLayoutExitedEventListener, YTEngagementPanelEventObserver, YTAdEngagementPanelActionTriggerAdapter> {
    /* instance variables */
    id <YTTriggerAdapterDelegate> _delegate;
    NSMutableDictionary *_registeredTriggers;
    NSMutableSet *_enteredLayoutIDs;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)onEngagementPanelCloseRequested;
- (void)onAutoCloseEngagementPanel;
- (_Bool)registerTrigger:(id)trigger withTriggerCategory:(unsigned long long)category slot:(id)slot layout:(id)layout;
- (void)unregisterTrigger:(id)trigger;
- (void)didEnterLayout:(id)layout forSlot:(id)slot;
- (void)didExitLayout:(id)layout forSlot:(id)slot exitReason:(unsigned long long)reason;
- (void)startObservingAdsControlFlowEvent;

@end

#endif /* YTAdEngagementPanelActionTriggerAdapterImpl_h */
