  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTAdWatchNextResponseOpportunityAdapter_Protocol_h
#define YTAdWatchNextResponseOpportunityAdapter_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol YTAdWatchNextResponseOpportunityAdapter <NSObject>

@required

/* class methods */
+ (id)alloc;
+ (id)new;

/* required instance methods */
- (id)init;
- (void)didReceiveAdWatchNextResponse:(id)response instreamAd:(id)ad playerBytesLayoutID:(id)id contentCPN:(id)cpn playerResponse:(id)response;

@optional

@end

#endif /* YTAdWatchNextResponseOpportunityAdapter_Protocol_h */
