  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTAdsPlayerServices_Protocol_h
#define YTAdsPlayerServices_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol YTAdsPlayerServices <NSObject>

@required

/* required instance methods */
- (id)adVideoPlayerOverlayWithParentResponder:(id)responder;
- (id)forceInDisplayAdsMenuWith:(id)with parentResponder:(id)responder;
- (id)forceInDisplayAdsMenuWithBackButton:(_Bool)button scrollsToTopCoordinator:(id)coordinator parentResponder:(id)responder;
- (id)forceInstreamAdsMenuWith:(id)with parentResponder:(id)responder;
- (id)forceInstreamAdsMenuWithBackButton:(_Bool)button scrollsToTopCoordinator:(id)coordinator parentResponder:(id)responder;

@optional

@end

#endif /* YTAdsPlayerServices_Protocol_h */
