@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTALSettingItemCell_h
#define YTALSettingItemCell_h
@import Foundation;

#include "GA11YMixinEmbedder-Protocol.h"
#include "GA11YMixinImpl-Protocol.h"
#include "YTCollectionViewCell.h"
#include "YTCollectionViewCellProtocol-Protocol.h"
#include "YTIAccountLinkSettingItemRenderer.h"
#include "YTImageView.h"
#include "YTLabel.h"
#include "YTPageStyling-Protocol.h"
#include "YTResponder-Protocol.h"
#include "YTThumbnailMapping-Protocol.h"
#include "YTThumbnailMapping.h"

@class NSString;

@interface YTALSettingItemCell : YTCollectionViewCell <GA11YMixinEmbedder, YTThumbnailMapping, YTPageStyling, YTCollectionViewCellProtocol> {
    /* instance variables */
    YTLabel *_titleLabel;
    YTLabel *_linkedStatusLabel;
    YTImageView *_thumbnailImageView;
    YTThumbnailMapping *_thumbnailImageMapping;
    YTIAccountLinkSettingItemRenderer *_renderer;
    long long _pageStyle;
}

@property (nonatomic) _Bool useUpdatedSettingsColors;
@property (readonly, nonatomic) id <GA11YMixinImpl> accessibilityMixin;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <YTResponder> parentResponder;
@property (nonatomic) _Bool isShowingInNonFullscreenModal;

/* class methods */
+ (struct CGSize { double x0; double x1; })cellSizeForEntry:(id)entry size:(struct CGSize { double x0; double x1; })size;
+ (struct CGSize { double x0; double x1; })cellSizeForEntry:(id)entry size:(struct CGSize { double x0; double x1; })size safeAreaInsets:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })insets;
+ (struct CGSize { double x0; double x1; })preferredSizeForEntry:(id)entry size:(struct CGSize { double x0; double x1; })size;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (void)updateLinkedStatusIfNeeded;
- (void)setEntry:(id)entry;
- (id)entry;
- (long long)accessibilityElementCount;
- (id)accessibilityElementAtIndex:(long long)index;
- (long long)indexOfAccessibilityElement:(id)element;
- (id)accessibilityElements;
- (_Bool)isAccessibilityElement;
- (id)accessibilityLabel;
- (id)accessibleViews;
- (void)prepareForReuse;
- (id)thumbnailMappings;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(id)superview;
- (void)pageStyleDidChange:(long long)change;
- (void)resetThumbnailImageView;

@end

#endif /* YTALSettingItemCell_h */
