//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTAppStoreBottomSheetCommandHandler_h
#define YTAppStoreBottomSheetCommandHandler_h
@import Foundation;

#include "YTBottomSheetControllerDelegate-Protocol.h"

@class NSObject, NSString, SKStoreProductViewController;

@interface YTAppStoreBottomSheetCommandHandler : NSObject <YTBottomSheetControllerDelegate> {
    /* instance variables */
    SKStoreProductViewController *storeProductViewController;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)executeWithCommand:(id)command entry:(id)entry fromView:(id)view sender:(id)sender containerController:(id)controller;
- (void)bottomSheetControllerDidCancel:(id)cancel;

@end

#endif /* YTAppStoreBottomSheetCommandHandler_h */
