  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTAppBackgroundTasksController_h
#define YTAppBackgroundTasksController_h
@import Foundation;

#include "YTBackgroundTasksController-Protocol.h"

@class NSArray, NSObject, NSString;

@interface YTAppBackgroundTasksController : NSObject <YTBackgroundTasksController> {
    /* instance variables */
    NSArray *_refreshTasks;
    NSArray *_processingTasks;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)registerBackgroundTasks;
- (void)scheduleBackgroundTasks;
- (void)disableBackgroundTaskWithIdentifier:(id)identifier;
- (void)performRefreshTasksWithCompletionHandler:(id /* block */)handler;
- (void)performProcessingTask:(id)task completionHandler:(id /* block */)handler;
- (void)expireRefreshTasks;
- (void)handleRefreshTask:(id)task;
- (void)handleProcessingTask:(id)task taskInfo:(id)info;
- (void)scheduleAppRefreshTask:(id)task;
- (void)scheduleProcessingTask:(id)task startInterval:(id)interval;
- (void)prepareAppForBackgroundRefreshTask;
- (void)setRefreshTasks:(id)tasks;
- (void)setProcessingTasks:(id)tasks;

@end

#endif /* YTAppBackgroundTasksController_h */
