  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTBackstageCreateRepostHeaderView_h
#define YTBackstageCreateRepostHeaderView_h
@import Foundation;

#include "YTBackstageCreateRepostHeaderViewDelegate-Protocol.h"
#include "YTFormattedStringLabel.h"
#include "YTIBackstageRepostCreationRenderer.h"
#include "YTPageStyling-Protocol.h"
#include "YTQTMButton.h"

@class NSString, UIView;

@interface YTBackstageCreateRepostHeaderView : UIView <YTPageStyling> {
    /* instance variables */
    YTIBackstageRepostCreationRenderer *_renderer;
    id <YTBackstageCreateRepostHeaderViewDelegate> _delegate;
    YTFormattedStringLabel *_titleLabel;
    YTQTMButton *_postButton;
    long long _pageStyle;
}

@property (nonatomic) _Bool postEnabled;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithRepostRenderer:(id)renderer delegate:(id)delegate;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)didTapPost;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(id)superview;
- (void)pageStyleDidChange:(long long)change;

@end

#endif /* YTBackstageCreateRepostHeaderView_h */
