  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTClientSamplerGate_h
#define YTClientSamplerGate_h
@import Foundation;

#include "YTServiceRegistryScope-Protocol.h"

@class NSObject;

@interface YTClientSamplerGate : NSObject {
    /* instance variables */
    id <YTServiceRegistryScope> _serviceRegistryScope;
    _Bool _allowSample;
}

/* class methods */
+ (id)queue;

/* instance methods */
- (id)initWithServiceRegistryScope:(id)scope fractionOfRunsToSample:(float)sample sampleCounterKey:(id)key;
- (id)init;
- (_Bool)allowSample;
- (_Bool)checkIfShouldSampleWithFractionOfRunToSample:(float)sample sampleCounterKey:(id)key;
- (float)getSampleCounterValueForKey:(id)key;
- (void)setSampleCounterValue:(float)value forKey:(id)key;

@end

#endif /* YTClientSamplerGate_h */
