  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTCreationStickerSnapshot_h
#define YTCreationStickerSnapshot_h
@import Foundation;

#include "YTCreationStickerSnapshotModel.h"

@class NSObject, NSString, NSURL;

@interface YTCreationStickerSnapshot : NSObject {
    /* instance variables */
    NSString *_posLayerID_10;
    long long _zIndex_6;
    double _alpha_5;
    YTCreationStickerSnapshotModel *_model_5;
    NSURL *_imageURL_8;
    struct CGPoint { double x; double y; } _center_6;
    struct CGPoint { double x; double y; } _anchorPoint_11;
    struct CGSize { double width; double height; } _containerViewSize_17;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _bounds_6;
    struct CGAffineTransform { double a; double b; double c; double d; double tx; double ty; } _transform_9;
    struct { struct { long long value; int timescale; unsigned int flags; long long epoch; } start; struct { long long value; int timescale; unsigned int flags; long long epoch; } duration; } _timeRange_9;
}

@property (readonly, copy, nonatomic) NSString *posLayerID;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } bounds;
@property (readonly, nonatomic) struct CGPoint { double x0; double x1; } center;
@property (readonly, nonatomic) long long zIndex;
@property (readonly, nonatomic) double alpha;
@property (readonly, nonatomic) struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; } transform;
@property (readonly, nonatomic) struct CGPoint { double x0; double x1; } anchorPoint;
@property (readonly, copy, nonatomic) YTCreationStickerSnapshotModel *model;
@property (readonly, nonatomic) NSURL *imageURL;
@property (readonly, nonatomic) struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; } timeRange;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } containerViewSize;

/* instance methods */
- (id)initWithPosLayerID:(id)id bounds:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bounds center:(struct CGPoint { double x0; double x1; })center zIndex:(long long)index alpha:(double)alpha transform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })transform anchorPoint:(struct CGPoint { double x0; double x1; })point model:(id)model imageURL:(id)url timeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })range containerViewSize:(struct CGSize { double x0; double x1; })size;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;

@end

#endif /* YTCreationStickerSnapshot_h */
