  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTCreationEditorEffectsPickerFeatureController_h
#define YTCreationEditorEffectsPickerFeatureController_h
@import Foundation;

#include "YTCreationAboveEngagementPanelView.h"
#include "YTCreationAssetController-Protocol.h"
#include "YTCreationCommonEditorView.h"
#include "YTCreationControlInputFeatureController.h"
#include "YTCreationControlInputFeatureControllerDelegate-Protocol.h"
#include "YTCreationEditorEffectsPickerFeatureControllerDelegate-Protocol.h"
#include "YTCreationEffectsManager.h"
#include "YTCreationEffectsManagerObserver-Protocol.h"
#include "YTCreationEngagementPanelController-Protocol.h"
#include "YTCreationEngagementPanelControllerDelegate-Protocol.h"
#include "YTCreationToolbelt-Protocol.h"
#include "YTCreationToolbeltButtonModel.h"
#include "YTEntityStoreObserver-Protocol.h"
#include "YTResponder-Protocol.h"
#include "YTShortsCreationResponseParser-Protocol.h"
#include "YTShortsEditorGesturesController.h"

@class NSObject, NSString, UIView, UIViewController;

@interface YTCreationEditorEffectsPickerFeatureController : NSObject <YTCreationControlInputFeatureControllerDelegate, YTCreationEffectsManagerObserver, YTCreationEngagementPanelControllerDelegate, YTEntityStoreObserver, YTResponder> {
    /* instance variables */
    YTCreationCommonEditorView *_commonEditorView;
    YTCreationEffectsManager *_effectsManager;
    id <YTShortsCreationResponseParser> _effectsParser;
    YTCreationAboveEngagementPanelView *_aboveEngagementPanelView;
    YTShortsEditorGesturesController *_gesturesController;
    UIViewController<YTCreationToolbelt> *_toolbeltViewController;
    UIView *_transformView;
    _Bool _effectsParserLoaded;
    UIView *_stickerView;
    double _cornerRadiusWhenEPExpanded;
    YTCreationToolbeltButtonModel *_effectPickerEntryModel;
    _Bool _isEffectPickerEffectSelected;
    id <YTCreationAssetController> _assetController;
    _Bool _isLoadingEffectPickerEffect;
}

@property (weak, nonatomic) id <YTCreationEditorEffectsPickerFeatureControllerDelegate> delegate;
@property (readonly, nonatomic) id <YTCreationEngagementPanelController> engagementPanelController;
@property (readonly, nonatomic) YTCreationControlInputFeatureController *controlInputFeatureController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, weak, nonatomic) id <YTResponder> parentResponder;

/* instance methods */
- (id)initWithParentResponder:(id)responder commonEditorView:(id)view effectsManager:(id)manager effectsParser:(id)parser gesturesController:(id)controller stickerView:(id)view toolbeltViewController:(id)controller transformView:(id)view cornerRadiusWhenEPExpanded:(double)epexpanded assetController:(id)controller;
- (id)init;
- (void)loadEffects;
- (void)handleEffectsParserLoaded:(id)loaded;
- (void)setUpEffectPickerEntryWithButtonModel:(id)model;
- (void)showEngagementPanelWithCommand:(id)command;
- (void)controlInputFeatureControllerDidUpdateControlView:(id)view;
- (void)effectsManagerDidDeselectAllEffects:(id)effects;
- (void)effectsManagerDidFailToLoadEffects:(id)effects;
- (void)effectsManagerDidLoadEffects:(id)effects;
- (void)effectsManager:(id)manager didSelectEffectsWithEffectIDs:(id)ids;
- (void)effectsManager:(id)manager didDeselectEffectsWithEffectIDs:(id)ids;
- (void)effectsManager:(id)manager didDownloadEffectWithID:(id)id;
- (void)engagementPanelControllerWillShowPanel:(id)panel;
- (void)engagementPanelControllerWillHidePanel:(id)panel;
- (void)engagementPanelControllerDidHidePanel:(id)panel;
- (void)didUpdateKey:(id)key inEntityStore:(id)store withUpdateType:(unsigned long long)type previousEntity:(id)entity entity:(id)entity;

@end

#endif /* YTCreationEditorEffectsPickerFeatureController_h */
