  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTCreationToolbeltButtonNewnessController_h
#define YTCreationToolbeltButtonNewnessController_h
@import Foundation;

#include "YTUserDefaults.h"

@class NSObject, NSString;

@interface YTCreationToolbeltButtonNewnessController : NSObject {
    /* instance variables */
    NSString *_toolbeltIdentifier;
    YTUserDefaults *_userDefaults;
}

/* instance methods */
- (id)initWithToolbeltIdentifier:(id)identifier;
- (void)setNewness:(id)newness withFeatureIdentifier:(id)identifier;
- (id)newnessWithFeatureIdentifier:(id)identifier;

@end

#endif /* YTCreationToolbeltButtonNewnessController_h */
