//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTCreationTapToDismissEngagementPanelViewController_h
#define YTCreationTapToDismissEngagementPanelViewController_h
@import Foundation;

#include "YTCreationTapToDismissEngagementPanelView.h"
#include "YTCreationTapToDismissEngagementPanelViewControllerDelegate-Protocol.h"

@class UIViewController;

@interface YTCreationTapToDismissEngagementPanelViewController : UIViewController

@property (retain, nonatomic) YTCreationTapToDismissEngagementPanelView *view;
@property (weak, nonatomic) id <YTCreationTapToDismissEngagementPanelViewControllerDelegate> delegate;

/* instance methods */
- (void)loadView;
- (void)didTapBackground;

@end

#endif /* YTCreationTapToDismissEngagementPanelViewController_h */
