//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTCreationEffectControlsViewController_h
#define YTCreationEffectControlsViewController_h
@import Foundation;

#include "YTCreationAssetController-Protocol.h"
#include "YTCreationEffectControlsViewControllerDelegate-Protocol.h"
#include "YTCreationEffectMediaPicker-Protocol.h"
#include "YTCreationEffectsManager.h"
#include "YTInMemoryEntityStore-Protocol.h"
#include "YTResponder-Protocol.h"

@class NSString, UIView, UIViewController;

@interface YTCreationEffectControlsViewController : UIViewController <YTResponder> {
    /* instance variables */
    id <YTCreationAssetController> _assetController;
    id <YTCreationEffectMediaPicker> _mediaPicker;
    YTCreationEffectsManager *_effectsManager;
    id <YTInMemoryEntityStore> _inMemoryStore;
    UIView *_placeholderView;
    _Bool _isControlInputRefactorEnabled;
}

@property (weak, nonatomic) id <YTCreationEffectControlsViewControllerDelegate> delegate;
@property (readonly, nonatomic) UIView *effectPanelEffectControlsView;
@property (readonly, nonatomic) UIView *inCameraEffectControlsView;
@property (readonly, weak, nonatomic) id <YTResponder> parentResponder;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithParentResponder:(id)responder assetController:(id)controller effectsManager:(id)manager;
- (void)setMediaPicker:(id)picker;
- (void)renderEffectUIWithActiveEffects:(id)effects entityKey:(id)key;
- (void)renderEffectUIWithRenderer:(id)renderer;
- (void)updateControlViewFromEntity:(id)entity;
- (void)updateControlViewFromEffectUIRenderer:(id)uirenderer;
- (void)handleAssetResult:(id)result error:(id)error;
- (void)initControlInputViewsForRenderer:(id)renderer;
- (id)elementsViewForRenderer:(id)renderer;
- (void)clearEffectControls;

@end

#endif /* YTCreationEffectControlsViewController_h */
