  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTCreationOverlayButtonColorStyle_Protocol_h
#define YTCreationOverlayButtonColorStyle_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSMutableDictionary, NSShadow;

@protocol YTCreationOverlayButtonColorStyle <NSObject>

@required

@property (retain, nonatomic) NSMutableDictionary *tintColorMap;
@property (retain, nonatomic) NSMutableDictionary *titleColorMap;
@property (retain, nonatomic) NSMutableDictionary *backgroundColorMap;
@property (retain, nonatomic) NSMutableDictionary *inkColorMap;
@property (retain, nonatomic) NSMutableDictionary *titleShadowColorMap;
@property (retain, nonatomic) NSShadow *buttonShadow;
@property (readonly, nonatomic) _Bool hasButtonShadow;

@optional

@end

#endif /* YTCreationOverlayButtonColorStyle_Protocol_h */
