//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTCreationSlipViewController_h
#define YTCreationSlipViewController_h
@import Foundation;

#include "YTCreationInlinePanelDelegate-Protocol.h"
#include "YTCreationSlipViewDelegate-Protocol.h"

@class UIViewController, googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift;

@interface YTCreationSlipViewController : UIViewController <YTCreationInlinePanelDelegate, YTCreationSlipViewDelegate> { // (Swift)
    /* instance variables */
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift timelineStateController;
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift segmentID;
    googlemac_iPhone_Shared_Identity_AccountSettings_Services_Snackbar_Impl_Impl_ImplLib/Impl_Factory+SRL.swift $__lazy_storage_$_slipPanGestureRecognizer;
}

@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } slipEditWindow;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } slipEditFilmstripFrame;

/* instance methods */
- (void)inlinePanelDidTapDoneButton:(id)button;
- (id)initWithTimelineStateController:(id)controller;
- (id)initWithCoder:(id)coder;
- (void)loadView;
- (void)viewDidLoad;
- (void)enableSlipWithSegmentID:(id)id slipEditWindow:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })window slipEditFilmstripFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)disableSlip;
- (void)handleSlipPan:(id)pan;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* YTCreationSlipViewController_h */
