//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTEditStickerView_h
#define YTEditStickerView_h
@import Foundation;

#include "TOKOverlayGestureManagerManagedView-Protocol.h"
#include "YTEditHitTestValidator-Protocol.h"

@class NSString, UIView;

@interface YTEditStickerView : UIView <TOKOverlayGestureManagerManagedView> {
    /* instance variables */
    struct UIEdgeInsets { double top; double left; double bottom; double right; } _hittableInsets;
    double _hittableInsetsRotation;
}

@property (retain, nonatomic) id <YTEditHitTestValidator> hitTestValidator;
@property (retain, nonatomic) id <YTEditHitTestValidator> noBlurHitTestValidator;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (double)yt_blurRadius;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (_Bool)pointInside:(struct CGPoint { double x0; double x1; })inside withEvent:(id)event;
- (id)currentImage;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })overlayGestureManagerCollisionRectForPosition:(struct CGPoint { double x0; double x1; })position transform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })transform;
- (void)overlayGestureManagerDidEnd:(id)end withGestureRecognizer:(id)recognizer;
- (_Bool)overlayGestureManagerShouldBeginTransformingView:(id)view;
- (void)overlayGestureManagerWillBegin:(id)begin withGestureRecognizer:(id)recognizer;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getIntersectionRectWithPoint:(struct CGPoint { double x0; double x1; })point;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })hittableInsetsForRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect targetTransform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })transform targetCenter:(struct CGPoint { double x0; double x1; })center;

@end

#endif /* YTEditStickerView_h */
