  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTEditVideoFrameSource_h
#define YTEditVideoFrameSource_h
@import Foundation;

#include "AVPlayerItemOutputPullDelegate-Protocol.h"
#include "OS_dispatch_queue-Protocol.h"
#include "YTEditVideoFrameSourceDelegate-Protocol.h"

@class AVPlayerItem, AVPlayerItemVideoOutput, CADisplayLink, NSDictionary, NSObject, NSString;

@interface YTEditVideoFrameSource : NSObject <AVPlayerItemOutputPullDelegate> {
    /* instance variables */
    AVPlayerItemVideoOutput *_videoOutput;
    CADisplayLink *_videoDisplayLink;
    NSObject<OS_dispatch_queue> *_videoQueue;
    _Bool _isVideoFrameSourceV2Enabled;
    NSDictionary *_videoOutputSettings;
}

@property (weak, nonatomic) id <YTEditVideoFrameSourceDelegate> delegate;
@property (retain, nonatomic) AVPlayerItem *playerItem;
@property (nonatomic) struct CGSize { double x0; double x1; } outputSize;
@property (nonatomic) _Bool paused;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithMaximumFPS:(long long)fps pixelFormat:(unsigned int)format;
- (id)initWithMaximumFPS:(long long)fps videoOutputSettings:(id)settings;
- (void)dealloc;
- (void)shutdown;
- (void)setupVideoOutput;
- (void)requestFrameForCurrentTime;
- (void)resetVideoOutput;
- (_Bool)isPaused;
- (_Bool)hasFrameForTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (void)attachVideoOutput;
- (void)removeVideoOutput;
- (void)outputMediaDataWillChange:(id)change;
- (void)videoUpdate:(id)update;
- (void)displayLinkCallBack:(id)back;
- (void)getFrameForTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;

@end

#endif /* YTEditVideoFrameSource_h */
