  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTEditStickerHeaderView_h
#define YTEditStickerHeaderView_h
@import Foundation;

#include "YTFormattedStringLabel.h"
#include "YTIFormattedString.h"

@class UICollectionReusableView;

@interface YTEditStickerHeaderView : UICollectionReusableView {
    /* instance variables */
    YTFormattedStringLabel *_titleLabel;
}

@property (retain, nonatomic) YTIFormattedString *titleFormattedString;

/* class methods */
+ (double)preferredHeightForTitle:(id)title width:(double)width;

/* instance methods */
- (void)layoutSubviews;
- (void)prepareForReuse;

@end

#endif /* YTEditStickerHeaderView_h */
