  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTFadingHeaderCollectionViewFlowLayout_h
#define YTFadingHeaderCollectionViewFlowLayout_h
@import Foundation;

#include "YTSeparatorCollectionViewFlowLayout.h"

@class NSIndexPath, NSMutableDictionary, UICollectionViewLayoutAttributes;

@interface YTFadingHeaderCollectionViewFlowLayout : YTSeparatorCollectionViewFlowLayout {
    /* instance variables */
    NSIndexPath *_fadingHeaderIndexPath;
    long long _fadingHeaderPushySection;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _originalHeaderFrame;
    UICollectionViewLayoutAttributes *_cachedFadingHeaderAttributes;
    NSMutableDictionary *_cachedSeparatorAttributes;
    _Bool _disableSlideInFromAboveUntilScrollOutsideTransition;
}

@property (nonatomic) double fadeExpandStartDistance;
@property (nonatomic) _Bool shouldEnableSlideInFromAboveLayoutStyle;
@property (nonatomic) _Bool shouldShowProminentChips;

/* instance methods */
- (id)init;
- (void)disableSlideInFromAboveUntilScrollOutsideTransition;
- (void)prepareLayout;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })change;
- (id)layoutAttributesForDecorationViewOfKind:(id)kind atIndexPath:(id)path;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)kind atIndexPath:(id)path;
- (id)layoutAttributesForItemAtIndexPath:(id)path;
- (id)layoutAttributesForElementsInRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)path;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)path;
- (id)initialLayoutAttributesForAppearingSupplementaryElementOfKind:(id)kind atIndexPath:(id)path;
- (id)finalLayoutAttributesForDisappearingSupplementaryElementOfKind:(id)kind atIndexPath:(id)path;
- (struct CGPoint { double x0; double x1; })targetContentOffsetForProposedContentOffset:(struct CGPoint { double x0; double x1; })offset withScrollingVelocity:(struct CGPoint { double x0; double x1; })velocity;
- (void)scrollViewDidEndDecelerating;
- (void)scrollViewDidEndDragging;
- (id)adjustFadingHeaderAttributes:(id)attributes;
- (id)adjustOtherElementsAttributes:(id)attributes;
- (void)adjustPanGestureTranslationIfNeededOnBoundsChange:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })change;
- (void)invalidateStickyHeaderLayoutIfNeededForBoundsChange:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })change;
- (void)invalidateOtherElementsLayoutIfNeededForBoundsChange:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })change separatorsOnly:(_Bool)only;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })adjustBoundsWithVerticalLookAhead:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })ahead;
- (_Bool)isFadingHeaderAttributes:(id)attributes;
- (_Bool)isSeparatorAttributes:(id)attributes;
- (id)fadingHeaderIndexPath;
- (long long)fadingHeaderPushySection;
- (double)verticalOffsetForSection:(unsigned long long)section;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frameForFirstFadingSectionHeaderBeforeSection:(unsigned long long)section;

@end

#endif /* YTFadingHeaderCollectionViewFlowLayout_h */
