//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTFineScrubberFilmstripViewSeekDelegate_Protocol_h
#define YTFineScrubberFilmstripViewSeekDelegate_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol YTFineScrubberFilmstripViewSeekDelegate <NSObject>

@required

/* required instance methods */
- (void)fineScrubberFilmstripLogSeekActionWithClientData:(id)data;
- (void)fineScrubberDidStartSeeking;
- (void)fineScrubberDidSeekToTime:(double)time;
- (void)fineScrubberDidEndSeekingWithSeekSource:(int)source;

@optional

@end

#endif /* YTFineScrubberFilmstripViewSeekDelegate_Protocol_h */
