  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTGetSearchSuggestionsServiceImpl_h
#define YTGetSearchSuggestionsServiceImpl_h
@import Foundation;

#include "YTAccountScopedBaseInnerTubeRequestService.h"
#include "YTGetSearchSuggestionsService-Protocol.h"
#include "YTInnerTubeResponseParser.h"

@class NSString;

@interface YTGetSearchSuggestionsServiceImpl : YTAccountScopedBaseInnerTubeRequestService <YTGetSearchSuggestionsService> {
    /* instance variables */
    YTInnerTubeResponseParser *_suggestionParser;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithAccountID:(id)id;
- (void)makeSuggestRequest:(id)request responseBlock:(id /* block */)block errorBlock:(id /* block */)block;

@end

#endif /* YTGetSearchSuggestionsServiceImpl_h */
