//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIActiveViewTrackingPings_h
#define YTIActiveViewTrackingPings_h
@import Foundation;

#include "GPBMessage.h"

@class NSMutableArray, NSString;

@interface YTIActiveViewTrackingPings : GPBMessage

@property (retain, nonatomic) NSMutableArray *activeViewViewablePingsArray;
@property (readonly, nonatomic) unsigned long long activeViewViewablePingsArray_Count;
@property (retain, nonatomic) NSMutableArray *activeViewMeasurablePingsArray;
@property (readonly, nonatomic) unsigned long long activeViewMeasurablePingsArray_Count;
@property (retain, nonatomic) NSMutableArray *activeViewFullyViewableAudibleHalfDurationPingsArray;
@property (readonly, nonatomic) unsigned long long activeViewFullyViewableAudibleHalfDurationPingsArray_Count;
@property (retain, nonatomic) NSMutableArray *activeViewEndOfSessionPingsArray;
@property (readonly, nonatomic) unsigned long long activeViewEndOfSessionPingsArray_Count;
@property (retain, nonatomic) NSMutableArray *activeViewAudioAudiblePingsArray;
@property (readonly, nonatomic) unsigned long long activeViewAudioAudiblePingsArray_Count;
@property (retain, nonatomic) NSMutableArray *activeViewAudioMeasurablePingsArray;
@property (readonly, nonatomic) unsigned long long activeViewAudioMeasurablePingsArray_Count;
@property (nonatomic) int trafficType;
@property (nonatomic) _Bool hasTrafficType;
@property (copy, nonatomic) NSString *identifier;
@property (nonatomic) _Bool hasIdentifier;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIActiveViewTrackingPings_h */
