  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIBrowseFeedActionsSupportedRenderers_h
#define YTIBrowseFeedActionsSupportedRenderers_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIButtonRenderer.h"
#include "YTICompactLinkRenderer.h"
#include "YTIEomSettingsDisclaimerRenderer.h"
#include "YTISearchBoxRenderer.h"
#include "YTIToggleButtonRenderer.h"

@interface YTIBrowseFeedActionsSupportedRenderers : GPBMessage

@property (readonly, nonatomic) int actionsOneOfCase;
@property (retain, nonatomic) YTIButtonRenderer *buttonRenderer;
@property (nonatomic) _Bool hasButtonRenderer;
@property (retain, nonatomic) YTIToggleButtonRenderer *toggleButtonRenderer;
@property (nonatomic) _Bool hasToggleButtonRenderer;
@property (retain, nonatomic) YTISearchBoxRenderer *searchBoxRenderer;
@property (nonatomic) _Bool hasSearchBoxRenderer;
@property (retain, nonatomic) YTICompactLinkRenderer *compactLinkRenderer;
@property (nonatomic) _Bool hasCompactLinkRenderer;
@property (retain, nonatomic) YTIEomSettingsDisclaimerRenderer *eomSettingsDisclaimerRenderer;
@property (nonatomic) _Bool hasEomSettingsDisclaimerRenderer;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIBrowseFeedActionsSupportedRenderers_h */
