  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIBrowseContinuationSourceBlockImpl_Protocol_h
#define YTIBrowseContinuationSourceBlockImpl_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol YTIBrowseContinuationSourceBlockImpl <NSObject>

@required

/* required instance methods */
- (id)setContinuations:(id)continuations error:(id *)error;
- (id)canReload:(id)reload error:(id *)error;
- (id)canGetNext:(id)next error:(id *)error;
- (id)canGetPrevious:(id)previous error:(id *)error;
- (void)reload:(id)reload callback:(id /* block */)callback;
- (void)getNext:(id)next callback:(id /* block */)callback;
- (void)getPrevious:(id)previous callback:(id /* block */)callback;
- (id)refreshInteractionLogger:(id)logger error:(id *)error;

@optional

@end

#endif /* YTIBrowseContinuationSourceBlockImpl_Protocol_h */
