  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTICommentModerationButtonsSupportedRenderers_h
#define YTICommentModerationButtonsSupportedRenderers_h
@import Foundation;

#include "GPBMessage.h"
#include "YTICommentModerationButtonsRenderer.h"

@interface YTICommentModerationButtonsSupportedRenderers : GPBMessage

@property (retain, nonatomic) YTICommentModerationButtonsRenderer *commentModerationButtonsRenderer;
@property (nonatomic) _Bool hasCommentModerationButtonsRenderer;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTICommentModerationButtonsSupportedRenderers_h */
