  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIClientSideUpdateProperties_h
#define YTIClientSideUpdateProperties_h
@import Foundation;

#include "GPBMessage.h"

@class NSString;

@interface YTIClientSideUpdateProperties : GPBMessage

@property (copy, nonatomic) NSString *gameTitleKey;
@property (nonatomic) _Bool hasGameTitleKey;
@property (copy, nonatomic) NSString *liveConferenceStateKey;
@property (nonatomic) _Bool hasLiveConferenceStateKey;
@property (copy, nonatomic) NSString *orientationStateKey;
@property (nonatomic) _Bool hasOrientationStateKey;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIClientSideUpdateProperties_h */
