  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIChannelSettingsEditorRenderer_h
#define YTIChannelSettingsEditorRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIButtonSupportedRenderers.h"
#include "YTIChannelSettingsEditorBooleanFormFieldSupportedRenderers.h"
#include "YTIFormattedString.h"

@class NSMutableArray;

@interface YTIChannelSettingsEditorRenderer : GPBMessage

@property (retain, nonatomic) YTIFormattedString *title;
@property (nonatomic) _Bool hasTitle;
@property (retain, nonatomic) YTIFormattedString *privacySettingsTitle;
@property (nonatomic) _Bool hasPrivacySettingsTitle;
@property (retain, nonatomic) NSMutableArray *privacySettingsArray;
@property (readonly, nonatomic) unsigned long long privacySettingsArray_Count;
@property (retain, nonatomic) YTIFormattedString *accountSettingsText;
@property (nonatomic) _Bool hasAccountSettingsText;
@property (retain, nonatomic) YTIChannelSettingsEditorBooleanFormFieldSupportedRenderers *layoutSetting;
@property (nonatomic) _Bool hasLayoutSetting;
@property (retain, nonatomic) YTIFormattedString *advancedSettingsText;
@property (nonatomic) _Bool hasAdvancedSettingsText;
@property (retain, nonatomic) YTIChannelSettingsEditorBooleanFormFieldSupportedRenderers *discussionTabSetting;
@property (nonatomic) _Bool hasDiscussionTabSetting;
@property (retain, nonatomic) YTIFormattedString *translateInfoTitle;
@property (nonatomic) _Bool hasTranslateInfoTitle;
@property (retain, nonatomic) YTIFormattedString *translateInfoBody;
@property (nonatomic) _Bool hasTranslateInfoBody;
@property (retain, nonatomic) YTIButtonSupportedRenderers *saveButton;
@property (nonatomic) _Bool hasSaveButton;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIChannelSettingsEditorRenderer_h */
