  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTICompanionAdRenderer_h
#define YTICompanionAdRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTICommand.h"
#include "YTICompanionAdCallToActionSupportedRenderers.h"
#include "YTIFormattedString.h"
#include "YTIMenuSupportedRenderers.h"
#include "YTIRenderer.h"
#include "YTIThumbnailDetails.h"

@class NSData, NSMutableArray;

@interface YTICompanionAdRenderer : GPBMessage

@property (nonatomic) _Bool hack;
@property (nonatomic) _Bool hasHack;
@property (retain, nonatomic) YTIFormattedString *title;
@property (nonatomic) _Bool hasTitle;
@property (retain, nonatomic) YTIRenderer *titleClickCommand;
@property (nonatomic) _Bool hasTitleClickCommand;
@property (retain, nonatomic) YTIFormattedString *descriptionText;
@property (nonatomic) _Bool hasDescriptionText;
@property (retain, nonatomic) YTIRenderer *descriptionClickCommand;
@property (nonatomic) _Bool hasDescriptionClickCommand;
@property (retain, nonatomic) YTIThumbnailDetails *thumbnail;
@property (nonatomic) _Bool hasThumbnail;
@property (retain, nonatomic) YTIRenderer *iconClickCommand;
@property (nonatomic) _Bool hasIconClickCommand;
@property (retain, nonatomic) YTICommand *navigationEndpoint;
@property (nonatomic) _Bool hasNavigationEndpoint;
@property (nonatomic) _Bool autohide;
@property (nonatomic) _Bool hasAutohide;
@property (retain, nonatomic) YTIMenuSupportedRenderers *menu;
@property (nonatomic) _Bool hasMenu;
@property (retain, nonatomic) YTICompanionAdCallToActionSupportedRenderers *callToAction;
@property (nonatomic) _Bool hasCallToAction;
@property (retain, nonatomic) YTIRenderer *secondaryButton;
@property (nonatomic) _Bool hasSecondaryButton;
@property (nonatomic) _Bool useRoundThumbnail;
@property (nonatomic) _Bool hasUseRoundThumbnail;
@property (retain, nonatomic) NSMutableArray *impressionCommandsArray;
@property (readonly, nonatomic) unsigned long long impressionCommandsArray_Count;
@property (retain, nonatomic) YTICommand *adCompleteCommand;
@property (nonatomic) _Bool hasAdCompleteCommand;
@property (retain, nonatomic) YTIRenderer *companionExtension;
@property (nonatomic) _Bool hasCompanionExtension;
@property (nonatomic) int completionAction;
@property (nonatomic) _Bool hasCompletionAction;
@property (nonatomic) unsigned int backgroundColor;
@property (nonatomic) _Bool hasBackgroundColor;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTICompanionAdRenderer_h */
