@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIdentityTransaction_h
#define YTIdentityTransaction_h
@import Foundation;

#include "YTIdentityState.h"
#include "YTIdentityTransactionCommitter-Protocol.h"

@class NSObject;

@interface YTIdentityTransaction : NSObject {
    /* instance variables */
    id <YTIdentityTransactionCommitter> _committer;
}

@property (retain, nonatomic) YTIdentityState *oldIdentity;
@property (retain, nonatomic) YTIdentityState *futureIdentity;
@property (nonatomic) unsigned long long identityChangeType;

/* instance methods */
- (id)initWithIdentityTransactionCommitter:(id)committer;
- (void)commit;

@end

#endif /* YTIdentityTransaction_h */
