  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIDeviceContext_h
#define YTIDeviceContext_h
@import Foundation;

#include "GPBMessage.h"

@interface YTIDeviceContext : GPBMessage

@property (nonatomic) _Bool wifiConnected;
@property (nonatomic) _Bool hasWifiConnected;
@property (nonatomic) unsigned int wifiId;
@property (nonatomic) _Bool hasWifiId;
@property (nonatomic) _Bool screenActive;
@property (nonatomic) _Bool hasScreenActive;
@property (nonatomic) _Bool setByClient;
@property (nonatomic) _Bool hasSetByClient;
@property (nonatomic) _Bool isBrowseBackgroundFetchEnabled;
@property (nonatomic) _Bool hasIsBrowseBackgroundFetchEnabled;
@property (nonatomic) int appLastOpenedTimeBucket;
@property (nonatomic) _Bool hasAppLastOpenedTimeBucket;
@property (nonatomic) int appLastOpenedMaxHours;
@property (nonatomic) _Bool hasAppLastOpenedMaxHours;
@property (nonatomic) _Bool deviceCharging;
@property (nonatomic) _Bool hasDeviceCharging;
@property (nonatomic) _Bool powerSaveMode;
@property (nonatomic) _Bool hasPowerSaveMode;
@property (nonatomic) int currentBatteryPercent;
@property (nonatomic) _Bool hasCurrentBatteryPercent;
@property (nonatomic) long long taskScheduledTimeMillis;
@property (nonatomic) _Bool hasTaskScheduledTimeMillis;
@property (nonatomic) long long clientCurrentTimeMillis;
@property (nonatomic) _Bool hasClientCurrentTimeMillis;
@property (nonatomic) int notificationsSetting;
@property (nonatomic) _Bool hasNotificationsSetting;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIDeviceContext_h */
