  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIEndpoint_h
#define YTIEndpoint_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIEndpoint_Downloads.h"
#include "YTIEndpoint_Home.h"
#include "YTIEndpoint_KidsParentZone.h"
#include "YTIEndpoint_ShortsCreation.h"

@interface YTIEndpoint : GPBMessage

@property (readonly, nonatomic) int pageOneOfCase;
@property (retain, nonatomic) YTIEndpoint_KidsParentZone *kidsParentZone;
@property (nonatomic) _Bool hasKidsParentZone;
@property (retain, nonatomic) YTIEndpoint_Home *home;
@property (nonatomic) _Bool hasHome;
@property (retain, nonatomic) YTIEndpoint_Downloads *downloads;
@property (nonatomic) _Bool hasDownloads;
@property (retain, nonatomic) YTIEndpoint_ShortsCreation *shortsCreation;
@property (nonatomic) _Bool hasShortsCreation;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIEndpoint_h */
