//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIFlowThumbnailsRenderer_h
#define YTIFlowThumbnailsRenderer_h
@import Foundation;

#include "GPBMessage.h"

@class NSData, NSMutableArray;

@interface YTIFlowThumbnailsRenderer : GPBMessage

@property (retain, nonatomic) NSMutableArray *thumbnailsArray;
@property (readonly, nonatomic) unsigned long long thumbnailsArray_Count;
@property (retain, nonatomic) NSMutableArray *titlesArray;
@property (readonly, nonatomic) unsigned long long titlesArray_Count;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIFlowThumbnailsRenderer_h */
