  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIFeaturePlayerOverlayStateEntity_h
#define YTIFeaturePlayerOverlayStateEntity_h
@import Foundation;

#include "GPBMessage.h"

@class NSString;

@interface YTIFeaturePlayerOverlayStateEntity : GPBMessage

@property (copy, nonatomic) NSString *key;
@property (nonatomic) _Bool hasKey;
@property (nonatomic) _Bool isEndscreenOverlayVisible;
@property (nonatomic) _Bool hasIsEndscreenOverlayVisible;
@property (nonatomic) _Bool isRelatedVideosCarouselVisible;
@property (nonatomic) _Bool hasIsRelatedVideosCarouselVisible;
@property (nonatomic) _Bool isAutonavOverlayVisible;
@property (nonatomic) _Bool hasIsAutonavOverlayVisible;
@property (nonatomic) _Bool isFineScrubbingOverlayVisible;
@property (nonatomic) _Bool hasIsFineScrubbingOverlayVisible;
@property (nonatomic) _Bool shouldShowTrailerLabelOverlay;
@property (nonatomic) _Bool hasShouldShowTrailerLabelOverlay;

/* class methods */
+ (Class)entityClass;
+ (id)descriptor;

/* instance methods */
- (id)entityWithStore:(id)store;
- (id)entityWithStore:(id)store entityMetadata:(id)metadata;

@end

#endif /* YTIFeaturePlayerOverlayStateEntity_h */
