@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIGetLiveChatRequest_ClientMutableData_h
#define YTIGetLiveChatRequest_ClientMutableData_h
@import Foundation;

#include "GPBMessage.h"
#include "GPBUInt32UInt32Dictionary.h"

@interface YTIGetLiveChatRequest_ClientMutableData : GPBMessage

@property (retain, nonatomic) GPBUInt32UInt32Dictionary *legalDisclaimerCounts;
@property (readonly, nonatomic) unsigned long long legalDisclaimerCounts_Count;
@property (retain, nonatomic) GPBUInt32UInt32Dictionary *viewerSuggestionCounts;
@property (readonly, nonatomic) unsigned long long viewerSuggestionCounts_Count;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIGetLiveChatRequest_ClientMutableData_h */
