  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIHintButtonRenderer_h
#define YTIHintButtonRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTClickableButton-Protocol.h"
#include "YTIAccessibilitySupportedDatas.h"
#include "YTICommand.h"
#include "YTIFormattedString.h"
#include "YTIHintButtonStyle.h"
#include "YTIIcon.h"
#include "YTTooltipButtonModel-Protocol.h"

@class NSData, NSString;

@interface YTIHintButtonRenderer : GPBMessage <YTClickableButton, YTTooltipButtonModel>

@property (readonly, nonatomic) _Bool nonEmpty;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) YTIHintButtonStyle *style;
@property (nonatomic) _Bool hasStyle;
@property (nonatomic) _Bool isDisabled;
@property (nonatomic) _Bool hasIsDisabled;
@property (retain, nonatomic) YTIIcon *icon;
@property (nonatomic) _Bool hasIcon;
@property (retain, nonatomic) YTIFormattedString *text;
@property (nonatomic) _Bool hasText;
@property (retain, nonatomic) YTICommand *serviceEndpoint;
@property (nonatomic) _Bool hasServiceEndpoint;
@property (retain, nonatomic) YTICommand *navigationEndpoint;
@property (nonatomic) _Bool hasNavigationEndpoint;
@property (retain, nonatomic) YTIAccessibilitySupportedDatas *accessibility;
@property (nonatomic) _Bool hasAccessibility;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;

/* class methods */
+ (id)descriptor;

/* instance methods */
- (_Bool)hasAnyCommand;
- (void)sendAllClickEventsWithFirstResponder:(id)responder fromView:(id)view;
- (void)sendAllClickEventsWithFirstResponder:(id)responder fromView:(id)view entry:(id)entry;
- (void)sendAllClickEventsWithFirstResponder:(id)responder fromView:(id)view entry:(id)entry sendClick:(_Bool)click;
- (void)sendAllClickEventsWithFirstResponder:(id)responder fromView:(id)view entry:(id)entry sendClick:(_Bool)click displayTitle:(id)title;
- (_Bool)isNonEmpty;
- (void)loadOntoButton:(id)button;

@end

#endif /* YTIHintButtonRenderer_h */
