  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIHorizontalButtonListRenderer_h
#define YTIHorizontalButtonListRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIFormattedString.h"
#include "YTIHorizontalButtonListColorPalette.h"
#include "YTIIcon.h"

@class NSData, NSMutableArray;

@interface YTIHorizontalButtonListRenderer : GPBMessage

@property (retain, nonatomic) NSMutableArray *itemsArray;
@property (readonly, nonatomic) unsigned long long itemsArray_Count;
@property (retain, nonatomic) YTIHorizontalButtonListColorPalette *colorData;
@property (nonatomic) _Bool hasColorData;
@property (retain, nonatomic) YTIIcon *icon;
@property (nonatomic) _Bool hasIcon;
@property (retain, nonatomic) YTIFormattedString *title;
@property (nonatomic) _Bool hasTitle;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIHorizontalButtonListRenderer_h */
