  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIKidsExistingOnboardingConfig_h
#define YTIKidsExistingOnboardingConfig_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIKidsExistingOnboardingDisplayPeriod.h"

@interface YTIKidsExistingOnboardingConfig : GPBMessage

@property (retain, nonatomic) YTIKidsExistingOnboardingDisplayPeriod *firstPeriod;
@property (nonatomic) _Bool hasFirstPeriod;
@property (retain, nonatomic) YTIKidsExistingOnboardingDisplayPeriod *secondPeriod;
@property (nonatomic) _Bool hasSecondPeriod;
@property (retain, nonatomic) YTIKidsExistingOnboardingDisplayPeriod *thirdPeriod;
@property (nonatomic) _Bool hasThirdPeriod;
@property (nonatomic) _Bool enableCleanHistoryAndSearchOff;
@property (nonatomic) _Bool hasEnableCleanHistoryAndSearchOff;
@property (nonatomic) _Bool enableClearHistory;
@property (nonatomic) _Bool hasEnableClearHistory;
@property (nonatomic) _Bool enableSearchOff;
@property (nonatomic) _Bool hasEnableSearchOff;
@property (nonatomic) _Bool enableGlobalConfigRefreshOnStartup;
@property (nonatomic) _Bool hasEnableGlobalConfigRefreshOnStartup;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIKidsExistingOnboardingConfig_h */
