  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTILiveCreationPlayablesMetrics_h
#define YTILiveCreationPlayablesMetrics_h
@import Foundation;

#include "GPBMessage.h"
#include "YTILiveCreationContext.h"

@class NSMutableArray;

@interface YTILiveCreationPlayablesMetrics : GPBMessage

@property (retain, nonatomic) YTILiveCreationContext *liveCreationContext;
@property (nonatomic) _Bool hasLiveCreationContext;
@property (retain, nonatomic) NSMutableArray *miniAppInfoArray;
@property (readonly, nonatomic) unsigned long long miniAppInfoArray_Count;
@property (nonatomic) float avgCameraFps;
@property (nonatomic) _Bool hasAvgCameraFps;
@property (nonatomic) float avgPlayableCaptureInputFps;
@property (nonatomic) _Bool hasAvgPlayableCaptureInputFps;
@property (nonatomic) float avgMainCompositorFps;
@property (nonatomic) _Bool hasAvgMainCompositorFps;
@property (nonatomic) float avgPlayableCompositorOutputFps;
@property (nonatomic) _Bool hasAvgPlayableCompositorOutputFps;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTILiveCreationPlayablesMetrics_h */
