  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTILoggingHeartbeatConfig_h
#define YTILoggingHeartbeatConfig_h
@import Foundation;

#include "GPBMessage.h"

@interface YTILoggingHeartbeatConfig : GPBMessage

@property (nonatomic) _Bool enabled;
@property (nonatomic) _Bool hasEnabled;
@property (nonatomic) int foregroundCaptureIntervalSecs;
@property (nonatomic) _Bool hasForegroundCaptureIntervalSecs;
@property (nonatomic) int inactiveTimeoutSecs;
@property (nonatomic) _Bool hasInactiveTimeoutSecs;
@property (nonatomic) _Bool accountChangeHeartbeatEnabled;
@property (nonatomic) _Bool hasAccountChangeHeartbeatEnabled;
@property (nonatomic) _Bool sendDummyPayload;
@property (nonatomic) _Bool hasSendDummyPayload;
@property (nonatomic) int heartbeatPersistModulus;
@property (nonatomic) _Bool hasHeartbeatPersistModulus;
@property (nonatomic) _Bool logHeartbeatCdn;
@property (nonatomic) _Bool hasLogHeartbeatCdn;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTILoggingHeartbeatConfig_h */
