@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIMdxNotificationTriggerCondition_h
#define YTIMdxNotificationTriggerCondition_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIMdxNotificationTriggerCondition_QuietPeriodByNotificationCondition.h"
#include "YTIMdxNotificationTriggerCondition_Range.h"

@class NSMutableArray;

@interface YTIMdxNotificationTriggerCondition : GPBMessage

@property (retain, nonatomic) NSMutableArray *mdxConnectionCountsArray;
@property (readonly, nonatomic) unsigned long long mdxConnectionCountsArray_Count;
@property (retain, nonatomic) NSMutableArray *castAvailableSessionCountsArray;
@property (readonly, nonatomic) unsigned long long castAvailableSessionCountsArray_Count;
@property (nonatomic) int requiredPage;
@property (nonatomic) _Bool hasRequiredPage;
@property (retain, nonatomic) YTIMdxNotificationTriggerCondition_Range *currentVideoDuration;
@property (nonatomic) _Bool hasCurrentVideoDuration;
@property (nonatomic) _Bool requireFullScreen;
@property (nonatomic) _Bool hasRequireFullScreen;
@property (nonatomic) _Bool requireHd;
@property (nonatomic) _Bool hasRequireHd;
@property (nonatomic) _Bool requirePlaylistPlayback;
@property (nonatomic) _Bool hasRequirePlaylistPlayback;
@property (retain, nonatomic) YTIMdxNotificationTriggerCondition_Range *uncastedVideoCount;
@property (nonatomic) _Bool hasUncastedVideoCount;
@property (retain, nonatomic) YTIMdxNotificationTriggerCondition_QuietPeriodByNotificationCondition *quietPeriodByNotification;
@property (nonatomic) _Bool hasQuietPeriodByNotification;
@property (nonatomic) _Bool requireSd;
@property (nonatomic) _Bool hasRequireSd;
@property (retain, nonatomic) NSMutableArray *timeConditionsArray;
@property (readonly, nonatomic) unsigned long long timeConditionsArray_Count;
@property (retain, nonatomic) NSMutableArray *timeOfWeekConditionsArray;
@property (readonly, nonatomic) unsigned long long timeOfWeekConditionsArray_Count;
@property (retain, nonatomic) NSMutableArray *videoIdsArray;
@property (readonly, nonatomic) unsigned long long videoIdsArray_Count;
@property (retain, nonatomic) NSMutableArray *playlistIdsArray;
@property (readonly, nonatomic) unsigned long long playlistIdsArray_Count;
@property (retain, nonatomic) NSMutableArray *dependentNotificationsArray;
@property (readonly, nonatomic) unsigned long long dependentNotificationsArray_Count;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIMdxNotificationTriggerCondition_h */
