  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIMusicCollectionShelfRenderer_h
#define YTIMusicCollectionShelfRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIMusicEntityRef.h"
#include "YTIRenderer.h"

@interface YTIMusicCollectionShelfRenderer : GPBMessage

@property (retain, nonatomic) YTIMusicEntityRef *entityRef;
@property (nonatomic) _Bool hasEntityRef;
@property (nonatomic) long long maxItemsDisplayed;
@property (nonatomic) _Bool hasMaxItemsDisplayed;
@property (retain, nonatomic) YTIRenderer *shelfTemplateRenderer;
@property (nonatomic) _Bool hasShelfTemplateRenderer;
@property (retain, nonatomic) YTIRenderer *firstItemTemplateRenderer;
@property (nonatomic) _Bool hasFirstItemTemplateRenderer;
@property (retain, nonatomic) YTIRenderer *itemTemplateRenderer;
@property (nonatomic) _Bool hasItemTemplateRenderer;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIMusicCollectionShelfRenderer_h */
