  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIMusicThumbnailButtonRenderer_h
#define YTIMusicThumbnailButtonRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIAccessibilitySupportedDatas.h"
#include "YTICommand.h"
#include "YTIFormattedString.h"
#include "YTIIcon.h"
#include "YTILoggingDirectives.h"

@class NSData;

@interface YTIMusicThumbnailButtonRenderer : GPBMessage

@property (retain, nonatomic) YTIFormattedString *text;
@property (nonatomic) _Bool hasText;
@property (retain, nonatomic) YTIIcon *icon;
@property (nonatomic) _Bool hasIcon;
@property (retain, nonatomic) YTICommand *command;
@property (nonatomic) _Bool hasCommand;
@property (retain, nonatomic) YTIAccessibilitySupportedDatas *accessibilityData;
@property (nonatomic) _Bool hasAccessibilityData;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;
@property (retain, nonatomic) YTILoggingDirectives *loggingDirectives;
@property (nonatomic) _Bool hasLoggingDirectives;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIMusicThumbnailButtonRenderer_h */
