@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIMdxNotificationTriggerCondition_QuietPeriodByNotificationCondition_h
#define YTIMdxNotificationTriggerCondition_QuietPeriodByNotificationCondition_h
@import Foundation;

#include "GPBMessage.h"

@interface YTIMdxNotificationTriggerCondition_QuietPeriodByNotificationCondition : GPBMessage

@property (nonatomic) int notificationType;
@property (nonatomic) _Bool hasNotificationType;
@property (nonatomic) int quietPeriodSeconds;
@property (nonatomic) _Bool hasQuietPeriodSeconds;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIMdxNotificationTriggerCondition_QuietPeriodByNotificationCondition_h */
