  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTInlineMutedPlaybackPostVideoPlayerOverlayViewController_h
#define YTInlineMutedPlaybackPostVideoPlayerOverlayViewController_h
@import Foundation;

#include "MLNerdStatsPlaybackData.h"
#include "YTASDPlayableEntry-Protocol.h"
#include "YTEntityStore-Protocol.h"
#include "YTEntityStoreObserver-Protocol.h"
#include "YTInlineMutedPlaybackOverlayDelegate-Protocol.h"
#include "YTInlineMutedPlaybackPlayerOverlayViewController.h"
#include "YTInlineMutedPlaybackPostVideoPlayerOverlayView.h"
#include "YTInlineMutedPlaybackPostVideoScrubberViewController.h"
#include "YTInlineMutedPlaybackVideoPlaybackController.h"
#include "YTInlinePlaybackPlayerOverlayProtocol-Protocol.h"
#include "YTResponder-Protocol.h"
#include "YTVideoPlayerOverlayDelegate-Protocol.h"
#include "YTVideoPlayerOverlayProtocol-Protocol.h"

@class NSString;

@interface YTInlineMutedPlaybackPostVideoPlayerOverlayViewController : YTInlineMutedPlaybackPlayerOverlayViewController <YTInlinePlaybackPlayerOverlayProtocol, YTVideoPlayerOverlayProtocol, YTResponder, YTEntityStoreObserver> {
    /* instance variables */
    YTInlineMutedPlaybackPostVideoPlayerOverlayView *_postVideoPlayerOverlayView;
    id <YTInlineMutedPlaybackOverlayDelegate> _overlayDelegate;
    YTInlineMutedPlaybackVideoPlaybackController *_impVideoPlaybackController;
    id <YTEntityStore> _entityStore;
    NSString *_audioButtonsEntityKey;
    YTInlineMutedPlaybackPostVideoScrubberViewController *_scrubberViewController;
}

@property (retain, nonatomic) id <YTASDPlayableEntry> entry;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) int overlayType;
@property (weak, nonatomic) id <YTVideoPlayerOverlayDelegate> delegate;
@property (retain, nonatomic) MLNerdStatsPlaybackData *nerdStatsPlaybackData;
@property (nonatomic) _Bool externalPlaybackActive;
@property (nonatomic) _Bool MDXPlaybackActive;
@property (nonatomic) _Bool currentVideoVertical;
@property (nonatomic) _Bool playlistControlsHidden;
@property (nonatomic) _Bool hasPreviousVideo;
@property (nonatomic) _Bool hasNextVideo;
@property (nonatomic) _Bool userScrubbing;
@property (nonatomic) _Bool foregroundAudioOnly;
@property (nonatomic) _Bool shouldPreventPlayerRenderingViewModifications;
@property (nonatomic) int embargoState;
@property (readonly, weak, nonatomic) id <YTResponder> parentResponder;

/* instance methods */
- (id)initWithParentResponder:(id)responder delegate:(id)delegate playableEntry:(id)entry;
- (void)loadView;
- (void)playbackDidPause;
- (void)resetAndShowLoading:(_Bool)loading;
- (void)setPlayerResponse:(id)response CPN:(id)cpn;
- (void)setActiveSingleVideo:(id)video;
- (void)setControlButtonsWithPlayerData:(id)data;
- (void)addControlButtonsEntityStoreObserver:(id)observer;
- (void)removeControlButtonsEntityStoreObserver:(id)observer;
- (void)setUpGestureRecognizers;
- (void)didLongPress:(id)press;
- (void)maybeUpdateScrubberViewController;
- (void)didUpdateKey:(id)key inEntityStore:(id)store withUpdateType:(unsigned long long)type previousEntity:(id)entity entity:(id)entity;

@end

#endif /* YTInlineMutedPlaybackPostVideoPlayerOverlayViewController_h */
