  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTInfoCardDarkTeaserContainerView_h
#define YTInfoCardDarkTeaserContainerView_h
@import Foundation;

#include "UIGestureRecognizerDelegate-Protocol.h"
#include "YTInfoCardTeaserContainerViewDelegate-Protocol.h"
#include "YTInfoCardTeaserContainerViewProtocol-Protocol.h"
#include "YTInfoCardTeaserViewProtocol-Protocol.h"
#include "YTSimpleInfoCardTeaserViewProtocol-Protocol.h"

@class NSString, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface YTInfoCardDarkTeaserContainerView : UIView <UIGestureRecognizerDelegate, YTInfoCardTeaserViewProtocol, YTInfoCardTeaserContainerViewProtocol> {
    /* instance variables */
    double _subViewPanX;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

@property (readonly, nonatomic) UIView *contentContainerView;
@property (readonly, nonatomic) UIView *teaserBackgroundView;
@property (readonly, nonatomic) UIView *closeButtonContainerView;
@property (nonatomic) _Bool visible;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) _Bool disableTeasers;
@property (retain, nonatomic) UIView<YTSimpleInfoCardTeaserViewProtocol> *teaserView;
@property (weak, nonatomic) id <YTInfoCardTeaserContainerViewDelegate> delegate;

/* class methods */
+ (id)globalMotionCurve;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (double)additionalXOffset;
- (double)additionalYOffset;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (_Bool)pointInside:(struct CGPoint { double x0; double x1; })inside withEvent:(id)event;
- (void)addDidTapInfoCardIconTarget:(id)target action:(SEL)action;
- (void)removeDidTapInfoCardIconTarget:(id)target action:(SEL)action;
- (void)setIconVisible:(_Bool)visible;
- (void)showInfoCardTeaserAnimated:(_Bool)animated hideAfterDelay:(double)delay iconDelay:(double)delay;
- (void)hideAnimatedAfterDelay;
- (void)hideInfoCardTeaserAnimated:(_Bool)animated;
- (void)didPan:(id)pan;
- (void)panWithXDistance:(double)xdistance xVelocity:(double)velocity panFinished:(_Bool)finished;
- (void)didTap:(id)tap;
- (_Bool)isVisible;

@end

#endif /* YTInfoCardDarkTeaserContainerView_h */
