  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIntervalNode_h
#define YTIntervalNode_h
@import Foundation;

#include "YTInterval.h"

@class NSObject;

@interface YTIntervalNode : NSObject

@property (retain, nonatomic) YTInterval *value;
@property (nonatomic) long long priority;
@property (nonatomic) double maxStop;
@property (nonatomic) _Bool maxStopInclusive;
@property (retain, nonatomic) YTIntervalNode *left;
@property (retain, nonatomic) YTIntervalNode *right;

/* instance methods */
- (id)initWithInterval:(id)interval priority:(long long)priority;
- (id)initWithInterval:(id)interval;
- (void)enumerateIntervalsContainingPoint:(double)point withBlock:(id /* block */)block;
- (void)enumerateIntervalsOverlappingInterval:(id)interval withBlock:(id /* block */)block;
- (void)enumerateAllIntervalsWithBlock:(id /* block */)block;
- (void)enumerateIntervalsStartingBetweenStartTime:(double)time endTime:(double)time withBlock:(id /* block */)block;
- (void)addIntervalsContainingPoint:(double)point toSet:(id)set;
- (void)addIntervalsOverlappingInterval:(id)interval toSet:(id)set;
- (void)addIntervalsStartingBetweenStartTime:(double)time endTime:(double)time toSet:(id)set;
- (void)addAllIntervalsToSet:(id)set;
- (void)addNode:(id)node;
- (_Bool)removeNodeWithInterval:(id)interval fromNode:(id *)node;
- (id)remove;
- (id)nodeWithSmallestValue;
- (void)updateCachedValues;
- (long long)compareStopOfNode:(id)node;
- (void)rotateLeft;
- (void)rotateRight;
- (_Bool)isMaxStopInclusive;

@end

#endif /* YTIntervalNode_h */
