//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTInlinePlayerBarFineScrubberControlsViewObserver_Protocol_h
#define YTInlinePlayerBarFineScrubberControlsViewObserver_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol YTInlinePlayerBarFineScrubberControlsViewObserver <NSObject>

@required

/* required instance methods */
- (void)inlinePlayerBarFineScrubberControlsViewDidPressFineScrubberPlayButton;
- (void)inlinePlayerBarFineScrubberControlsViewDidPressFineScrubberScrimToPlay;

@optional

@end

#endif /* YTInlinePlayerBarFineScrubberControlsViewObserver_Protocol_h */
