  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIPlaylistEditorEndpoint_h
#define YTIPlaylistEditorEndpoint_h
@import Foundation;

#include "GPBMessage.h"

@class NSString;

@interface YTIPlaylistEditorEndpoint : GPBMessage

@property (copy, nonatomic) NSString *playlistId;
@property (nonatomic) _Bool hasPlaylistId;
@property (nonatomic) _Bool openCollaborationPage;
@property (nonatomic) _Bool hasOpenCollaborationPage;
@property (copy, nonatomic) NSString *params;
@property (nonatomic) _Bool hasParams;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIPlaylistEditorEndpoint_h */
