//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIPlayerKavRenderer_h
#define YTIPlayerKavRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIButtonSupportedRenderers.h"
#include "YTIFormattedString.h"
#include "YTIIcon.h"
#include "YTIThumbnailDetails.h"

@class NSString;

@interface YTIPlayerKavRenderer : GPBMessage

@property (copy, nonatomic) NSString *kavURL;
@property (nonatomic) _Bool hasKavURL;
@property (copy, nonatomic) NSString *playerParams;
@property (nonatomic) _Bool hasPlayerParams;
@property (copy, nonatomic) NSString *title;
@property (nonatomic) _Bool hasTitle;
@property (retain, nonatomic) YTIFormattedString *reason;
@property (nonatomic) _Bool hasReason;
@property (retain, nonatomic) YTIButtonSupportedRenderers *proceedButton;
@property (nonatomic) _Bool hasProceedButton;
@property (retain, nonatomic) YTIThumbnailDetails *thumbnail;
@property (nonatomic) _Bool hasThumbnail;
@property (retain, nonatomic) YTIIcon *icon;
@property (nonatomic) _Bool hasIcon;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIPlayerKavRenderer_h */
