  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIPostProminenceObserver_h
#define YTIPostProminenceObserver_h
@import Foundation;

#include "ELMPBCommand.h"
#include "GPBMessage.h"

@class NSString;

@interface YTIPostProminenceObserver : GPBMessage

@property (copy, nonatomic) NSString *groupKey;
@property (nonatomic) _Bool hasGroupKey;
@property (nonatomic) float visibilityRatio;
@property (nonatomic) _Bool hasVisibilityRatio;
@property (retain, nonatomic) ELMPBCommand *onEnter;
@property (nonatomic) _Bool hasOnEnter;
@property (retain, nonatomic) ELMPBCommand *onExit;
@property (nonatomic) _Bool hasOnExit;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIPostProminenceObserver_h */
