  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIPlayerBytesAdLayoutRenderer_h
#define YTIPlayerBytesAdLayoutRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIAdLayoutMetadata.h"
#include "YTIRenderer.h"

@class NSMutableArray;

@interface YTIPlayerBytesAdLayoutRenderer : GPBMessage

@property (retain, nonatomic) YTIAdLayoutMetadata *adLayoutMetadata;
@property (nonatomic) _Bool hasAdLayoutMetadata;
@property (retain, nonatomic) YTIRenderer *renderingContent;
@property (nonatomic) _Bool hasRenderingContent;
@property (retain, nonatomic) NSMutableArray *layoutExitNormalTriggersArray;
@property (readonly, nonatomic) unsigned long long layoutExitNormalTriggersArray_Count;
@property (retain, nonatomic) NSMutableArray *layoutExitSkipTriggersArray;
@property (readonly, nonatomic) unsigned long long layoutExitSkipTriggersArray_Count;
@property (retain, nonatomic) NSMutableArray *layoutExitMuteTriggersArray;
@property (readonly, nonatomic) unsigned long long layoutExitMuteTriggersArray_Count;
@property (retain, nonatomic) NSMutableArray *layoutExitUserInputSubmittedTriggersArray;
@property (readonly, nonatomic) unsigned long long layoutExitUserInputSubmittedTriggersArray_Count;
@property (nonatomic) _Bool suppressDisplayAd;
@property (nonatomic) _Bool hasSuppressDisplayAd;
@property (nonatomic) long long driftRecoveryMs;
@property (nonatomic) _Bool hasDriftRecoveryMs;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIPlayerBytesAdLayoutRenderer_h */
