//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIRemoteMutateCompositionOperation_h
#define YTIRemoteMutateCompositionOperation_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIMutateCreationContext.h"

@class NSData;

@interface YTIRemoteMutateCompositionOperation : GPBMessage

@property (retain, nonatomic) YTIMutateCreationContext *mutateCreationContext;
@property (nonatomic) _Bool hasMutateCreationContext;
@property (copy, nonatomic) NSData *clickTrackingParams;
@property (nonatomic) _Bool hasClickTrackingParams;
@property (nonatomic) long long clientRequestTimeoutMs;
@property (nonatomic) _Bool hasClientRequestTimeoutMs;
@property (nonatomic) long long maxRetries;
@property (nonatomic) _Bool hasMaxRetries;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIRemoteMutateCompositionOperation_h */
