  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIReelItemWatchResponse_h
#define YTIReelItemWatchResponse_h
@import Foundation;

#include "GPBMessage.h"
#include "GPBTimestamp.h"
#include "YTICommand.h"
#include "YTIFrameworkUpdateTransport.h"
#include "YTIPlayerResponse.h"
#include "YTIReelPlayerOverlaySupportedRenderers.h"
#include "YTIReelPlayerScrubber.h"
#include "YTIRenderer.h"
#include "YTIResponseContext.h"

@class NSData, NSMutableArray, NSString;

@interface YTIReelItemWatchResponse : GPBMessage

@property (retain, nonatomic) YTIResponseContext *responseContext;
@property (nonatomic) _Bool hasResponseContext;
@property (retain, nonatomic) YTIReelPlayerOverlaySupportedRenderers *overlay;
@property (nonatomic) _Bool hasOverlay;
@property (retain, nonatomic) YTIPlayerResponse *playerResponse;
@property (nonatomic) _Bool hasPlayerResponse;
@property (nonatomic) int status;
@property (nonatomic) _Bool hasStatus;
@property (copy, nonatomic) NSString *debugInfo;
@property (nonatomic) _Bool hasDebugInfo;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;
@property (nonatomic) int loopBehavior;
@property (nonatomic) _Bool hasLoopBehavior;
@property (nonatomic) int pipLoopBehavior;
@property (nonatomic) _Bool hasPipLoopBehavior;
@property (retain, nonatomic) YTIFrameworkUpdateTransport *frameworkUpdates;
@property (nonatomic) _Bool hasFrameworkUpdates;
@property (retain, nonatomic) YTICommand *replacementEndpoint;
@property (nonatomic) _Bool hasReplacementEndpoint;
@property (copy, nonatomic) NSString *sequenceContinuation;
@property (nonatomic) _Bool hasSequenceContinuation;
@property (retain, nonatomic) YTIRenderer *desktopTopbar;
@property (nonatomic) _Bool hasDesktopTopbar;
@property (retain, nonatomic) YTIRenderer *topbar;
@property (nonatomic) _Bool hasTopbar;
@property (retain, nonatomic) YTIRenderer *tooltip;
@property (nonatomic) _Bool hasTooltip;
@property (retain, nonatomic) NSMutableArray *engagementPanelsArray;
@property (readonly, nonatomic) unsigned long long engagementPanelsArray_Count;
@property (retain, nonatomic) YTIRenderer *watchStatus;
@property (nonatomic) _Bool hasWatchStatus;
@property (retain, nonatomic) YTICommand *onResponseReceivedCommand;
@property (nonatomic) _Bool hasOnResponseReceivedCommand;
@property (retain, nonatomic) YTICommand *onPageEnteredCommand;
@property (nonatomic) _Bool hasOnPageEnteredCommand;
@property (retain, nonatomic) YTIRenderer *background;
@property (nonatomic) _Bool hasBackground;
@property (retain, nonatomic) GPBTimestamp *responseTimestamp;
@property (nonatomic) _Bool hasResponseTimestamp;
@property (copy, nonatomic) NSString *updatableVideoInvalidationSignalEntityKey;
@property (nonatomic) _Bool hasUpdatableVideoInvalidationSignalEntityKey;
@property (retain, nonatomic) YTIRenderer *endscreenRenderer;
@property (nonatomic) _Bool hasEndscreenRenderer;
@property (retain, nonatomic) YTIReelPlayerScrubber *scrubber;
@property (nonatomic) _Bool hasScrubber;
@property (retain, nonatomic) YTIRenderer *microformat;
@property (nonatomic) _Bool hasMicroformat;
@property (retain, nonatomic) NSMutableArray *adSlotsArray;
@property (readonly, nonatomic) unsigned long long adSlotsArray_Count;
@property (retain, nonatomic) YTIRenderer *bottomActionBar;
@property (nonatomic) _Bool hasBottomActionBar;
@property (retain, nonatomic) YTIRenderer *persistentEducation;
@property (nonatomic) _Bool hasPersistentEducation;
@property (retain, nonatomic) YTIRenderer *onHorizontalSwipeContainer;
@property (nonatomic) _Bool hasOnHorizontalSwipeContainer;
@property (retain, nonatomic) NSMutableArray *signaledTriggerConditionsArray;
@property (readonly, nonatomic) unsigned long long signaledTriggerConditionsArray_Count;
@property (retain, nonatomic) NSMutableArray *topBarAccessoryViewsArray;
@property (readonly, nonatomic) unsigned long long topBarAccessoryViewsArray_Count;
@property (retain, nonatomic) YTIRenderer *engagementPanelOverlay;
@property (nonatomic) _Bool hasEngagementPanelOverlay;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIReelItemWatchResponse_h */
