  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIShowIncognitoAnimationCommand_h
#define YTIShowIncognitoAnimationCommand_h
@import Foundation;

#include "GPBMessage.h"
#include "YTICommand.h"

@class NSString;

@interface YTIShowIncognitoAnimationCommand : GPBMessage

@property (copy, nonatomic) NSString *targetId;
@property (nonatomic) _Bool hasTargetId;
@property (retain, nonatomic) YTICommand *nextEndpoint;
@property (nonatomic) _Bool hasNextEndpoint;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIShowIncognitoAnimationCommand_h */
