@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTISuspenseCommand_h
#define YTISuspenseCommand_h
@import Foundation;

#include "GPBMessage.h"
#include "YTICommand.h"
#include "YTIFormData.h"
#include "YTISuspenseContinuationData.h"
#include "YTISuspenseTriggerConfig.h"

@class NSString;

@interface YTISuspenseCommand : GPBMessage

@property (copy, nonatomic) NSString *configKey;
@property (nonatomic) _Bool hasConfigKey;
@property (retain, nonatomic) YTISuspenseTriggerConfig *triggerConfig;
@property (nonatomic) _Bool hasTriggerConfig;
@property (nonatomic) int placeholderBehavior;
@property (nonatomic) _Bool hasPlaceholderBehavior;
@property (nonatomic) int fetchBehavior;
@property (nonatomic) _Bool hasFetchBehavior;
@property (retain, nonatomic) YTIFormData *formData;
@property (nonatomic) _Bool hasFormData;
@property (copy, nonatomic) NSString *componentKey;
@property (nonatomic) _Bool hasComponentKey;
@property (copy, nonatomic) NSString *dataKey;
@property (nonatomic) _Bool hasDataKey;
@property (readonly, nonatomic) int continuationOptionsOneOfCase;
@property (retain, nonatomic) YTISuspenseContinuationData *suspenseContinuationData;
@property (nonatomic) _Bool hasSuspenseContinuationData;
@property (retain, nonatomic) YTICommand *continuationCommand;
@property (nonatomic) _Bool hasContinuationCommand;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTISuspenseCommand_h */
