  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIThumbnailLoaded_h
#define YTIThumbnailLoaded_h
@import Foundation;

#include "GPBEnumArray.h"
#include "GPBMessage.h"
#include "YTIThumbnailPreloaded.h"

@class NSString;

@interface YTIThumbnailLoaded : GPBMessage

@property (nonatomic) _Bool isMovingThumbnail;
@property (nonatomic) _Bool hasIsMovingThumbnail;
@property (nonatomic) int durationLoadingMs;
@property (nonatomic) _Bool hasDurationLoadingMs;
@property (copy, nonatomic) NSString *videoId;
@property (nonatomic) _Bool hasVideoId;
@property (copy, nonatomic) NSString *playlistId;
@property (nonatomic) _Bool hasPlaylistId;
@property (nonatomic) int widthPx;
@property (nonatomic) _Bool hasWidthPx;
@property (nonatomic) int heightPx;
@property (nonatomic) _Bool hasHeightPx;
@property (nonatomic) float pxToDpRatio;
@property (nonatomic) _Bool hasPxToDpRatio;
@property (nonatomic) int downloadedBytes;
@property (nonatomic) _Bool hasDownloadedBytes;
@property (nonatomic) int pageVeType;
@property (nonatomic) _Bool hasPageVeType;
@property (nonatomic) _Bool finishedLoading;
@property (nonatomic) _Bool hasFinishedLoading;
@property (copy, nonatomic) NSString *URL;
@property (nonatomic) _Bool hasURL;
@property (nonatomic) int URLCount;
@property (nonatomic) _Bool hasURLCount;
@property (nonatomic) int viewWidthPx;
@property (nonatomic) _Bool hasViewWidthPx;
@property (nonatomic) int viewHeightPx;
@property (nonatomic) _Bool hasViewHeightPx;
@property (nonatomic) int bitmapWidthPx;
@property (nonatomic) _Bool hasBitmapWidthPx;
@property (nonatomic) int bitmapHeightPx;
@property (nonatomic) _Bool hasBitmapHeightPx;
@property (nonatomic) int bitmapSize;
@property (nonatomic) _Bool hasBitmapSize;
@property (nonatomic) int deviceOrientation;
@property (nonatomic) _Bool hasDeviceOrientation;
@property (retain, nonatomic) GPBEnumArray *errorTypesArray;
@property (readonly, nonatomic) unsigned long long errorTypesArray_Count;
@property (nonatomic) int loadNumber;
@property (nonatomic) _Bool hasLoadNumber;
@property (nonatomic) int concurrentLoads;
@property (nonatomic) _Bool hasConcurrentLoads;
@property (nonatomic) _Bool isOtf;
@property (nonatomic) _Bool hasIsOtf;
@property (nonatomic) _Bool isLoadError;
@property (nonatomic) _Bool hasIsLoadError;
@property (nonatomic) _Bool appWentToBackground;
@property (nonatomic) _Bool hasAppWentToBackground;
@property (nonatomic) int numProcessors;
@property (nonatomic) _Bool hasNumProcessors;
@property (nonatomic) long long availableMemoryBytes;
@property (nonatomic) _Bool hasAvailableMemoryBytes;
@property (nonatomic) long long totalMemoryBytes;
@property (nonatomic) _Bool hasTotalMemoryBytes;
@property (nonatomic) _Bool isLowMemory;
@property (nonatomic) _Bool hasIsLowMemory;
@property (nonatomic) long long lowMemoryThresholdBytes;
@property (nonatomic) _Bool hasLowMemoryThresholdBytes;
@property (copy, nonatomic) NSString *URLQuery;
@property (nonatomic) _Bool hasURLQuery;
@property (retain, nonatomic) YTIThumbnailPreloaded *preload;
@property (nonatomic) _Bool hasPreload;
@property (nonatomic) int startupTemperature;
@property (nonatomic) _Bool hasStartupTemperature;
@property (nonatomic) int startupCompletionStatus;
@property (nonatomic) _Bool hasStartupCompletionStatus;
@property (copy, nonatomic) NSString *emlTemplateName;
@property (nonatomic) _Bool hasEmlTemplateName;
@property (copy, nonatomic) NSString *imageType;
@property (nonatomic) _Bool hasImageType;
@property (nonatomic) int HTTPErrorStatusCode;
@property (nonatomic) _Bool hasHTTPErrorStatusCode;
@property (copy, nonatomic) NSString *csn;
@property (nonatomic) _Bool hasCsn;
@property (nonatomic) long long imageViewVisibleTimeUsec;
@property (nonatomic) _Bool hasImageViewVisibleTimeUsec;
@property (nonatomic) _Bool isPrewarmedLaunch;
@property (nonatomic) _Bool hasIsPrewarmedLaunch;
@property (nonatomic) _Bool isBrowseRefresh;
@property (nonatomic) _Bool hasIsBrowseRefresh;
@property (retain, nonatomic) GPBEnumArray *collectionReasonsArray;
@property (readonly, nonatomic) unsigned long long collectionReasonsArray_Count;
@property (nonatomic) int diskCacheStaleness;
@property (nonatomic) _Bool hasDiskCacheStaleness;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIThumbnailLoaded_h */
