  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTITimeline_h
#define YTITimeline_h
@import Foundation;

#include "GPBMessage.h"
#include "YTITime.h"

@class NSString;

@interface YTITimeline : GPBMessage

@property (copy, nonatomic) NSString *id_p;
@property (nonatomic) _Bool hasId_p;
@property (nonatomic) _Bool looped;
@property (nonatomic) _Bool hasLooped;
@property (retain, nonatomic) YTITime *loopStart;
@property (nonatomic) _Bool hasLoopStart;
@property (retain, nonatomic) YTITime *loopEnd;
@property (nonatomic) _Bool hasLoopEnd;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTITimeline_h */
