  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTITopbarLogoRenderer_h
#define YTITopbarLogoRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTICommand.h"
#include "YTIFormattedString.h"
#include "YTIIcon.h"
#include "YTIRenderer.h"
#include "YTIRendererContext.h"
#include "YTIThumbnailDetails.h"

@class NSData, NSString;

@interface YTITopbarLogoRenderer : GPBMessage

@property (readonly, nonatomic) int imageOneOfCase;
@property (retain, nonatomic) YTIIcon *iconImage;
@property (nonatomic) _Bool hasIconImage;
@property (retain, nonatomic) YTIThumbnailDetails *thumbnailImage;
@property (nonatomic) _Bool hasThumbnailImage;
@property (readonly, nonatomic) int darkThemeImageOneOfCase;
@property (retain, nonatomic) YTIIcon *darkThemeIconImage;
@property (nonatomic) _Bool hasDarkThemeIconImage;
@property (retain, nonatomic) YTIThumbnailDetails *darkThemeThumbnailImage;
@property (nonatomic) _Bool hasDarkThemeThumbnailImage;
@property (retain, nonatomic) YTIFormattedString *tooltipText;
@property (nonatomic) _Bool hasTooltipText;
@property (retain, nonatomic) YTICommand *endpoint;
@property (nonatomic) _Bool hasEndpoint;
@property (retain, nonatomic) YTIRenderer *yoodle;
@property (nonatomic) _Bool hasYoodle;
@property (copy, nonatomic) NSString *overrideEntityKey;
@property (nonatomic) _Bool hasOverrideEntityKey;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;
@property (retain, nonatomic) YTIRendererContext *rendererContext;
@property (nonatomic) _Bool hasRendererContext;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTITopbarLogoRenderer_h */
