  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIUnpluggedLocationRenderer_h
#define YTIUnpluggedLocationRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIButtonSupportedRenderers.h"
#include "YTIFormattedString.h"
#include "YTIThumbnailDetails.h"
#include "YTIUnpluggedAnimationDetails.h"
#include "YTIUnpluggedEditTextSupportedRenderers.h"

@class NSData, NSMutableArray;

@interface YTIUnpluggedLocationRenderer : GPBMessage

@property (retain, nonatomic) YTIThumbnailDetails *headerIcon;
@property (nonatomic) _Bool hasHeaderIcon;
@property (retain, nonatomic) YTIUnpluggedAnimationDetails *animation;
@property (nonatomic) _Bool hasAnimation;
@property (retain, nonatomic) YTIFormattedString *locationName;
@property (nonatomic) _Bool hasLocationName;
@property (retain, nonatomic) YTIFormattedString *zipCode;
@property (nonatomic) _Bool hasZipCode;
@property (retain, nonatomic) YTIFormattedString *titleText;
@property (nonatomic) _Bool hasTitleText;
@property (retain, nonatomic) YTIFormattedString *bodyText;
@property (nonatomic) _Bool hasBodyText;
@property (nonatomic) unsigned int bodyTextColor;
@property (nonatomic) _Bool hasBodyTextColor;
@property (retain, nonatomic) YTIUnpluggedEditTextSupportedRenderers *unpluggedEditText;
@property (nonatomic) _Bool hasUnpluggedEditText;
@property (retain, nonatomic) YTIButtonSupportedRenderers *changeLocationButton;
@property (nonatomic) _Bool hasChangeLocationButton;
@property (retain, nonatomic) YTIButtonSupportedRenderers *logInButton;
@property (nonatomic) _Bool hasLogInButton;
@property (retain, nonatomic) NSMutableArray *buttonsArray;
@property (readonly, nonatomic) unsigned long long buttonsArray_Count;
@property (retain, nonatomic) YTIFormattedString *headerText;
@property (nonatomic) _Bool hasHeaderText;
@property (retain, nonatomic) YTIButtonSupportedRenderers *actionButton;
@property (nonatomic) _Bool hasActionButton;
@property (retain, nonatomic) YTIButtonSupportedRenderers *improveLocationGhelpButton;
@property (nonatomic) _Bool hasImproveLocationGhelpButton;
@property (retain, nonatomic) YTIButtonSupportedRenderers *improveLocationStartFlowButton;
@property (nonatomic) _Bool hasImproveLocationStartFlowButton;
@property (retain, nonatomic) NSMutableArray *locationChoicesArray;
@property (readonly, nonatomic) unsigned long long locationChoicesArray_Count;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIUnpluggedLocationRenderer_h */
