  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIUpdateBroadcastConferenceRequest_h
#define YTIUpdateBroadcastConferenceRequest_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIInnerTubeContext.h"
#include "YTIUpdateBroadcastConferenceParams.h"
#include "YTIUpdateBroadcastConferenceParamsMask.h"

@class NSString;

@interface YTIUpdateBroadcastConferenceRequest : GPBMessage

@property (retain, nonatomic) YTIInnerTubeContext *context;
@property (nonatomic) _Bool hasContext;
@property (copy, nonatomic) NSString *externalVideoId;
@property (nonatomic) _Bool hasExternalVideoId;
@property (retain, nonatomic) YTIUpdateBroadcastConferenceParams *updateParams;
@property (nonatomic) _Bool hasUpdateParams;
@property (retain, nonatomic) YTIUpdateBroadcastConferenceParamsMask *updateParamsMask;
@property (nonatomic) _Bool hasUpdateParamsMask;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIUpdateBroadcastConferenceRequest_h */
