//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIUpdateChannelPageSettingsResponse_h
#define YTIUpdateChannelPageSettingsResponse_h
@import Foundation;

#include "GPBMessage.h"
#include "YTICreatorChannelData.h"
#include "YTIFrameworkUpdateTransport.h"
#include "YTIHandleUpdateStatus.h"
#include "YTIResponseContext.h"
#include "YTIUpdateStatus.h"

@interface YTIUpdateChannelPageSettingsResponse : GPBMessage

@property (retain, nonatomic) YTIResponseContext *responseContext;
@property (nonatomic) _Bool hasResponseContext;
@property (retain, nonatomic) YTICreatorChannelData *updatedChannelEntity;
@property (nonatomic) _Bool hasUpdatedChannelEntity;
@property (retain, nonatomic) YTIUpdateStatus *watchMilestoneCampaignUpdateStatus;
@property (nonatomic) _Bool hasWatchMilestoneCampaignUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *trailerVideoUpdateStatus;
@property (nonatomic) _Bool hasTrailerVideoUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *featuredVideoUpdateStatus;
@property (nonatomic) _Bool hasFeaturedVideoUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *shelfListUpdateStatus;
@property (nonatomic) _Bool hasShelfListUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *channelLinksUpdateStatus;
@property (nonatomic) _Bool hasChannelLinksUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *businessEmailUpdateStatus;
@property (nonatomic) _Bool hasBusinessEmailUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *avatarImageUpdateStatus;
@property (nonatomic) _Bool hasAvatarImageUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *descriptionUpdateStatus;
@property (nonatomic) _Bool hasDescriptionUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *bannerImageUpdateStatus;
@property (nonatomic) _Bool hasBannerImageUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *watermarkImageUpdateStatus;
@property (nonatomic) _Bool hasWatermarkImageUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *vanityURLClaimStatus;
@property (nonatomic) _Bool hasVanityURLClaimStatus;
@property (retain, nonatomic) YTIHandleUpdateStatus *newHandleUpdateStatus;
@property (nonatomic) _Bool hasNewHandleUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *forYouShelfUpdateStatus;
@property (nonatomic) _Bool hasForYouShelfUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *pronounsUpdateStatus;
@property (nonatomic) _Bool hasPronounsUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *homeTabUpdateStatus;
@property (nonatomic) _Bool hasHomeTabUpdateStatus;
@property (retain, nonatomic) YTIUpdateStatus *shoppingModuleMobileUpdateStatus;
@property (nonatomic) _Bool hasShoppingModuleMobileUpdateStatus;
@property (nonatomic) _Bool successfulUpdate;
@property (nonatomic) _Bool hasSuccessfulUpdate;
@property (retain, nonatomic) YTIFrameworkUpdateTransport *frameworkUpdates;
@property (nonatomic) _Bool hasFrameworkUpdates;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIUpdateChannelPageSettingsResponse_h */
