  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIWatchBreakRenderer_h
#define YTIWatchBreakRenderer_h
@import Foundation;

#include "GPBMessage.h"
#include "YTIFormattedString.h"
#include "YTIRenderer.h"

@class NSData;

@interface YTIWatchBreakRenderer : GPBMessage

@property (retain, nonatomic) YTIFormattedString *heading;
@property (nonatomic) _Bool hasHeading;
@property (retain, nonatomic) YTIFormattedString *notice;
@property (nonatomic) _Bool hasNotice;
@property (retain, nonatomic) YTIRenderer *primaryButton;
@property (nonatomic) _Bool hasPrimaryButton;
@property (retain, nonatomic) YTIRenderer *secondaryButton;
@property (nonatomic) _Bool hasSecondaryButton;
@property (nonatomic) int watchBreakType;
@property (nonatomic) _Bool hasWatchBreakType;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) _Bool hasTrackingParams;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIWatchBreakRenderer_h */
