  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTIYtMainDownloadsListEntityActionMetadata_h
#define YTIYtMainDownloadsListEntityActionMetadata_h
@import Foundation;

#include "GPBMessage.h"

@interface YTIYtMainDownloadsListEntityActionMetadata : GPBMessage

@property (nonatomic) int browseRequestContext;
@property (nonatomic) _Bool hasBrowseRequestContext;
@property (nonatomic) _Bool shouldNotRefreshContent;
@property (nonatomic) _Bool hasShouldNotRefreshContent;
@property (nonatomic) _Bool shouldDoOfflineRefresh;
@property (nonatomic) _Bool hasShouldDoOfflineRefresh;

/* class methods */
+ (id)descriptor;

@end

#endif /* YTIYtMainDownloadsListEntityActionMetadata_h */
