@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTLabel_h
#define YTLabel_h
@import Foundation;

#include "YTFontAttributes.h"
#include "YTPageStyling-Protocol.h"

@class NSString, UIColor, UILabel;

@interface YTLabel : UILabel <YTPageStyling> {
    /* instance variables */
    long long _pageStyle;
    long long _typeKind;
    long long _typeVariant;
    UIColor *_textColor;
    _Bool _useBoldFontKind;
    YTFontAttributes *_fontAttributes;
    NSString *_labelText;
    _Bool _isFontAttributesSupportEnabled;
    _Bool _useMonospacedFont;
}

@property (nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } edgeInsets;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)initWithFontAttributesSupportEnabled:(_Bool)enabled;
- (void)drawTextInRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)setTypeKind:(long long)kind;
- (void)setTypeKind:(long long)kind typeVariant:(long long)variant;
- (void)setTypeKindForBold:(long long)bold;
- (void)setTypeKindForBold:(long long)bold typeVariant:(long long)variant;
- (void)setTypeVariant:(long long)variant;
- (void)setTextColor:(id)color;
- (void)traitCollectionDidChange:(id)change;
- (void)setFontAttributes:(id)attributes text:(id)text;
- (void)setUseMonospacedFont:(_Bool)font;
- (id)accessibilityLabel;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(id)superview;
- (void)pageStyleDidChange:(long long)change;
- (void)applyTypeStyle;

@end

#endif /* YTLabel_h */
