  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTLogoEntityModel_h
#define YTLogoEntityModel_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSMutableCopying-Protocol.h"
#include "YTCommandModel.h"
#include "YTEntity-Protocol.h"
#include "YTEntityStore-Protocol.h"
#include "YTIAccessibilitySupportedDatas.h"
#include "YTIFormattedString.h"
#include "YTILogoEntity.h"
#include "YTLoggingDirectivesModel.h"
#include "YTLogoEntity_OneofIconOrThumbnailModel.h"
#include "YTThumbnailDetailsModel.h"
#include "YTVisualElement.h"

@class NSData, NSDictionary, NSObject, NSString;

@interface YTLogoEntityModel : NSObject <YTEntity, NSCopying, NSMutableCopying> {
    /* instance variables */
    NSString *_key;
}

@property (readonly, nonatomic) YTVisualElement *yt_interactionLoggingProxyButton;
@property (retain, nonatomic) YTLogoEntity_OneofIconOrThumbnailModel *lightThemeLogo;
@property (retain, nonatomic) YTLogoEntity_OneofIconOrThumbnailModel *darkThemeLogo;
@property (retain, nonatomic) YTThumbnailDetailsModel *lightThemeAnimatedLogo;
@property (retain, nonatomic) YTThumbnailDetailsModel *darkThemeAnimatedLogo;
@property (retain, nonatomic) YTCommandModel *onTapCommand;
@property (retain, nonatomic) YTIFormattedString *tooltipText;
@property (retain, nonatomic) YTIAccessibilitySupportedDatas *accessibilityData;
@property (retain, nonatomic) YTLoggingDirectivesModel *loggingDirectives;
@property (nonatomic) _Bool parseAndExtractFieldsFromProtoData;
@property (nonatomic) _Bool generateData;
@property (copy, nonatomic) YTILogoEntity *protoBuf;
@property (copy, nonatomic) NSData *data;
@property (copy, nonatomic) NSDictionary *entityMetadata;
@property (readonly, nonatomic) id <YTEntityStore> entityStore;
@property (readonly, nonatomic) NSString *promoId;
@property (readonly, copy, nonatomic) YTILogoEntity *proto;
@property (readonly, copy, nonatomic) NSString *entityKey;
@property (readonly, copy, nonatomic) NSData *entityVersion;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)yt_lottieAnimationURLForPageStyle:(long long)style;
- (id)yt_thumbnailsForPageStyle:(long long)style;
- (id)yt_iconImageForPageStyle:(long long)style;
- (_Bool)yt_isLogoResourcesEqualToResourcesForLogoEntity:(id)entity;
- (id)initWithEntityStore:(id)store protoBuf:(id)buf;
- (id)initWithEntityStore:(id)store protoBuf:(id)buf entityMetadata:(id)metadata;
- (id)initWithEntityStore:(id)store entityKey:(id)key protoBufData:(id)data;
- (id)initWithEntityStore:(id)store entityKey:(id)key protoBufData:(id)data entityMetadata:(id)metadata;
- (id)initWithEntityStore:(id)store entityKey:(id)key protoBuf:(id)buf protoBufData:(id)data entityMetadata:(id)metadata;
- (id)init;
- (_Bool)isEqual:(id)equal;
- (_Bool)isEqualToEntity:(id)entity;
- (id)allAssociationKeys;
- (id)copy;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopy;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (void)parseAndExtractFieldsFromProtoIfNecessary;
- (void)generateDataIfNecessary;
- (_Bool)isEqualEntityValue:(id)value;

@end

#endif /* YTLogoEntityModel_h */
