  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTMainVideoEntityModel_h
#define YTMainVideoEntityModel_h
@import Foundation;

#include "GPBMessage.h"
#include "NSCopying-Protocol.h"
#include "NSMutableCopying-Protocol.h"
#include "YTDownloadedVideoEntityModel-Protocol.h"
#include "YTDownloadedVideoModel-Protocol.h"
#include "YTEntity-Protocol.h"
#include "YTEntityStore-Protocol.h"
#include "YTFormattedStringModel.h"
#include "YTIClientEndpointBuilderData.h"
#include "YTIFormattedString.h"
#include "YTIMainVideoEntity.h"
#include "YTIOfflineFutureUnplayableInfo.h"
#include "YTIOfflineState.h"
#include "YTIThumbnailDetails.h"
#include "YTMainVideoAdditionalMetadataModel.h"
#include "YTMainVideoDownloadStateEntityModel.h"
#include "YTMainVideoUserStateMetadataModel.h"
#include "YTOfflineVideoPolicyEntityModel.h"
#include "YTPlaybackDataEntityModel.h"
#include "YTRecommendedDownloadVideoEntityModel-Protocol.h"
#include "YTThumbnailDetailsModel.h"
#include "YTYtMainChannelEntityModel.h"
#include "YTYtMainVideoEntityLocalizedStringsModel.h"

@class NSArray, NSData, NSDate, NSDictionary, NSMutableArray, NSObject, NSString;

@interface YTMainVideoEntityModel : NSObject <YTDownloadedVideoModel, YTDownloadedVideoEntityModel, YTRecommendedDownloadVideoEntityModel, YTEntity, NSCopying, NSMutableCopying> {
    /* instance variables */
    NSString *_key;
}

@property (readonly, nonatomic) NSString *yt_videoID;
@property (readonly, nonatomic) YTPlaybackDataEntityModel *yt_playbackDataEntity;
@property (readonly, nonatomic) YTOfflineVideoPolicyEntityModel *yt_offlineVideoPolicyEntity;
@property (readonly, copy, nonatomic) NSString *entityKey;
@property (readonly, copy, nonatomic) NSData *entityVersion;
@property (readonly, copy, nonatomic) GPBMessage *proto;
@property (readonly, copy, nonatomic) NSData *data;
@property (readonly, copy, nonatomic) NSDictionary *entityMetadata;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSString *videoID;
@property (readonly, nonatomic) NSString *title;
@property (readonly, nonatomic) YTIThumbnailDetails *videoThumbnail;
@property (readonly, nonatomic) int status;
@property (readonly, nonatomic) NSData *clickTrackingParams;
@property (readonly, nonatomic) _Bool hasDrmParams;
@property (readonly, nonatomic) NSString *shortViewCountText;
@property (readonly, nonatomic) long long viewCount;
@property (readonly, nonatomic) long long likeCountInteger;
@property (readonly, nonatomic) NSString *likeCountString;
@property (readonly, nonatomic) NSString *dislikeCountString;
@property (readonly, nonatomic) NSString *likeCountAccessibilityText;
@property (readonly, nonatomic) NSString *dislikeAccessibilityText;
@property (readonly, nonatomic) NSString *viewCountAccessibilityText;
@property (readonly, nonatomic) long long publishedTimestampMillis;
@property (readonly, nonatomic) NSString *publishedDateText;
@property (readonly, nonatomic) NSString *publishedDateAccessibilityText;
@property (readonly, nonatomic) NSString *subscriberCountText;
@property (readonly, nonatomic) YTIFormattedString *descriptionString;
@property (readonly, nonatomic) NSString *channelTitle;
@property (readonly, nonatomic) YTIThumbnailDetails *channelAvatar;
@property (readonly, nonatomic) NSString *lengthText;
@property (readonly, nonatomic) int lengthSeconds;
@property (readonly, nonatomic) NSMutableArray *additionalMetadatasArray;
@property (readonly, nonatomic) YTIClientEndpointBuilderData *endpointOverrideData;
@property (readonly, nonatomic) YTIOfflineFutureUnplayableInfo *offlineFutureUnplayableInfo;
@property (readonly, nonatomic) YTIOfflineState *offlineState;
@property (readonly, nonatomic) NSDate *offlineStateDate;
@property (readonly, nonatomic) unsigned int expiresInSeconds;
@property (readonly, nonatomic) NSDate *expiryDate;
@property (readonly, nonatomic) long long resumePlaybackPosition;
@property (readonly, nonatomic) unsigned int watchPercentForBadge;
@property (readonly, nonatomic) NSString *channelHandle;
@property (readonly, nonatomic) NSString *lexicographicalSortValue;
@property (readonly, nonatomic) NSDate *chronologicalSortValue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) YTThumbnailDetailsModel *thumbnail;
@property (retain, nonatomic) YTFormattedStringModel *formattedDescription;
@property (retain, nonatomic) YTYtMainVideoEntityLocalizedStringsModel *localizedStrings;
@property (retain, nonatomic) YTMainVideoUserStateMetadataModel *userState;
@property (retain, nonatomic) NSArray *downloadFormatsArray;
@property (retain, nonatomic) YTMainVideoAdditionalMetadataModel *additionalMetadata;
@property (nonatomic) _Bool parseAndExtractFieldsFromProtoData;
@property (nonatomic) _Bool generateData;
@property (copy, nonatomic) YTIMainVideoEntity *protoBuf;
@property (copy, nonatomic) NSData *data;
@property (copy, nonatomic) NSDictionary *entityMetadata;
@property (readonly, nonatomic) id <YTEntityStore> entityStore;
@property (readonly, nonatomic) NSString *ownerKey;
@property (readonly, nonatomic) YTYtMainChannelEntityModel *owner;
@property (readonly, nonatomic) NSString *downloadStateKey;
@property (readonly, nonatomic) YTMainVideoDownloadStateEntityModel *downloadState;
@property (readonly, nonatomic) NSString *videoId;
@property (readonly, nonatomic) NSString *title;
@property (readonly, nonatomic) _Bool hasPublishedTimestampMillis;
@property (readonly, nonatomic) unsigned long long publishedTimestampMillis;
@property (readonly, nonatomic) _Bool hasLengthSeconds;
@property (readonly, nonatomic) int lengthSeconds;
@property (readonly, nonatomic) _Bool hasViewCount;
@property (readonly, nonatomic) unsigned long long viewCount;
@property (readonly, nonatomic) _Bool hasLikeCount;
@property (readonly, nonatomic) unsigned long long likeCount;
@property (readonly, nonatomic) _Bool hasDislikeCount;
@property (readonly, nonatomic) unsigned long long dislikeCount;
@property (readonly, copy, nonatomic) YTIMainVideoEntity *proto;
@property (readonly, copy, nonatomic) NSString *entityKey;
@property (readonly, copy, nonatomic) NSData *entityVersion;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (int)offlineVideoStatusFromTransferState:(int)state;

/* instance methods */
- (id)transferEntity;
- (id)asyncGetClickTrackingParams;
- (_Bool)canBeResumed;
- (_Bool)canBePaused;
- (_Bool)isPlayableOfflineWithReason:(id *)reason;
- (id)asyncCheckIsPlayableOffline;
- (_Bool)isPlayableOfflineWithUpsell:(id *)upsell;
- (id)asyncGetOfflineStateDate;
- (id)playerData;
- (id)playbackDataEntity;
- (id)asyncGetPlayerData;
- (id)offlineStateDateWithOfflineVideoPolicy:(id)policy;
- (int)statusWithDownloadState:(id)state transfer:(id)transfer;
- (unsigned int)getWatchPercentWithLastPlaybackPositionSeconds:(long long)seconds;
- (_Bool)isMostlyWatchedWithWatchPercent:(unsigned int)percent secondsLeft:(long long)left;
- (id)offlineVideoPolicyEntity;
- (_Bool)isPlayableOfflineWithUpsell:(id *)upsell downloadState:(id)state playbackData:(id)data transfer:(id)transfer offlineVideoPolicy:(id)policy;
- (id)playlistPanelVideoRendererWithPlaylistID:(id)id index:(unsigned long long)index offlineMode:(_Bool)mode isPendingRemove:(_Bool)remove;
- (id)slimVideoMetadataSectionRenderer;
- (id)lockScreenRenderer;
- (id)drmExpirationSimpleTextSectionRenderer;
- (id)initWithEntityStore:(id)store protoBuf:(id)buf;
- (id)initWithEntityStore:(id)store protoBuf:(id)buf entityMetadata:(id)metadata;
- (id)initWithEntityStore:(id)store entityKey:(id)key protoBufData:(id)data;
- (id)initWithEntityStore:(id)store entityKey:(id)key protoBufData:(id)data entityMetadata:(id)metadata;
- (id)initWithEntityStore:(id)store entityKey:(id)key protoBuf:(id)buf protoBufData:(id)data entityMetadata:(id)metadata;
- (id)init;
- (_Bool)isEqual:(id)equal;
- (_Bool)isEqualToEntity:(id)entity;
- (void)ownerWithCallbackQueue:(id)queue completionBlock:(id /* block */)block;
- (void)downloadStateWithCallbackQueue:(id)queue completionBlock:(id /* block */)block;
- (id)allAssociationKeys;
- (id)copy;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopy;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (void)parseAndExtractFieldsFromProtoIfNecessary;
- (void)generateDataIfNecessary;
- (_Bool)isEqualEntityValue:(id)value;

@end

#endif /* YTMainVideoEntityModel_h */
