  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTMainDownloadsListEntity_ItemModel_h
#define YTMainDownloadsListEntity_ItemModel_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSMutableCopying-Protocol.h"
#include "YTEntityStore-Protocol.h"
#include "YTIMainDownloadsListEntity_Item.h"
#include "YTMainPlaylistEntityModel.h"
#include "YTMainVideoEntityModel.h"
#include "YTYtMainDownloadedPlaylistEntityModel.h"
#include "YTYtMainDownloadedVideoEntityModel.h"

@class NSData, NSObject, NSString;

@interface YTMainDownloadsListEntity_ItemModel : NSObject <NSCopying, NSMutableCopying>

@property (nonatomic) _Bool parseAndExtractFieldsFromProtoData;
@property (nonatomic) _Bool generateData;
@property (copy, nonatomic) YTIMainDownloadsListEntity_Item *protoBuf;
@property (copy, nonatomic) NSData *data;
@property (readonly, nonatomic) id <YTEntityStore> entityStore;
@property (readonly, nonatomic) int itemOneOfCase;
@property (readonly, nonatomic) NSString *videoKey;
@property (readonly, nonatomic) YTYtMainDownloadedVideoEntityModel *video;
@property (readonly, nonatomic) NSString *playlistKey;
@property (readonly, nonatomic) YTYtMainDownloadedPlaylistEntityModel *playlist;
@property (readonly, nonatomic) NSString *videoItemKey;
@property (readonly, nonatomic) YTMainVideoEntityModel *videoItem;
@property (readonly, nonatomic) NSString *playlistItemKey;
@property (readonly, nonatomic) YTMainPlaylistEntityModel *playlistItem;
@property (readonly, copy, nonatomic) YTIMainDownloadsListEntity_Item *proto;

/* instance methods */
- (id)initWithEntityStore:(id)store protoBuf:(id)buf;
- (id)initWithEntityStore:(id)store protoBufData:(id)data;
- (id)initWithEntityStore:(id)store entityKey:(id)key protoBuf:(id)buf protoBufData:(id)data;
- (id)init;
- (id)entityVersion;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)videoWithCallbackQueue:(id)queue completionBlock:(id /* block */)block;
- (void)playlistWithCallbackQueue:(id)queue completionBlock:(id /* block */)block;
- (void)videoItemWithCallbackQueue:(id)queue completionBlock:(id /* block */)block;
- (void)playlistItemWithCallbackQueue:(id)queue completionBlock:(id /* block */)block;
- (id)allAssociationKeys;
- (id)copy;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopy;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (void)parseAndExtractFieldsFromProtoIfNecessary;
- (void)generateDataIfNecessary;
- (_Bool)isEqualEntityValue:(id)value;

@end

#endif /* YTMainDownloadsListEntity_ItemModel_h */
