  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTMediaGenBlockDelegate_Protocol_h
#define YTMediaGenBlockDelegate_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol YTMediaGenBlockDelegate <NSObject>

@required

/* required instance methods */
- (void)mediaGenBlockDidStartGetDynamicCreationAssetCall:(id)call;
- (void)mediaGenBlockDidMakeSuccessfulGetDynamicCreationAssetCall:(id)call response:(id)response;
- (void)mediaGenBlock:(id)block getDynamicCreationAssetDidFailWithError:(id)error response:(id)response;
- (void)mediaGenBlock:(id)block willUpdateLoadingSpinnerWithVisibility:(_Bool)visibility;

@optional

@end

#endif /* YTMediaGenBlockDelegate_Protocol_h */
