  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTMigrationPlaybackDataEntityController_h
#define YTMigrationPlaybackDataEntityController_h
@import Foundation;

#include "YTLegacyOfflineDataHandler-Protocol.h"
#include "YTOfflineEntityController-Protocol.h"
#include "YTOfflineEntityControllerBatchingExtension-Protocol.h"
#include "YTOfflinePlaybackDataEntityController.h"
#include "YTOfflinePlaybackDataEntityShimController.h"

@class NSObject, NSString;

@interface YTMigrationPlaybackDataEntityController : NSObject <YTOfflineEntityController, YTOfflineEntityControllerBatchingExtension, YTLegacyOfflineDataHandler> {
    /* instance variables */
    YTOfflinePlaybackDataEntityShimController *_playbackDataEntityShimController;
    YTOfflinePlaybackDataEntityController *_playbackDataEntityController;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (long long)entityType;

/* instance methods */
- (id)init;
- (id)handleAction:(id)action actionID:(id)id forIdentity:(id)identity;
- (id)actionBatchRulesForAction:(id)action;
- (id)handleActions:(id)actions forIdentity:(id)identity;
- (void)handleLegacyOfflineData:(id)data completionBlock:(id /* block */)block;
- (void)handlePlaybackDataEntityDeleteAction:(id)action actionID:(id)id forIdentity:(id)identity promise:(id)promise;
- (void)handleDeleteVideoResponseWithVideoID:(id)id action:(id)action actionID:(id)id forIdentity:(id)identity promise:(id)promise didRemoveFromStore:(_Bool)store;
- (id)handlePlayerResponseBytesIfNeeded:(id)needed;
- (id)handleOfflineStateIfNeeded:(id)needed;
- (id)resolveInvalidAction;
- (id)resolveInvalidActions:(id)actions;
- (_Bool)isMigrationEnabledForPesAction;
- (_Bool)isMigrationSoftRollbackEnabledForPesAction;

@end

#endif /* YTMigrationPlaybackDataEntityController_h */
