  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTMutableWebViewEntityModel_h
#define YTMutableWebViewEntityModel_h
@import Foundation;

#include "GPBMessage.h"
#include "YTMutableEntity-Protocol.h"
#include "YTWebViewEntityModel.h"

@class NSData, NSDictionary, NSString;

@interface YTMutableWebViewEntityModel : YTWebViewEntityModel <YTMutableEntity>

@property (retain, nonatomic) NSString *fullURL;
@property (retain, nonatomic) NSString *hostName;
@property (retain, nonatomic) NSString *schema;
@property (nonatomic) _Bool is3PHost;
@property (retain, nonatomic) NSString *pageTitle;
@property (nonatomic) _Bool isLoaded;
@property (nonatomic) _Bool canGoBack;
@property (nonatomic) _Bool canGoForward;
@property (nonatomic) _Bool isSecuredURL;
@property (copy, nonatomic) NSData *data;
@property (copy, nonatomic) NSDictionary *entityMetadata;
@property (readonly, copy, nonatomic) NSString *entityKey;
@property (readonly, copy, nonatomic) NSData *entityVersion;
@property (readonly, copy, nonatomic) GPBMessage *proto;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithEntityStore:(id)store entityKey:(id)key;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)parseAndExtractFieldsFromProtoIfNecessary;

@end

#endif /* YTMutableWebViewEntityModel_h */
