//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTMutableReplyCountEntityModel_h
#define YTMutableReplyCountEntityModel_h
@import Foundation;

#include "ELMPBAttributedString.h"
#include "GPBMessage.h"
#include "YTMutableEntity-Protocol.h"
#include "YTReplyCountEntityModel.h"

@class NSData, NSDictionary, NSString;

@interface YTMutableReplyCountEntityModel : YTReplyCountEntityModel <YTMutableEntity>

@property (retain, nonatomic) ELMPBAttributedString *replyCount;
@property (nonatomic) long long replyCountNumber;
@property (retain, nonatomic) NSString *replyButtonAccessibilityText;
@property (copy, nonatomic) NSData *data;
@property (copy, nonatomic) NSDictionary *entityMetadata;
@property (readonly, copy, nonatomic) NSString *entityKey;
@property (readonly, copy, nonatomic) NSData *entityVersion;
@property (readonly, copy, nonatomic) GPBMessage *proto;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithEntityStore:(id)store entityKey:(id)key;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)parseAndExtractFieldsFromProtoIfNecessary;

@end

#endif /* YTMutableReplyCountEntityModel_h */
