  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTMutableLikeCountEntityModel_h
#define YTMutableLikeCountEntityModel_h
@import Foundation;

#include "ELMPBAttributedString.h"
#include "GPBMessage.h"
#include "YTLikeCountEntityModel.h"
#include "YTMutableEntity-Protocol.h"

@class NSData, NSDictionary, NSString;

@interface YTMutableLikeCountEntityModel : YTLikeCountEntityModel <YTMutableEntity>

@property (retain, nonatomic) ELMPBAttributedString *likeCountIfLiked;
@property (retain, nonatomic) ELMPBAttributedString *likeCountIfDisliked;
@property (retain, nonatomic) ELMPBAttributedString *likeCountIfIndifferent;
@property (retain, nonatomic) ELMPBAttributedString *expandedLikeCountIfLiked;
@property (retain, nonatomic) ELMPBAttributedString *expandedLikeCountIfDisliked;
@property (retain, nonatomic) ELMPBAttributedString *expandedLikeCountIfIndifferent;
@property (retain, nonatomic) ELMPBAttributedString *likeCountLabel;
@property (retain, nonatomic) ELMPBAttributedString *likeButtonA11YText;
@property (nonatomic) long long likeCountIfLikedNumber;
@property (nonatomic) long long likeCountIfDislikedNumber;
@property (nonatomic) long long likeCountIfIndifferentNumber;
@property (nonatomic) _Bool shouldExpandLikeCount;
@property (retain, nonatomic) ELMPBAttributedString *sentimentFactoidA11YTextIfLiked;
@property (retain, nonatomic) ELMPBAttributedString *sentimentFactoidA11YTextIfDisliked;
@property (copy, nonatomic) NSData *data;
@property (copy, nonatomic) NSDictionary *entityMetadata;
@property (readonly, copy, nonatomic) NSString *entityKey;
@property (readonly, copy, nonatomic) NSData *entityVersion;
@property (readonly, copy, nonatomic) GPBMessage *proto;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithEntityStore:(id)store entityKey:(id)key;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)parseAndExtractFieldsFromProtoIfNecessary;

@end

#endif /* YTMutableLikeCountEntityModel_h */
