  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTMutableDownloadsPagePlaylistEntity_CollageThumbnailModel_h
#define YTMutableDownloadsPagePlaylistEntity_CollageThumbnailModel_h
@import Foundation;

#include "YTDownloadsPagePlaylistEntity_CollageThumbnailModel.h"

@class NSArray, NSData;

@interface YTMutableDownloadsPagePlaylistEntity_CollageThumbnailModel : YTDownloadsPagePlaylistEntity_CollageThumbnailModel

@property (retain, nonatomic) NSArray *firstColumnThumbnailsArray;
@property (retain, nonatomic) NSArray *secondColumnThumbnailsArray;
@property (nonatomic) int style;
@property (nonatomic) unsigned int firstColumnCoverThumbnailBackgroundColor;
@property (copy, nonatomic) NSData *data;

/* instance methods */
- (id)initWithEntityStore:(id)store;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)parseAndExtractFieldsFromProtoIfNecessary;

@end

#endif /* YTMutableDownloadsPagePlaylistEntity_CollageThumbnailModel_h */
