//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTNotificationMultiToggleButton_h
#define YTNotificationMultiToggleButton_h
@import Foundation;

#include "YTColor.h"
#include "YTHintViewAnchor-Protocol.h"
#include "YTIThemedBasicColorPalette.h"
#include "YTPageStyling-Protocol.h"
#include "YTQTMButton.h"
#include "YTSubscribeControlVisibilityDelegate-Protocol.h"
#include "YTSubscribeControlVisibilityProtocol-Protocol.h"

@class NSString;

@interface YTNotificationMultiToggleButton : YTQTMButton <YTPageStyling, YTHintViewAnchor, YTSubscribeControlVisibilityProtocol> {
    /* instance variables */
    YTIThemedBasicColorPalette *_basicColorPalette;
    long long _pageStyle;
}

@property (retain, nonatomic) YTColor *color;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <YTSubscribeControlVisibilityDelegate> visibilityDelegate;

/* class methods */
+ (id)button;

/* instance methods */
- (void)setRenderer:(id)renderer;
- (id)viewForHint;
- (void)setHidden:(_Bool)hidden;
- (void)setAlpha:(double)alpha;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })accessibilityFrame;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(id)superview;
- (void)pageStyleDidChange:(long long)change;
- (void)didUpdateVisibility;
- (void)setTintColorWithPageStyle:(long long)style;

@end

#endif /* YTNotificationMultiToggleButton_h */
