//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTOfflinePlaylistVideoListSectionController_h
#define YTOfflinePlaylistVideoListSectionController_h
@import Foundation;

#include "YTAppOfflinePlaylistController-Protocol.h"
#include "YTConnectionStatusController-Protocol.h"
#include "YTConnectionStatusControllerObserver-Protocol.h"
#include "YTDownloadedPlaylistModelEventObserver-Protocol.h"
#include "YTDownloadedVideoModelEventObserver-Protocol.h"
#include "YTIOfflinePlaylistVideoListRenderer.h"
#include "YTInnerTubeSectionController.h"
#include "YTVideoListPlaylistIDResponderProvider-Protocol.h"

@class NSString;

@interface YTOfflinePlaylistVideoListSectionController : YTInnerTubeSectionController <YTConnectionStatusControllerObserver, YTDownloadedPlaylistModelEventObserver, YTDownloadedVideoModelEventObserver, YTVideoListPlaylistIDResponderProvider> {
    /* instance variables */
    YTIOfflinePlaylistVideoListRenderer *_offlinePlaylistVideoListRenderer;
}

@property (weak, nonatomic) id <YTAppOfflinePlaylistController> appOfflinePlaylistController;
@property (weak, nonatomic) id <YTConnectionStatusController> connectionStatusController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)loadWithModel:(id)model;
- (void)collectionViewControllerWillAskForRefresh;
- (id)videoListPlaylistID;
- (void)didDeleteOfflineVideoWithID:(id)id pinTypes:(int)types;
- (void)didAddVideoToPlaylistID:(id)id;
- (void)didSaveMetadataWithPlaylistID:(id)id;
- (void)didDeleteVideoID:(id)id fromPlaylistID:(id)id;
- (void)connectionStatusDidChange:(_Bool)change;
- (void)queueOfflineRefreshIfConnected;

@end

#endif /* YTOfflinePlaylistVideoListSectionController_h */
