@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTOfflineGELEventControllerImpl_h
#define YTOfflineGELEventControllerImpl_h
@import Foundation;

#include "YTHotConfigObserver-Protocol.h"
#include "YTOfflineAppStateEventCenter.h"
#include "YTOfflineGELEventController-Protocol.h"

@class NSDate, NSObject, NSString;

@interface YTOfflineGELEventControllerImpl : NSObject <YTHotConfigObserver, YTOfflineGELEventController> {
    /* instance variables */
    NSString *_lastGELHeartbeatVideoID;
    NSDate *_lastGELHeartbeatTime;
    _Bool _enableLogPendingStateWithATQ;
    _Bool _enableLogPendingStateWithSuspended;
    _Bool _enableNewTransferLogging;
    YTOfflineAppStateEventCenter *_appStateController;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithColdConfig:(id)config hotConfig:(id)config;
- (id)init;
- (void)logAddedToOfflineQueueEventWithVideoID:(id)id;
- (void)logOffliningStartEventWithVideoID:(id)id transferFirstStarted:(_Bool)started;
- (void)logOffliningSuccessEventWithVideoID:(id)id fetchedKBytes:(unsigned long long)kbytes;
- (void)logOffliningPausedEventWithVideo:(id)video;
- (void)logOffliningFailedEventWithVideoID:(id)id failureReason:(int)reason;
- (void)logAdOffliningFailedEventWithVideoID:(id)id failureReason:(int)reason;
- (void)logOffliningFailedEventWithVideoID:(id)id failureReason:(int)reason failureExceptionType:(id)type;
- (void)logOffliningHeartbeatEventWithVideoID:(id)id fetchedKBytes:(unsigned long long)kbytes;
- (void)logOffliningSuspendedEventWithVideoID:(id)id pendingState:(unsigned int)state;
- (void)logOffliningSuspendedEventWithVideoID:(id)id;
- (void)logOffliningCancelledEventWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logOffliningRetriedEventWithVideoID:(id)id;
- (void)logOffliningRetryableFailureEventWithVideoID:(id)id failureReason:(int)reason;
- (void)logOffliningRetryableFailureEventWithVideoID:(id)id failureReason:(int)reason failureExceptionType:(id)type;
- (void)logOffliningDeletedEventWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)clearHeartbeat;
- (void)logTransferStatusEnqueuedWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logTransferStatusReenqueuedByUserResumeWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logTransferStatusReenqueuedByRetryWithVideoID:(id)id failureReason:(int)reason transferSnapshot:(id)snapshot;
- (void)logTransferStatusReenqueuedByPlayerResponseRefreshWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logTransferStatusPreprocessingWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logTransferStatusProcessingWithVideoID:(id)id transferFirstStarted:(_Bool)started transferSnapshot:(id)snapshot;
- (void)logTransferStatusCompletedWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logTransferStatusTerminatedWithFailureWithVideoID:(id)id failureReason:(int)reason transferSnapshot:(id)snapshot;
- (void)logTransferStatusTerminatedByUserWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logTransferStatusDequeuedByUserPauseWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logTransferStatusDequeuedByPlayerResponseExpirationWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logTransferStatusDeletedAfterCompletionWithVideoID:(id)id transferSnapshot:(id)snapshot;
- (void)logImageDownloadSuccess;
- (void)logImageDownloadSuccessWithAttempts:(long long)attempts isPinned:(_Bool)pinned dateAdded:(id)added hostDomain:(id)domain;
- (void)logImageDownloadFailureWithReason:(int)reason;
- (void)logImageDownloadFailureWithAttempts:(long long)attempts isPinned:(_Bool)pinned dateAdded:(id)added hostDomain:(id)domain failureReason:(int)reason;
- (void)hotConfigDidChange:(id)change;
- (id)createClientEventForVideoID:(id)id transferStatus:(int)status downloadContextEntity:(id)entity transferSnapshot:(id)snapshot;
- (void)logEventWithVideoID:(id)id transferStatus:(int)status transferSnapshot:(id)snapshot;
- (void)logEventWithVideoID:(id)id transferStatus:(int)status failureReason:(int)reason transferSnapshot:(id)snapshot;
- (void)logEventWithVideoID:(id)id transferStatus:(int)status transferFirstStarted:(_Bool)started transferSnapshot:(id)snapshot;
- (void)logEventWithVideoID:(id)id status:(int)status;
- (void)logEventWithVideoID:(id)id status:(int)status updateGELEventBlock:(id /* block */)block;
- (void)logOffliningFailedEventWithVideoID:(id)id forceIsAd:(_Bool)ad failureReason:(int)reason failureExceptionType:(id)type;
- (void)logEventWithVideoID:(id)id status:(int)status transferSnapshot:(id)snapshot updateGELEventBlock:(id /* block */)block;
- (id)getOfflineTransferStatusChangedWithVideoID:(id)id transferSnapshot:(id)snapshot downloadContextEntity:(id)entity status:(int)status;
- (void)sendLogEvent:(id)event fieldNumber:(int)number;
- (void)sendGelEvent:(id)event fieldNumber:(int)number;
- (void)sendFlowEvent:(id)event;
- (id)currentDate;
- (_Bool)shouldDropHeartbeatEventWithVideoID:(id)id;
- (void)fetchVideoDownloadContextEntityForEntityID:(id)id completionBlock:(id /* block */)block;

@end

#endif /* YTOfflineGELEventControllerImpl_h */
