  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTOfflinePlaybackDataEntityProvider_h
#define YTOfflinePlaybackDataEntityProvider_h
@import Foundation;

#include "YTEntityStoreObserver-Protocol.h"
#include "YTOfflineEntityProvider-Protocol.h"
#include "YTOfflineEntityProviderDelegate-Protocol.h"
#include "YTOfflineVideoControllerObserver-Protocol.h"
#include "YTPersistentEntityStore-Protocol.h"
#include "YTUserChangedObserver-Protocol.h"

@class NSObject, NSString;

@interface YTOfflinePlaybackDataEntityProvider : NSObject <YTOfflineVideoControllerObserver, YTEntityStoreObserver, YTUserChangedObserver, YTOfflineEntityProvider> {
    /* instance variables */
    id <YTPersistentEntityStore> _persistentEntityStore;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <YTOfflineEntityProviderDelegate> delegate;

/* class methods */
+ (id)entityKeyForEntityID:(id)id;
+ (void)getEntityForEntityID:(id)id identity:(id)identity callbackQueue:(id)queue completionBlock:(id /* block */)block;
+ (void)getEntitiesForEntityIDs:(id)ids identity:(id)identity callbackQueue:(id)queue completionBlock:(id /* block */)block;
+ (void)getEntitiesForIdentity:(id)identity callbackQueue:(id)queue completionBlock:(id /* block */)block;
+ (void)fetchEntitiesFromStoreWithEntityIDs:(id)ids identity:(id)identity persistentEntityStore:(id)store callbackQueue:(id)queue completionBlock:(id /* block */)block;
+ (void)fetchEntitiesFromLegacyStoreWithEntityIDs:(id)ids identity:(id)identity callbackQueue:(id)queue completionBlock:(id /* block */)block;
+ (void)fetchEntitiesFromLegacyStoreWithIdentity:(id)identity callbackQueue:(id)queue completionBlock:(id /* block */)block;
+ (id)entityKeysForEntityIDs:(id)ids entityType:(long long)type;

/* instance methods */
- (id)init;
- (void)notifyDelegateDidUpdateEntityWithID:(id)id;
- (void)didUpdateKey:(id)key inEntityStore:(id)store withUpdateType:(unsigned long long)type previousEntity:(id)entity entity:(id)entity;
- (void)reinitializeAndObservePersistentEntityStore;
- (id)persistentEntityStoreForCurrentUser;
- (void)didSaveOfflineVideoWithID:(id)id pinTypes:(int)types;
- (void)didDeleteOfflineVideoWithID:(id)id pinTypes:(int)types;
- (void)didDeleteAllOfflineVideosWithIDs:(id)ids;
- (void)didDeleteOfflineVideosForUserID:(id)id deletedVideoIDs:(id)ids;
- (void)didUpdateFromStatus:(int)status toStatus:(int)status forOfflineVideoWithID:(id)id;
- (void)didSavePlayerResponseWithVideoID:(id)id;

@end

#endif /* YTOfflinePlaybackDataEntityProvider_h */
