  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTOfflineCoordinator_h
#define YTOfflineCoordinator_h
@import Foundation;

#include "YTOfflineAdController-Protocol.h"
#include "YTOfflineAdPlaylistController-Protocol.h"
#include "YTOfflineConfig-Protocol.h"
#include "YTOfflineConfigDelegate-Protocol.h"
#include "YTOfflineModeProvider-Protocol.h"
#include "YTOfflinePlaylistController.h"
#include "YTOfflinePlaylistControllerObserver-Protocol.h"
#include "YTOfflineTracklistCaptionController-Protocol.h"
#include "YTOfflineVideoController.h"
#include "YTOfflineVideoControllerObserver-Protocol.h"
#include "YTOfflineVideoListController.h"
#include "YTReachabilityController-Protocol.h"
#include "YTReachabilityObserver-Protocol.h"

@class NSHashTable, NSObject, NSString;

@interface YTOfflineCoordinator : NSObject <YTReachabilityObserver, YTOfflineVideoControllerObserver, YTOfflinePlaylistControllerObserver, YTOfflineConfigDelegate, YTOfflineModeProvider> {
    /* instance variables */
    YTOfflineVideoController *_offlineVideoController;
    YTOfflinePlaylistController *_offlinePlaylistController;
    YTOfflineVideoListController *_offlineVideoListController;
    id <YTOfflineTracklistCaptionController> _offlineTracklistCaptionController;
    id <YTOfflineAdPlaylistController> _offlineAdPlaylistController;
    id <YTOfflineAdController> _offlineAdController;
    id <YTReachabilityController> _reachabilityController;
    _Bool _connected;
    int _connectionType;
    NSHashTable *_observers;
    NSHashTable *_offlineModeObservers;
    id <YTOfflineConfig> _offlineConfig;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) _Bool offlineMode;

/* instance methods */
- (id)initWithOfflineAdController:(id)controller offlineTracklistCaptionController:(id)controller reachabilityController:(id)controller;
- (id)init;
- (_Bool)isOfflineMode;
- (void)addOfflineCoordinatorObserver:(id)observer;
- (void)removeOfflineCoordinatorObserver:(id)observer;
- (void)setCurrentUserID:(id)id;
- (void)deleteOfflineContentForUserID:(id)id responseBlock:(id /* block */)block errorBlock:(id /* block */)block;
- (void)getUserIDsWithOfflineResourcesWithResponseBlock:(id /* block */)block errorBlock:(id /* block */)block;
- (_Bool)canOfflineOnCurrentNetwork;
- (_Bool)isWaitingForWiFi;
- (id)offlineConfig;
- (void)addOfflineModeObserver:(id)observer;
- (void)removeOfflineModeObserver:(id)observer;
- (void)reachabilityDidChange;
- (void)reachabilityCellRadioDidChange;
- (void)onlyOfflineOverWiFiDidChange;
- (void)notifyObserversCellRadioDidChange;
- (void)notifyObserversConnectionTypeDidChange;
- (void)notifyObserversOfflineDidChange;
- (void)notifyObserversOnlyOfflineOverWiFiDidChange;
- (void)notifyObserversOfflineUserDidChange;
- (void)fetchAllDeleteDRMLicenseEntityActionsWithResponseBlock:(id /* block */)block errorBlock:(id /* block */)block;
- (void)fetchAllDeleteLocalImageEntityActionsWithResponseBlock:(id /* block */)block errorBlock:(id /* block */)block;
- (void)fetchLocalImageEntitiesWithCompletionBlock:(id /* block */)block;
- (void)fetchAllDeletePdeEntityActionsWithResponseBlock:(id /* block */)block errorBlock:(id /* block */)block;
- (void)fetchPdeEntityKeysWithCompletionBlock:(id /* block */)block;
- (id)persistentEntityStoreForCurrentUser;

@end

#endif /* YTOfflineCoordinator_h */
