//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTPdgBuyFlowCommandHandler_h
#define YTPdgBuyFlowCommandHandler_h
@import Foundation;

#include "YTAccountScopedCommandHandler.h"
#include "YTPdgBuyFlowController.h"
#include "YTPdgBuyFlowService.h"
#include "YTPdgErrorReporter.h"

@interface YTPdgBuyFlowCommandHandler : YTAccountScopedCommandHandler {
    /* instance variables */
    YTPdgBuyFlowController *_pdgBuyFlowController;
    YTPdgBuyFlowService *_getPdgBuyFlowService;
    YTPdgErrorReporter *_pdgErrorReporter;
}

@property (readonly, nonatomic) YTPdgBuyFlowService *pdgBuyFlowService;

/* instance methods */
- (id)initWithAccountID:(id)id pdgBuyFlowController:(id)controller pdgBuyFlowService:(id)service pdgErrorReporter:(id)reporter;
- (id)initWithAccountID:(id)id;
- (void)executeWithCommand:(id)command entry:(id)entry fromView:(id)view sender:(id)sender;

@end

#endif /* YTPdgBuyFlowCommandHandler_h */
