@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTPhotoLibraryAlbumListCell_h
#define YTPhotoLibraryAlbumListCell_h
@import Foundation;

#include "YTCollectionViewCell.h"
#include "YTCollectionViewCellProtocol-Protocol.h"
#include "YTColorPalette-Protocol.h"
#include "YTPhotoLibraryAssetCollection.h"
#include "YTPhotoLibraryPickerConfiguration.h"
#include "YTResponder-Protocol.h"

@class NSString, PHAssetCollection, UIImage, UIImageView, UILabel;

@interface YTPhotoLibraryAlbumListCell : YTCollectionViewCell <YTCollectionViewCellProtocol> {
    /* instance variables */
    YTPhotoLibraryPickerConfiguration *_pickerConfiguration;
    PHAssetCollection *_album;
    UIImageView *_albumThumbnailImageView;
    UILabel *_albumInfoLabel;
    UILabel *_albumCountLabel;
    UIImage *_albumThumbnail;
    YTPhotoLibraryAssetCollection *_assetCollection;
    _Bool _isPresentedInCreationModes;
    id <YTColorPalette> _darkPalette;
}

@property (weak, nonatomic) id <YTResponder> parentResponder;
@property (nonatomic) _Bool isShowingInNonFullscreenModal;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (struct CGSize { double x0; double x1; })cellSizeForEntry:(id)entry size:(struct CGSize { double x0; double x1; })size;
+ (struct CGSize { double x0; double x1; })cellSizeForEntry:(id)entry size:(struct CGSize { double x0; double x1; })size safeAreaInsets:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })insets;
+ (struct CGSize { double x0; double x1; })cellSizeForOneGalleryWithSize:(struct CGSize { double x0; double x1; })size;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)setPickerConfiguration:(id)configuration;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(id)superview;
- (void)pageStyleDidChange:(long long)change;
- (void)setEntry:(id)entry;
- (id)entry;
- (void)setThumbnail:(id)thumbnail animated:(_Bool)animated;
- (void)setUpOSMediaPickerThumbnail;
- (struct CGSize { double x0; double x1; })thumbnailSize;
- (void)setUpEntryColors;
- (_Bool)shouldAllowShortsEngagementPanel;

@end

#endif /* YTPhotoLibraryAlbumListCell_h */
