  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTPlaybackTimelineManagerFactoryImpl_h
#define YTPlaybackTimelineManagerFactoryImpl_h
@import Foundation;

#include "YTPlaybackTimelineManagerFactory-Protocol.h"

@class NSObject, NSString;

@interface YTPlaybackTimelineManagerFactoryImpl : NSObject <YTPlaybackTimelineManagerFactory>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)playbackTimelineManagerWithTimeline:(id)timeline viewportSizeProvider:(id)provider recompositeProvider:(id)provider playerView:(id)view delegate:(id)delegate singleVideoSequencerDelegate:(id)delegate singleVideoControllerDelegate:(id)delegate mediaPlayerResources:(id)resources reloadContext:(id)context;
- (long long)playbackTimelineManagerTypeWithTimeline:(id)timeline reloadContext:(id)context;

@end

#endif /* YTPlaybackTimelineManagerFactoryImpl_h */
