//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTPlayerBarProgressDecorationView_h
#define YTPlayerBarProgressDecorationView_h
@import Foundation;

#include "YTBrandGradientView.h"
#include "YTColdConfig.h"
#include "YTIPlayerBarDecorationModel.h"
#include "YTPlayerBarDecorationProtocol-Protocol.h"

@class CAGradientLayer, NSString, UIColor, UIView;

@interface YTPlayerBarProgressDecorationView : UIView <YTPlayerBarDecorationProtocol> {
    /* instance variables */
    YTIPlayerBarDecorationModel *_model;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _playerBarFrame;
    CAGradientLayer *_progressBarGradientLayer;
    unsigned long long _playedProgressRoundedCorners;
    unsigned long long _downloadedProgressRoundedCorners;
    unsigned long long _unbufferedProgressRoundedCorners;
    YTColdConfig *_coldConfig;
    _Bool _isModernProgressBarEnabled;
    YTBrandGradientView *_brandGradient;
}

@property (retain, nonatomic) UIColor *playedProgressBarColor;
@property (nonatomic) _Bool enableRoundedCorners;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithModel:(id)model;
- (void)updateFrameWithPlayerBarFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)userIsScrubbingDidChange;
- (void)scrubberTimeDidChange;
- (void)updateVisibility;
- (void)setAnchorPoint;
- (void)setTransform;
- (void)drawRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)drawRoundedCornersLeftMaskRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)drawRoundedCornersEndMaskRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)drawUnbufferedProgressWithRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect withCutoutRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)drawDownloadedProgressWithRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (id)pathForRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect withUIRectCorner:(unsigned long long)corner;
- (_Bool)shouldApplyRoundedCorners:(unsigned long long)corners;
- (void)drawRectangleDecoration:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })decoration;
- (void)drawRectangleDecorationMonotone:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })monotone;
- (void)drawRectangleDecorationWithProgress:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })progress;
- (void)drawPlayingProgressBorder:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })border playingProgressWidth:(double)width;
- (void)drawGapMask;
- (_Bool)decorationHasElasticity;
- (_Bool)collectionStateIsHidden:(int)hidden;
- (void)applyGradientForRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (id)createSubGradientFromOverallBrandGradientFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame withVisibleArea:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })area;
- (void)drawProgressRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)drawProgressRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect withColor:(id)color;
- (_Bool)isStateActive;
- (_Bool)shouldApplyGradientColor;
- (_Bool)isScrubbingOver;
- (double)decorationXForPlayerBarFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (double)decorationWidthForPlayerBarFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;

@end

#endif /* YTPlayerBarProgressDecorationView_h */
