  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTPlayerBarScrubberDotDecorationView_h
#define YTPlayerBarScrubberDotDecorationView_h
@import Foundation;

#include "YTColdConfig.h"
#include "YTIPlayerBarDecorationModel.h"
#include "YTPlayerBarDecorationProtocol-Protocol.h"

@class NSString, UIImage, UIImageView, UIView;

@interface YTPlayerBarScrubberDotDecorationView : UIView <YTPlayerBarDecorationProtocol> {
    /* instance variables */
    UIView *_defaultScrubberDot;
    UIImageView *_customImageScrubberImageView;
    UIImage *_customImageScrubberIcon;
    YTIPlayerBarDecorationModel *_model;
    double _playerBarHeight;
    YTColdConfig *_coldConfig;
    _Bool _enableLargerCustomImageScrubber;
    double _customImageScrubberEnlargedScale;
    double _customImageScrubberDragEnlargedScale;
    _Bool _enableCustomScrubberMalformedUrlErrorHandlingFix;
}

@property (retain, nonatomic) UIView *scrubberDot;
@property (nonatomic) double enlargedScale;
@property (nonatomic) double dragEnlargedScale;
@property (nonatomic) long long scrubberDotDecorationScale;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithModel:(id)model;
- (void)layoutSubviews;
- (void)setScrubberEnlarged:(_Bool)enlarged;
- (void)setScrubberCircleHidden:(_Bool)hidden;
- (void)transformScrubberScale:(double)scale;
- (void)setPlayerBarHeight:(double)height;
- (void)setCustomImageScrubberIcon:(id)icon;
- (void)updateFrameWithPlayerBarFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)userIsScrubbingDidChange;
- (void)scrubberTimeDidChange;
- (void)updateVisibility;
- (void)setAnchorPoint;
- (void)setTransform;
- (void)updateScrubberDot;
- (id)expectedScrubberDot;

@end

#endif /* YTPlayerBarScrubberDotDecorationView_h */
