//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTResumeToHomeControllerImpl_h
#define YTResumeToHomeControllerImpl_h
@import Foundation;

#include "MDXServices-Protocol.h"
#include "MDXSessionManagerObserver-Protocol.h"
#include "MLPIPControllerObserver-Protocol.h"
#include "YTResumeToHomeController-Protocol.h"
#include "YTSystemNotificationsObserver-Protocol.h"

@class NSObject, NSString;

@interface YTResumeToHomeControllerImpl : NSObject <YTSystemNotificationsObserver, MLPIPControllerObserver, MDXSessionManagerObserver, YTResumeToHomeController> {
    /* instance variables */
    id <MDXServices> _MDXServices;
    _Bool _hasRegisteredMDXObserver;
}

@property (nonatomic) double resumeToHomeTimestamp;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)mdxServices;
- (void)setResumeToHomeTimestamp;
- (void)appDidEnterBackground;
- (void)appWillEnterForeground;
- (void)didStopPictureInPicture;
- (void)willStartPictureInPicture;
- (void)didStartPictureInPicture;
- (void)willStopPictureInPicture;
- (void)pictureInPictureFailedToStartWithError:(id)error;
- (void)pictureInPictureIsRestoringUserInterface;
- (void)pictureInPicturePlaybackPauseRequested;
- (void)pictureInPicturePlaybackResumeRequested;
- (void)pictureInPicturePlaybackRequestedSeekWithInterval:(struct { long long x0; int x1; unsigned int x2; long long x3; })interval;
- (void)pictureInPicturePlaybackReplayRequested;
- (void)pictureInPictureRequestedAdSkip;
- (void)MDXSessionManager:(id)manager didEndSession:(id)session withError:(id)error;

@end

#endif /* YTResumeToHomeControllerImpl_h */
