  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTSettingsPickerView_h
#define YTSettingsPickerView_h
@import Foundation;

#include "UIPickerViewDataSource-Protocol.h"
#include "UIPickerViewDelegate-Protocol.h"
#include "YTImpactFeedbackGenerator-Protocol.h"
#include "YTPageStyling-Protocol.h"
#include "YTSettingsPickerTitleView.h"
#include "YTSettingsPickerViewDelegate-Protocol.h"
#include "YTSettingsPickerViewMenuViewModel-Protocol.h"

@class NSArray, NSString, UIPickerView, UIView;

@interface YTSettingsPickerView : UIView <UIPickerViewDataSource, UIPickerViewDelegate, YTPageStyling> {
    /* instance variables */
    id <YTSettingsPickerViewMenuViewModel> _startMenu;
    id <YTSettingsPickerViewMenuViewModel> _endMenu;
    long long _pageStyle;
}

@property (retain, nonatomic) UIPickerView *startPickerView;
@property (retain, nonatomic) UIPickerView *endPickerView;
@property (retain, nonatomic) YTSettingsPickerTitleView *startPickerTitleView;
@property (retain, nonatomic) YTSettingsPickerTitleView *endPickerTitleView;
@property (retain, nonatomic) UIView *startContainerView;
@property (retain, nonatomic) UIView *endContainerView;
@property (retain, nonatomic) id <YTImpactFeedbackGenerator> feedbackGenerator;
@property (weak, nonatomic) id <YTSettingsPickerViewDelegate> delegate;
@property (readonly, nonatomic) NSArray *menus;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithMenus:(id)menus;
- (long long)selectedOptionIndexForMenu:(id)menu;
- (void)layoutSubviews;
- (void)didMoveToSuperview;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)updateWithEndMenu:(id)menu;
- (long long)numberOfComponentsInPickerView:(id)view;
- (long long)pickerView:(id)view numberOfRowsInComponent:(long long)component;
- (id)pickerView:(id)view attributedTitleForRow:(long long)row forComponent:(long long)component;
- (void)pickerView:(id)view didSelectRow:(long long)row inComponent:(long long)component;
- (void)didSelectStartRowView;
- (void)didSelectEndRowView;
- (void)pickerSelectionChanged;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(id)superview;
- (void)pageStyleDidChange:(long long)change;
- (void)updateStartPickerSelection;
- (void)updateEndPickerSelection;

@end

#endif /* YTSettingsPickerView_h */
