        @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
        @protocol NSObject, NSCopying, NSCoding;
@interface YTSettingsSectionItem : NSObject <YTSettingsItemViewModel, YTResponder> {
    /* instance variables */
    YTVisualElement *_proxyButton;
    _Bool _proxyButtonShown;
    _Bool _hasCheckmark;
    _Bool _hasSwitch;
    _Bool _on;
    _Bool _enabled;
    _Bool _switchVisible;
    _Bool _spinnerVisible;
    _Bool _inkEnabled;
    int _indicatorIconType;
    int _settingItemId;
    int _veType;
    id <YTResponder> _parentResponder;
    NSNumber *_categoryId;
    NSString *_title;
    NSString *_titleDescription;
    YTIFormattedString *_formattedSettingSummary;
    id /* block */ _titleDescriptionBlock;
    NSString *_accessibilityIdentifier;
    id /* block */ _detailTextBlock;
    id /* block */ _itemEnabledBlock;
    GPBMessage *_model;
    id /* block */ _selectBlock;
    id /* block */ _disabledSelectBlock;
    id /* block */ _switchBlock;
    YTIThumbnailDetails *_settingThumbnailImageDetails;
    YTIIcon *_settingIcon;
    NSData *_trackingParams;
    YTIButtonRenderer *_buttonRenderer;
}

@property (retain, nonatomic) NSNumber *categoryId;
@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSString *titleDescription;
@property (retain, nonatomic) YTIFormattedString *formattedSettingSummary;
@property (copy, nonatomic) id /* block */ titleDescriptionBlock;
@property (copy, nonatomic) NSString *accessibilityIdentifier;
@property (copy, nonatomic) id /* block */ detailTextBlock;
@property (nonatomic) _Bool hasCheckmark;
@property (nonatomic) _Bool hasSwitch;
@property (nonatomic) _Bool on;
@property (nonatomic) _Bool enabled;
@property (copy, nonatomic) id /* block */ itemEnabledBlock;
@property (nonatomic) _Bool switchVisible;
@property (nonatomic) _Bool spinnerVisible;
@property (nonatomic) int indicatorIconType;
@property (retain, nonatomic) GPBMessage *model;
@property (copy, nonatomic) id /* block */ selectBlock;
@property (copy, nonatomic) id /* block */ disabledSelectBlock;
@property (copy, nonatomic) id /* block */ switchBlock;
@property (nonatomic) int settingItemId;
@property (retain, nonatomic) YTIThumbnailDetails *settingThumbnailImageDetails;
@property (retain, nonatomic) YTIIcon *settingIcon;
@property (copy, nonatomic) NSData *trackingParams;
@property (nonatomic) int veType;
@property (nonatomic) _Bool inkEnabled;
@property (retain, nonatomic) YTIButtonRenderer *buttonRenderer;
@property (readonly, nonatomic) Class cellClass;
@property (retain, nonatomic) NSString *settingTitle;
@property (retain, nonatomic) NSString *settingSummary;
@property (nonatomic) _Bool settingEnabled;
@property (readonly, nonatomic) NSString *settingDetailText;
@property (readonly, nonatomic) NSString *settingMessageWhenDisabled;
@property (readonly, nonatomic) _Bool hasSubSettingsRenderer;
@property (readonly, nonatomic) YTIRenderer *subSettingsRenderer;
@property (readonly, nonatomic) YTICommand *enableSettingCommand;
@property (readonly, nonatomic) YTICommand *disableSettingCommand;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, weak, nonatomic) id <YTResponder> parentResponder;

/* class methods */
+ (id)itemWithTitle:(id)title titleDescription:(id)description trackingParams:(id)params accessibilityIdentifier:(id)identifier detailTextBlock:(id /* block */)block selectBlock:(id /* block */)block parentResponder:(id)responder;
+ (id)itemWithTitle:(id)title titleDescription:(id)description trackingParams:(id)params accessibilityIdentifier:(id)identifier detailTextBlock:(id /* block */)block selectBlock:(id /* block */)block;
+ (id)itemWithTitle:(id)title titleDescription:(id)description accessibilityIdentifier:(id)identifier detailTextBlock:(id /* block */)block selectBlock:(id /* block */)block;
+ (id)itemWithTitle:(id)title accessibilityIdentifier:(id)identifier detailTextBlock:(id /* block */)block selectBlock:(id /* block */)block;
+ (id)itemWithTitle:(id)title formattedTitleDescription:(id)description trackingParams:(id)params accessibilityIdentifier:(id)identifier detailTextBlock:(id /* block */)block selectBlock:(id /* block */)block parentResponder:(id)responder;
+ (id)itemWithTitle:(id)title formattedTitleDescription:(id)description accessibilityIdentifier:(id)identifier detailTextBlock:(id /* block */)block selectBlock:(id /* block */)block;
+ (id)eomDisclaimerItemWithDetailedTextBlock:(id /* block */)block icon:(id)icon buttonRenderer:(id)renderer accessibilityIdentifier:(id)identifier settingItemId:(int)id parentResponder:(id)responder;
+ (id)checkmarkItemWithTitle:(id)title titleDescription:(id)description selectBlock:(id /* block */)block;
+ (id)checkmarkItemWithTitle:(id)title titleDescription:(id)description selectBlock:(id /* block */)block disabledSelectBlock:(id /* block */)block;
+ (id)checkmarkItemWithTitle:(id)title selectBlock:(id /* block */)block;
+ (id)switchItemWithTitle:(id)title titleDescription:(id)description accessibilityIdentifier:(id)identifier switchOn:(_Bool)on switchBlock:(id /* block */)block;
+ (id)switchItemWithTitle:(id)title titleDescription:(id)description accessibilityIdentifier:(id)identifier switchOn:(_Bool)on switchBlock:(id /* block */)block settingItemId:(int)id;
+ (id)switchItemWithTitle:(id)title titleDescription:(id)description accessibilityIdentifier:(id)identifier switchOn:(_Bool)on confirmationRequiredToEnable:(_Bool)enable confirmationRequiredToDisable:(_Bool)disable switchBlock:(id /* block */)block settingItemId:(int)id parentResponder:(id)responder;
+ (id)switchItemWithTitle:(id)title formattedTitleDescription:(id)description accessibilityIdentifier:(id)identifier switchOn:(_Bool)on confirmationRequiredToEnable:(_Bool)enable confirmationRequiredToDisable:(_Bool)disable switchBlock:(id /* block */)block settingItemId:(int)id parentResponder:(id)responder;
+ (id)switchItemWithTitle:(id)title titleDescription:(id)description accessibilityIdentifier:(id)identifier switchOn:(_Bool)on switchBlock:(id /* block */)block selectBlock:(id /* block */)block settingItemId:(int)id;
+ (id)switchItemWithTitle:(id)title switchOn:(_Bool)on switchBlock:(id /* block */)block;
+ (id)switchItemWithTitle:(id)title switchOn:(_Bool)on veType:(int)type parentResponder:(id)responder switchBlock:(id /* block */)block;
+ (id)switchItemWithTitle:(id)title titleDescriptionBlock:(id /* block */)block accessibilityIdentifier:(id)identifier switchOn:(_Bool)on switchBlock:(id /* block */)block settingItemId:(int)id parentResponder:(id)responder;
+ (id)lockableSwitchItemWithTitle:(id)title titleDescription:(id)description accessibilityIdentifier:(id)identifier switchOn:(_Bool)on locked:(_Bool)locked settingItemId:(int)id switchBlock:(id /* block */)block selectBlock:(id /* block */)block disabledSelectBlock:(id /* block */)block;

/* instance methods */
- (id)initWithTitle:(id)title titleDescription:(id)description parentResponder:(id)responder;
- (id)initWithTitle:(id)title titleDescription:(id)description;
- (void)setServerSideSwitch:(unsigned long long)_switch;
- (void)setVeType:(int)type;
- (void)itemAddedToSettingsPage;
- (void)itemShownOnSettingsPage;
- (void)logItemTapped;
- (Class)cellClass;
- (id)settingTitle;
- (void)setSettingTitle:(id)title;
- (id)settingSummary;
- (void)setSettingSummary:(id)summary;
- (_Bool)settingEnabled;
- (void)setSettingEnabled:(_Bool)enabled;
- (id)settingDetailText;
- (id)parentResponder;
- (id)categoryId;
- (void)setCategoryId:(id)id;
- (id)title;
- (void)setTitle:(id)title;
- (id)titleDescription;
- (void)setTitleDescription:(id)description;
- (id)formattedSettingSummary;
- (void)setFormattedSettingSummary:(id)summary;
- (id /* block */)titleDescriptionBlock;
- (void)setTitleDescriptionBlock:(id /* block */)block;
- (id)accessibilityIdentifier;
- (void)setAccessibilityIdentifier:(id)identifier;
- (id /* block */)detailTextBlock;
- (void)setDetailTextBlock:(id /* block */)block;
- (_Bool)hasCheckmark;
- (void)setHasCheckmark:(_Bool)checkmark;
- (_Bool)hasSwitch;
- (void)setHasSwitch:(_Bool)_switch;
- (_Bool)on;
- (void)setOn:(_Bool)on;
- (_Bool)enabled;
- (void)setEnabled:(_Bool)enabled;
- (id /* block */)itemEnabledBlock;
- (void)setItemEnabledBlock:(id /* block */)block;
- (_Bool)switchVisible;
- (void)setSwitchVisible:(_Bool)visible;
- (_Bool)spinnerVisible;
- (void)setSpinnerVisible:(_Bool)visible;
- (int)indicatorIconType;
- (void)setIndicatorIconType:(int)type;
- (id)model;
- (void)setModel:(id)model;
- (id /* block */)selectBlock;
- (void)setSelectBlock:(id /* block */)block;
- (id /* block */)disabledSelectBlock;
- (void)setDisabledSelectBlock:(id /* block */)block;
- (id /* block */)switchBlock;
- (void)setSwitchBlock:(id /* block */)block;
- (int)settingItemId;
- (void)setSettingItemId:(int)id;
- (id)settingThumbnailImageDetails;
- (void)setSettingThumbnailImageDetails:(id)details;
- (id)settingIcon;
- (void)setSettingIcon:(id)icon;
- (id)trackingParams;
- (void)setTrackingParams:(id)params;
- (int)veType;
- (_Bool)isInkEnabled;
- (void)setInkEnabled:(_Bool)enabled;
- (id)buttonRenderer;
- (void)setButtonRenderer:(id)renderer;

@end

@interface YTSettingsSectionItemManager : NSObject <YTBedtimeReminderSettingsControllerDelegate, YTAppSettingsStoreObserver, YTSheetControllerDelegate, YTUserDefaultsObserver, OSSLicensesViewControllerDelegate, YTResponder> {
    /* instance variables */
    id <YTAppSettingsSectionItemControllerDelegate> _controllerDelegate;
    id <YTAppSettingsSectionItemDataDelegate> _dataDelegate;
    id <YTAppSettingsViewControllerDelegate> _settingsViewControllerDelegate;
    YTAppSettingsSectionItemController *_sectionItemController;
    YTHotConfig *_hotConfig;
    YTIdentityController *_identityController;
    YTVisualElement *_pipToggleProxyButton;
    YTVisualElement *_autoplayToggleProxyButton;
    YTVisualElement *_bedtimeReminderToggleProxyButton;
    YTVisualElement *_bedtimeReminderConfirmEnabledProxyButton;
    YTVisualElement *_watchBreakReminderToggleProxyButton;
    YTVisualElement *_appLanguageProxyButton;
    YTVisualElement *_appLanguageProxyToast;
    YTVisualElement *_rotationSettingToggleProxyButton;
    NSMutableArray *_attachedElements;
    unsigned long long _smartDownloadsUsageBytes;
    unsigned long long _freeStorageBytes;
    _Bool _didTurnOnSmartDownloads;
    YTUserDefaults *_userDefaults;
    id <YTIdentityProvider> _identityProvider;
    _Bool _enableServerMigration;
    _Bool _enablePlaybackAreaSettingTopOfGeneral;
    _Bool _enableAutoplayToggleLogging;
    _Bool _enableBedtimeReminderRedesignLogging;
    _Bool _enableBreakReminderLoggingUpdates;
    _Bool _enableQualitySettingsWithHighQualityAudio;
    _Bool _enableTimeManagementConsolidation;
    _Bool _enableHighQualityAudioPremiumUpsell;
    _Bool _timeManagementSectionHasBeenDisplayed;
    YTIElementRenderer *_receivedBreakReminderRenderer;
    id <YTRemindersController> _remindersController;
    id <YTRemindersSettingsResolver> _settingsResolver;
    _Bool _useResolver;
    _Bool _languageCateroryEnabled;
    id <YTFeatureGatesClient> _accountFeatureGatesClient;
    id <YTResponder> _parentResponder;
    YTBedtimeReminderSettingsController *_bedtimeReminderSettingsController;
    YTAppSettingsStore *_appSettingsStore;
}

@property (retain, nonatomic) YTBedtimeReminderSettingsController *bedtimeReminderSettingsController;
@property (retain, nonatomic) YTAppSettingsStore *appSettingsStore;
@property (readonly, nonatomic) _Bool watchBreakEnabled;
@property (readonly, nonatomic) _Bool bedtimeReminderEnabled;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, weak, nonatomic) id <YTResponder> parentResponder;

/* instance methods */
- (id)initWithParentResponder:(id)responder controllerDelegate:(id)delegate dataDelegate:(id)delegate settingsViewControllerDelegate:(id)delegate;
- (void)updateSectionForCategory:(unsigned long long)category withEntry:(id)entry;
- (void)updateTimeManagementSectionWithEntry:(id)entry;
- (void)updateUnlimitedSectionWithEntry:(id)entry;
- (void)updateSubscriptionProductsSectionWithEntry:(id)entry;
- (void)updateMainSectionWithEntry:(id)entry;
- (void)updateAutoplaySectionWithEntry:(id)entry;
- (void)updateVideoQualitySectionWithEntry:(id)entry;
- (_Bool)shouldShowUpdatedQualitySettings:(id)settings;
- (void)updateQualitySectionWithEntry:(id)entry;
- (void)updateNotificationSectionWithEntry:(id)entry;
- (void)updateHistorySectionWithEntry:(id)entry;
- (void)updatePrivacySectionWithEntry:(id)entry;
- (void)updateHistoryAndPrivacySectionWithEntry:(id)entry;
- (void)updateYourDataSectionWithEntry:(id)entry;
- (void)updateAccountSwitcherSectionWithEntry:(id)entry;
- (void)showConfirmDialogForRenderer:(id)renderer fromView:(id)view;
- (void)updateCategorySectionForCategory:(unsigned long long)category withEntry:(id)entry additionalSectionItems:(id)items;
- (void)updateOfflineSectionWithEntry:(id)entry;
- (void)updateSmartDownloadsSectionWithEntry:(id)entry;
- (void)createUploadSection;
- (void)updateLiveChatSectionWithEntry:(id)entry;
- (void)updatePremiumEarlyAccessSectionWithEntry:(id)entry;
- (void)updateGamingThirdPartySectionWithEntry:(id)entry;
- (void)createAboutSection;
- (void)updateUnpluggedSectionWithEntry:(id)entry;
- (void)updateParentSettingsSectionWithEntry:(id)entry;
- (void)attachAndUpdateVisibilityToVisualElement:(id)element;
- (void)logToggleInteractionForVisualElement:(id)element switchOn:(_Bool)on;
- (void)updateSettingsItemWithId:(int)id;
- (void)updateNavigationEndpointCategoryEntryWithCategory:(unsigned long long)category withEntry:(id)entry;
- (void)createWatchOnTvSection;
- (void)updateLanguagesSectionWithEntry:(id)entry;
- (id)sectionSettingItemFromSettingReadOnlyItemRenderer:(id)renderer;
- (void)updatePlaybackSectionWithEntry:(id)entry;
- (void)updateHelpSectionWithEntry:(id)entry;
- (void)updateSendFeedbackSectionWithEntry:(id)entry;
- (void)updateTermsOfServiceSectionWithEntry:(id)entry;
- (id)zoomToFillScreenSectionItem;
- (id)seekPlayerOptionSectionItem;
- (id)playbackInFeedsSectionItem;
- (id)helpSectionItem;
- (id)sendFeedbackSectionItem;
- (id)termsOfServiceSectionItem;
- (id)autoplaySectionItemFromCollectionRenderer:(id)renderer;
- (_Bool)restrictedModeOn:(id)on;
- (void)updateIMPTitleDescription:(id)description;
- (id)settings;
- (id)appThemeSettingsSectionItem;
- (id)orientationSettingsSectionItem;
- (id)appLanguageSectionItem;
- (id)pictureInPictureSectionItem:(id)item;
- (id)i18nPlaybackAreaSettingItemWithEntry:(id)entry;
- (id)homeLocationSettingItemWithEntry:(id)entry;
- (id)safetyModeSettingsItemWithEntry:(id)entry;
- (id)booleanRendererFromCollectionRenderer:(id)renderer withClientSettingItem:(int)item;
- (id)booleanRendererFromCollectionRenderer:(id)renderer withClientSettingItemId:(int)id;
- (id)actionRendererFromCollectionRenderer:(id)renderer withClientSettingItem:(int)item;
- (id)playbackAnnotationSettingsItemWithEntry:(id)entry;
- (id)watchOnTvSectionItem;
- (id)accountBadgesSettingsItemWithEntry:(id)entry;
- (id)readonlyItemRendererFromCollectionRenderer:(id)renderer withSettingItemId:(int)id;
- (id)crowdsourcedContextContributorSettingsItemWithEntry:(id)entry;
- (id)booleanRendererFromCollectionRenderer:(id)renderer withSettingItemId:(int)id;
- (id)accessibilityIdentifierForSettingRenderer:(id)renderer;
- (id)enumNameForSettingItemID:(int)id;
- (_Bool)switchIsOnForSetting:(int)setting;
- (id)termsOfServiceURL;
- (id)siriShortcutsSettingsSectionItemWithTitle:(id)title;
- (id)offlineSettingsVideoQualityPickerWithItemEnabledBlock:(id /* block */)block;
- (id)disabledShortsSmartDownloadsSettingsSectionItem;
- (id)smartDownloadsSettingsVideoQualityPickerWithRenderer:(id)renderer;
- (id)smartDownloadsSettingsSwitchWithUsageText:(_Bool)text smartDownloadsEntrypoint:(id)entrypoint;
- (id)smartDownloadsSettingsSectionItemWithInlinedToggleExperience:(_Bool)experience;
- (id)smartDownloadsSettingsSectionItem;
- (id)getShortsDailyTimerBooleanRendererFromEntry:(id)entry;
- (void)updateShortsDailyTimerLocalSettingsWithSettingBooleanRenderer:(id)renderer;
- (id)shortsDailyTimerSettingsSectionItemFromSettingBooleanRenderer:(id)renderer;
- (void)showShortsDailyTimerSettingsBottomSheet:(id)sheet;
- (void)shortsDailyTimerActionWhenLockedByParent:(id)parent;
- (id)watchBreakSettingsSectionItem;
- (void)showLockedByParentToast;
- (void)showWatchBreakSettingsCustomPicker;
- (_Bool)watchBreakEnabled;
- (id)watchBreakSettingsDetails;
- (id)navEndpointForActionSheet:(id)sheet;
- (void)attachVEContentsForActionSheet:(id)sheet;
- (void)actionSheetDidDisappear:(id)disappear;
- (id)bedtimeReminderSettingsController;
- (id)bedtimeReminderSettingsSectionItem;
- (void)showBedtimeReminderSettingsPicker;
- (id)bedtimeReminderTitleDescription;
- (_Bool)bedtimeReminderEnabled;
- (void)setBedtimeReminderEnabled:(_Bool)enabled;
- (void)setBedtimeReminderEnabled:(_Bool)enabled animated:(_Bool)animated;
- (void)didTapConfirmEnableBedtimeReminderButton;
- (void)appSettingsStore:(id)store didChangeSetting:(int)setting fromValue:(id)value toValue:(id)value;
- (void)valueDidChangeForKey:(id)key;
- (void)loadCurrentSDUsageAndFreeDiskSpace;
- (void)navigateToViewController:(id)controller;
- (id)parentResponder;
- (void)setBedtimeReminderSettingsController:(id)controller;
- (id)appSettingsStore;
- (void)setAppSettingsStore:(id)store;

@end

