  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTSearchBoxView_h
#define YTSearchBoxView_h
@import Foundation;

#include "FLXLayout.h"
#include "GIPInputShieldView.h"
#include "UITextFieldDelegate-Protocol.h"
#include "YTColor.h"
#include "YTFontAttributes.h"
#include "YTISearchBoxRenderer.h"
#include "YTPageStyling-Protocol.h"
#include "YTQTMButton.h"
#include "YTSearchBoxTextField.h"
#include "YTSearchBoxTextFieldWithFontAttributes.h"
#include "YTSearchBoxViewDelegate-Protocol.h"
#include "YTSizableView.h"

@class NSString, UIView;

@interface YTSearchBoxView : UIView <UITextFieldDelegate, YTPageStyling> {
    /* instance variables */
    YTQTMButton *_searchButton;
    YTISearchBoxRenderer *_entry;
    FLXLayout *_layout;
    GIPInputShieldView *_dimView;
    UIView *_contentView;
    _Bool _shouldShowCancelButton;
    _Bool _forceShowCancelButton;
    _Bool _shouldSearchOnEditing;
    _Bool _shouldPersistSearchOnEndEditing;
    _Bool _shouldDismissKeyboardWhenTapSearchButton;
    YTQTMButton *_cancelButton;
    YTFontAttributes *attributes;
    YTColor *placeholderTextColor;
}

@property (retain, nonatomic) YTSearchBoxTextField *searchLabel;
@property (retain, nonatomic) YTSearchBoxTextFieldWithFontAttributes *searchLabelWithFontAttributes;
@property (retain, nonatomic) YTSizableView *cancelButtonContainer;
@property (weak, nonatomic) id <YTSearchBoxViewDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)setEntry:(id)entry;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (id)hitTest:(struct CGPoint { double x0; double x1; })test withEvent:(id)event;
- (void)dismissKeyboard;
- (void)textFieldDidBeginEditing:(id)editing;
- (void)textFieldDidEndEditing:(id)editing;
- (_Bool)textFieldShouldReturn:(id)_return;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(id)superview;
- (void)pageStyleDidChange:(long long)change;
- (id)root;
- (void)didTapDimView;
- (void)gainFocus;
- (void)loseFocus;
- (void)didTapSearchButton;
- (void)didSearch;
- (void)didTapCancelButton;
- (void)showCancelButtonAnimated:(_Bool)animated;
- (void)hideCancelButtonAnimated:(_Bool)animated;
- (void)resetSearchLabel;

@end

#endif /* YTSearchBoxView_h */
