@interface YTSettingsSectionItemManager : NSObject <YTBedtimeReminderSettingsControllerDelegate, YTAppSettingsStoreObserver, YTSheetControllerDelegate, YTUserDefaultsObserver, OSSLicensesViewControllerDelegate, YTResponder> {
    /* instance variables */
    id <YTAppSettingsSectionItemControllerDelegate> _controllerDelegate;
    id <YTAppSettingsSectionItemDataDelegate> _dataDelegate;
    id <YTAppSettingsViewControllerDelegate> _settingsViewControllerDelegate;
    YTAppSettingsSectionItemController *_sectionItemController;
    YTHotConfig *_hotConfig;
    YTIdentityController *_identityController;
    YTVisualElement *_pipToggleProxyButton;
    YTVisualElement *_autoplayToggleProxyButton;
    YTVisualElement *_bedtimeReminderToggleProxyButton;
    YTVisualElement *_bedtimeReminderConfirmEnabledProxyButton;
    YTVisualElement *_watchBreakReminderToggleProxyButton;
    YTVisualElement *_appLanguageProxyButton;
    YTVisualElement *_appLanguageProxyToast;
    YTVisualElement *_rotationSettingToggleProxyButton;
    NSMutableArray *_attachedElements;
    unsigned long long _smartDownloadsUsageBytes;
    unsigned long long _freeStorageBytes;
    _Bool _didTurnOnSmartDownloads;
    YTUserDefaults *_userDefaults;
    id <YTIdentityProvider> _identityProvider;
    _Bool _enableServerMigration;
    _Bool _enablePlaybackAreaSettingTopOfGeneral;
    _Bool _enableAutoplayToggleLogging;
    _Bool _enableBedtimeReminderRedesignLogging;
    _Bool _enableBreakReminderLoggingUpdates;
    _Bool _enableQualitySettingsWithHighQualityAudio;
    _Bool _enableTimeManagementConsolidation;
    _Bool _enableHighQualityAudioPremiumUpsell;
    _Bool _timeManagementSectionHasBeenDisplayed;
    YTIElementRenderer *_receivedBreakReminderRenderer;
    id <YTRemindersController> _remindersController;
    id <YTRemindersSettingsResolver> _settingsResolver;
    _Bool _useResolver;
    _Bool _languageCateroryEnabled;
    id <YTFeatureGatesClient> _accountFeatureGatesClient;
    id <YTResponder> _parentResponder;
    YTBedtimeReminderSettingsController *_bedtimeReminderSettingsController;
    YTAppSettingsStore *_appSettingsStore;
}

@property (retain, nonatomic) YTBedtimeReminderSettingsController *bedtimeReminderSettingsController;
@property (retain, nonatomic) YTAppSettingsStore *appSettingsStore;
@property (readonly, nonatomic) _Bool watchBreakEnabled;
@property (readonly, nonatomic) _Bool bedtimeReminderEnabled;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, weak, nonatomic) id <YTResponder> parentResponder;

/* instance methods */
- (id)initWithParentResponder:(id)responder controllerDelegate:(id)delegate dataDelegate:(id)delegate settingsViewControllerDelegate:(id)delegate;
- (void)updateSectionForCategory:(unsigned long long)category withEntry:(id)entry;
- (void)updateTimeManagementSectionWithEntry:(id)entry;
- (void)updateUnlimitedSectionWithEntry:(id)entry;
- (void)updateSubscriptionProductsSectionWithEntry:(id)entry;
- (void)updateMainSectionWithEntry:(id)entry;
- (void)updateAutoplaySectionWithEntry:(id)entry;
- (void)updateVideoQualitySectionWithEntry:(id)entry;
- (_Bool)shouldShowUpdatedQualitySettings:(id)settings;
- (void)updateQualitySectionWithEntry:(id)entry;
- (void)updateNotificationSectionWithEntry:(id)entry;
- (void)updateHistorySectionWithEntry:(id)entry;
- (void)updatePrivacySectionWithEntry:(id)entry;
- (void)updateHistoryAndPrivacySectionWithEntry:(id)entry;
- (void)updateYourDataSectionWithEntry:(id)entry;
- (void)updateAccountSwitcherSectionWithEntry:(id)entry;
- (void)showConfirmDialogForRenderer:(id)renderer fromView:(id)view;
- (void)updateCategorySectionForCategory:(unsigned long long)category withEntry:(id)entry additionalSectionItems:(id)items;
- (void)updateOfflineSectionWithEntry:(id)entry;
- (void)updateSmartDownloadsSectionWithEntry:(id)entry;
- (void)createUploadSection;
- (void)updateLiveChatSectionWithEntry:(id)entry;
- (void)updatePremiumEarlyAccessSectionWithEntry:(id)entry;
- (void)updateGamingThirdPartySectionWithEntry:(id)entry;
- (void)createAboutSection;
- (void)updateUnpluggedSectionWithEntry:(id)entry;
- (void)updateParentSettingsSectionWithEntry:(id)entry;
- (void)attachAndUpdateVisibilityToVisualElement:(id)element;
- (void)logToggleInteractionForVisualElement:(id)element switchOn:(_Bool)on;
- (void)updateSettingsItemWithId:(int)id;
- (void)updateNavigationEndpointCategoryEntryWithCategory:(unsigned long long)category withEntry:(id)entry;
- (void)createWatchOnTvSection;
- (void)updateLanguagesSectionWithEntry:(id)entry;
- (id)sectionSettingItemFromSettingReadOnlyItemRenderer:(id)renderer;
- (void)updatePlaybackSectionWithEntry:(id)entry;
- (void)updateHelpSectionWithEntry:(id)entry;
- (void)updateSendFeedbackSectionWithEntry:(id)entry;
- (void)updateTermsOfServiceSectionWithEntry:(id)entry;
- (id)zoomToFillScreenSectionItem;
- (id)seekPlayerOptionSectionItem;
- (id)playbackInFeedsSectionItem;
- (id)helpSectionItem;
- (id)sendFeedbackSectionItem;
- (id)termsOfServiceSectionItem;
- (id)autoplaySectionItemFromCollectionRenderer:(id)renderer;
- (_Bool)restrictedModeOn:(id)on;
- (void)updateIMPTitleDescription:(id)description;
- (id)settings;
- (id)appThemeSettingsSectionItem;
- (id)orientationSettingsSectionItem;
- (id)appLanguageSectionItem;
- (id)pictureInPictureSectionItem:(id)item;
- (id)i18nPlaybackAreaSettingItemWithEntry:(id)entry;
- (id)homeLocationSettingItemWithEntry:(id)entry;
- (id)safetyModeSettingsItemWithEntry:(id)entry;
- (id)booleanRendererFromCollectionRenderer:(id)renderer withClientSettingItem:(int)item;
- (id)booleanRendererFromCollectionRenderer:(id)renderer withClientSettingItemId:(int)id;
- (id)actionRendererFromCollectionRenderer:(id)renderer withClientSettingItem:(int)item;
- (id)playbackAnnotationSettingsItemWithEntry:(id)entry;
- (id)watchOnTvSectionItem;
- (id)accountBadgesSettingsItemWithEntry:(id)entry;
- (id)readonlyItemRendererFromCollectionRenderer:(id)renderer withSettingItemId:(int)id;
- (id)crowdsourcedContextContributorSettingsItemWithEntry:(id)entry;
- (id)booleanRendererFromCollectionRenderer:(id)renderer withSettingItemId:(int)id;
- (id)accessibilityIdentifierForSettingRenderer:(id)renderer;
- (id)enumNameForSettingItemID:(int)id;
- (_Bool)switchIsOnForSetting:(int)setting;
- (id)termsOfServiceURL;
- (id)siriShortcutsSettingsSectionItemWithTitle:(id)title;
- (id)offlineSettingsVideoQualityPickerWithItemEnabledBlock:(id /* block */)block;
- (id)disabledShortsSmartDownloadsSettingsSectionItem;
- (id)smartDownloadsSettingsVideoQualityPickerWithRenderer:(id)renderer;
- (id)smartDownloadsSettingsSwitchWithUsageText:(_Bool)text smartDownloadsEntrypoint:(id)entrypoint;
- (id)smartDownloadsSettingsSectionItemWithInlinedToggleExperience:(_Bool)experience;
- (id)smartDownloadsSettingsSectionItem;
- (id)getShortsDailyTimerBooleanRendererFromEntry:(id)entry;
- (void)updateShortsDailyTimerLocalSettingsWithSettingBooleanRenderer:(id)renderer;
- (id)shortsDailyTimerSettingsSectionItemFromSettingBooleanRenderer:(id)renderer;
- (void)showShortsDailyTimerSettingsBottomSheet:(id)sheet;
- (void)shortsDailyTimerActionWhenLockedByParent:(id)parent;
- (id)watchBreakSettingsSectionItem;
- (void)showLockedByParentToast;
- (void)showWatchBreakSettingsCustomPicker;
- (_Bool)watchBreakEnabled;
- (id)watchBreakSettingsDetails;
- (id)navEndpointForActionSheet:(id)sheet;
- (void)attachVEContentsForActionSheet:(id)sheet;
- (void)actionSheetDidDisappear:(id)disappear;
- (id)bedtimeReminderSettingsController;
- (id)bedtimeReminderSettingsSectionItem;
- (void)showBedtimeReminderSettingsPicker;
- (id)bedtimeReminderTitleDescription;
- (_Bool)bedtimeReminderEnabled;
- (void)setBedtimeReminderEnabled:(_Bool)enabled;
- (void)setBedtimeReminderEnabled:(_Bool)enabled animated:(_Bool)animated;
- (void)didTapConfirmEnableBedtimeReminderButton;
- (void)appSettingsStore:(id)store didChangeSetting:(int)setting fromValue:(id)value toValue:(id)value;
- (void)valueDidChangeForKey:(id)key;
- (void)loadCurrentSDUsageAndFreeDiskSpace;
- (void)navigateToViewController:(id)controller;
- (id)parentResponder;
- (void)setBedtimeReminderSettingsController:(id)controller;
- (id)appSettingsStore;
- (void)setAppSettingsStore:(id)store;

@end

