  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTShortsDSPView_h
#define YTShortsDSPView_h
@import Foundation;

#include "UICollectionViewDataSource-Protocol.h"
#include "UICollectionViewDelegate-Protocol.h"
#include "YTShortsDSPCollectionView.h"
#include "YTShortsDSPViewLayout.h"
#include "YTShortsDSPViewModel.h"

@class NSString, UIView;

@interface YTShortsDSPView : UIView <UICollectionViewDataSource, UICollectionViewDelegate> {
    /* instance variables */
    YTShortsDSPCollectionView *_collectionView;
    YTShortsDSPViewLayout *_layout;
}

@property (readonly, copy, nonatomic) YTShortsDSPViewModel *model;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (void)configureWithModel:(id)model;
- (void)setUpCollectionView;
- (id)collectionView:(id)view cellForItemAtIndexPath:(id)path;
- (long long)collectionView:(id)view numberOfItemsInSection:(long long)section;

@end

#endif /* YTShortsDSPView_h */
