//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTSinglePlayerBytesHalftimeLayoutRenderingAdapter_h
#define YTSinglePlayerBytesHalftimeLayoutRenderingAdapter_h
@import Foundation;

#include "YTAdLayout.h"
#include "YTAdSlot.h"
#include "YTAdapterRequirementProtocol-Protocol.h"
#include "YTDAIAdTrackingController.h"
#include "YTDAIAdsPlaybackLifecycleAPI-Protocol.h"
#include "YTExternallyManagedSlotAdapter-Protocol.h"
#include "YTInstreamAd-Protocol.h"
#include "YTInstreamAdBreak-Protocol.h"
#include "YTLayoutRenderingAdapter-Protocol.h"
#include "YTLayoutRenderingAdapterDelegate-Protocol.h"
#include "YTPlaybackSegmentObservableWrapper.h"
#include "YTPlaybackTimeline.h"
#include "YTPlayerResponse.h"
#include "YTSingleAdDAIAdsPlaybackLifecycleEventListener-Protocol.h"

@class NSObject, NSString;

@interface YTSinglePlayerBytesHalftimeLayoutRenderingAdapter : NSObject <YTExternallyManagedSlotAdapter, YTSingleAdDAIAdsPlaybackLifecycleEventListener, YTLayoutRenderingAdapter, YTAdapterRequirementProtocol> {
    /* instance variables */
    id <YTLayoutRenderingAdapterDelegate> _layoutRenderingAdapterDelegate;
    id <YTDAIAdsPlaybackLifecycleAPI> _adsPlaybackLifecycleAPI;
    YTPlaybackTimeline *_playbackTimeline;
    YTAdSlot *_slot;
    YTAdLayout *_layout;
    id <YTInstreamAd> _ad;
    _Bool _isRenderingLayout;
    YTDAIAdTrackingController *_trackingController;
    YTPlayerResponse *_playerResponse;
    NSString *_contentCPN;
    id <YTInstreamAdBreak> _adBreak;
    YTPlaybackSegmentObservableWrapper *_segmentObservableWrapper;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSString *adCPN;

/* class methods */
+ (id)adapterRequirement;

/* instance methods */
- (id)initWithSlot:(id)slot layout:(id)layout layoutRenderingAdapterDelegate:(id)delegate;
- (double)adStartTimeForAdCPN:(id)cpn;
- (id)layout;
- (void)load;
- (void)unload;
- (id)slot;
- (void)startRendering;
- (void)stopRenderingWithExitReason:(unsigned long long)reason;
- (void)maybeRemovePlaybackSegmentForSingleVideoObservable:(id)observable;
- (void)adDidProgressWithMediaIngestionWallTime:(double)time localTime:(double)time adCPN:(id)cpn;
- (void)adSingleVideo:(id)video lifecycleStateDidChangeFromState:(long long)state toState:(long long)state adCPN:(id)cpn;
- (void)serverStitchedAdActivatedWithVideoData:(id)data;
- (void)serverStitchedAdDeactivated;
- (void)singleVideo:(id)video mediaStateDidChangeFromState:(long long)state toState:(long long)state adCPN:(id)cpn;
- (void)adPlaybackDidFailWithError:(id)error adCPN:(id)cpn;
- (void)didSkipAdWithTouchPoint:(struct CGPoint { double x0; double x1; })point;
- (void)didShowSkip;
- (void)adDidMuteWithTouchPoint:(struct CGPoint { double x0; double x1; })point;
- (_Bool)isRenderingLayoutState;
- (id)playbackSegmentObservableWrapper;
- (void)adDidProgressWithLocalTime:(double)time;

@end

#endif /* YTSinglePlayerBytesHalftimeLayoutRenderingAdapter_h */
