  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTSubscriptionProductView_h
#define YTSubscriptionProductView_h
@import Foundation;

#include "GA11YMixinEmbedder-Protocol.h"
#include "GA11YMixinImpl-Protocol.h"
#include "YTCellActionProtocol-Protocol.h"
#include "YTCellLinkDelegate-Protocol.h"
#include "YTCellLinkProtocol-Protocol.h"
#include "YTFormattedStringLabel.h"
#include "YTFormattedStringLabelDelegate-Protocol.h"
#include "YTISubscriptionProductRenderer.h"
#include "YTImageView.h"
#include "YTPageStyleProvider-Protocol.h"
#include "YTPageStyling-Protocol.h"
#include "YTQTMButton.h"
#include "YTReusableView-Protocol.h"
#include "YTThumbnailMapping-Protocol.h"

@class NSMutableArray, NSString, UIView;

@interface YTSubscriptionProductView : UIView <GA11YMixinEmbedder, YTFormattedStringLabelDelegate, YTPageStyling, YTPageStyleProvider, YTReusableView, YTCellLinkProtocol, YTCellActionProtocol, YTThumbnailMapping> {
    /* instance variables */
    YTImageView *_logoImageView;
    UIView *_spacingViewAboveMetadata;
    NSMutableArray *_metadataLabels;
    UIView *_spacingViewAboveAdditionalInfo;
    NSMutableArray *_additionalInfoLabels;
    YTFormattedStringLabel *_descriptionLabel;
    UIView *_separatorViewAbovePrimaryButton;
    UIView *_contentView;
    UIView *_redLine;
}

@property (retain, nonatomic) YTISubscriptionProductRenderer *renderer;
@property (weak, nonatomic) id <YTPageStyleProvider> pageStyleProviderDelegate;
@property (retain, nonatomic) YTQTMButton *primaryButton;
@property (retain, nonatomic) YTQTMButton *menuButton;
@property (readonly, nonatomic) id <GA11YMixinImpl> accessibilityMixin;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) long long pageStyle;
@property (weak, nonatomic) id <YTCellLinkDelegate> cellLinkDelegate;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)prepareForReuse;
- (void)setActionTarget:(id)target action:(SEL)action;
- (void)removeActionTarget;
- (void)setLongPressTarget:(id)target action:(SEL)action;
- (void)removeLongPressTarget;
- (long long)accessibilityElementCount;
- (id)accessibilityElementAtIndex:(long long)index;
- (long long)indexOfAccessibilityElement:(id)element;
- (id)accessibilityElements;
- (_Bool)isAccessibilityElement;
- (id)accessibilityLabel;
- (id)accessibleViews;
- (void)formattedStringLabel:(id)label didPressURL:(id)url;
- (void)formattedStringLabel:(id)label didPressNavigationEndpoint:(id)endpoint linkText:(id)text;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(id)superview;
- (void)pageStyleDidChange:(long long)change;
- (id)thumbnailMappings;
- (void)addMetaDataLabelsFromArray:(id)array;
- (void)addAdditionalInfoLabelsFromArray:(id)array;
- (id)getDescriptionLabel;
- (double)contentWidth;
- (void)didTapPrimaryButton:(id)button;
- (double)cardWidthWithMaxWidth:(double)width;

@end

#endif /* YTSubscriptionProductView_h */
