  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTSUploadFeedbackPollerImpl_h
#define YTSUploadFeedbackPollerImpl_h
@import Foundation;

#include "GIPDispatchTimer.h"
#include "OS_dispatch_queue-Protocol.h"
#include "YTSUploadFeedbackPoller-Protocol.h"

@class NSDate, NSHashTable, NSMutableDictionary, NSObject, NSString;

@interface YTSUploadFeedbackPollerImpl : NSObject <YTSUploadFeedbackPoller>

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *syncQueue;
@property (retain, nonatomic) NSDate *nextPollDate;
@property (retain, nonatomic) GIPDispatchTimer *nextPollTimer;
@property (retain, nonatomic) NSMutableDictionary *polledItemsMap;
@property (retain, nonatomic) NSHashTable *observers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)pollFeedbackForID:(id)id continuation:(id)continuation nextPollDate:(id)date;
- (void)addFeedbackObserver:(id)observer;
- (void)removeFeedbackObserver:(id)observer;
- (void)pollFeedback;
- (void)handlePollResponse:(id)response;
- (void)handleFeedbackItemRenderer:(id)renderer;
- (void)handlePollFailure:(id)failure forIDs:(id)ids;
- (void)maybeScheduleNextPoll;
- (void)notifyObserversWithBlock:(id /* block */)block;

@end

#endif /* YTSUploadFeedbackPollerImpl_h */
