  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTSurveyInterstitialView_h
#define YTSurveyInterstitialView_h
@import Foundation;

#include "YTButton.h"
#include "YTFormattedStringLabel.h"
#include "YTISurveyTextInterstitialRenderer.h"
#include "YTImageView.h"
#include "YTThumbnailMapping-Protocol.h"

@class NSString, UIView;

@interface YTSurveyInterstitialView : UIView <YTThumbnailMapping> {
    /* instance variables */
    YTISurveyTextInterstitialRenderer *_renderer;
    YTImageView *_backgroundImage;
    YTImageView *_brandLogo;
    YTFormattedStringLabel *_introText;
}

@property (readonly, nonatomic) UIView *backgroundTapView;
@property (readonly, nonatomic) YTButton *startButton;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithRenderer:(id)renderer;
- (void)layoutSubviews;
- (id)thumbnailMappings;

@end

#endif /* YTSurveyInterstitialView_h */
