  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTTimeOfDayModel_h
#define YTTimeOfDayModel_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSMutableCopying-Protocol.h"
#include "YTEntityStore-Protocol.h"
#include "YTITimeOfDay.h"

@class NSData, NSObject;

@interface YTTimeOfDayModel : NSObject <NSCopying, NSMutableCopying>

@property (nonatomic) _Bool parseAndExtractFieldsFromProtoData;
@property (nonatomic) _Bool generateData;
@property (copy, nonatomic) YTITimeOfDay *protoBuf;
@property (copy, nonatomic) NSData *data;
@property (readonly, nonatomic) id <YTEntityStore> entityStore;
@property (readonly, nonatomic) _Bool hasHours;
@property (readonly, nonatomic) int hours;
@property (readonly, nonatomic) _Bool hasMinutes;
@property (readonly, nonatomic) int minutes;
@property (readonly, nonatomic) _Bool hasSeconds;
@property (readonly, nonatomic) int seconds;
@property (readonly, nonatomic) _Bool hasNanos;
@property (readonly, nonatomic) int nanos;
@property (readonly, copy, nonatomic) YTITimeOfDay *proto;

/* instance methods */
- (id)initWithEntityStore:(id)store protoBuf:(id)buf;
- (id)initWithEntityStore:(id)store protoBufData:(id)data;
- (id)initWithEntityStore:(id)store entityKey:(id)key protoBuf:(id)buf protoBufData:(id)data;
- (id)init;
- (id)entityVersion;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)allAssociationKeys;
- (id)copy;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopy;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (void)parseAndExtractFieldsFromProtoIfNecessary;
- (void)generateDataIfNecessary;
- (_Bool)isEqualEntityValue:(id)value;

@end

#endif /* YTTimeOfDayModel_h */
