//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTUploadStreamingFMP4Processor_h
#define YTUploadStreamingFMP4Processor_h
@import Foundation;

@class NSObject;

@interface YTUploadStreamingFMP4Processor : NSObject

/* class methods */
+ (id)convertMoovBox:(id)box mdatBoxOffset:(unsigned long long)offset mdatBoxSize:(unsigned long long)size error:(id *)error;
+ (id)adjustMoofBoxDataRef:(id)ref offset:(unsigned long long)offset incrementSeqNum:(_Bool)num error:(id *)error;
+ (id)createPaddingBox:(unsigned long long)box error:(id *)error;

@end

#endif /* YTUploadStreamingFMP4Processor_h */
