  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTVarispeedSwitchControllerImpl_h
#define YTVarispeedSwitchControllerImpl_h
@import Foundation;

#include "YTActionSheetController.h"
#include "YTActionSheetControllerDelegate-Protocol.h"
#include "YTVarispeedSwitchController-Protocol.h"
#include "YTVarispeedSwitchControllerDelegate-Protocol.h"

@class NSArray, NSObject, NSString;

@interface YTVarispeedSwitchControllerImpl : NSObject <YTActionSheetControllerDelegate, YTVarispeedSwitchController> {
    /* instance variables */
    NSArray *_options;
    YTActionSheetController *_actionSheetController;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <YTVarispeedSwitchControllerDelegate> delegate;

/* instance methods */
- (id)init;
- (void)reset;
- (void)showMenuFromView:(id)view;
- (id)selectedVarispeedLabelText;
- (void)actionSheetDidDisappear:(id)disappear cancelAction:(_Bool)action;
- (void)addActionForOption:(id)option;

@end

#endif /* YTVarispeedSwitchControllerImpl_h */
