  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTVideoDismissalController_h
#define YTVideoDismissalController_h
@import Foundation;

#include "YTAlertView.h"
#include "YTCellDismissalController.h"
#include "YTDismissalFollowUpViewModel-Protocol.h"
#include "YTDismissalFollowupView.h"
#include "YTDismissalFollowupViewDelegate-Protocol.h"
#include "YTResponder-Protocol.h"
#include "YTVideoDismissedViewDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface YTVideoDismissalController : YTCellDismissalController <YTDismissalFollowupViewDelegate, YTVideoDismissedViewDelegate, YTResponder> {
    /* instance variables */
    YTDismissalFollowupView *_reasonsView;
    YTAlertView *_reasonsAlertView;
    NSMutableArray *_thumbnailControllers;
    struct CGSize { double width; double height; } _outlineSize;
    long long _style;
    _Bool _didLogDismissalReasons;
    _Bool _showingReasonView;
}

@property (retain, nonatomic) id <YTDismissalFollowUpViewModel> reasonsRenderer;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, weak, nonatomic) id <YTResponder> parentResponder;

/* instance methods */
- (id)initWithEntry:(id)entry parentResponder:(id)responder delegate:(id)delegate;
- (void)didTapDismissalUndoWithRenderer:(id)renderer;
- (void)didTapDismissalFeedbackWithRenderer:(id)renderer;
- (void)didTapDismissalMoreInfoWithRenderer:(id)renderer;
- (_Bool)shouldShrinkDismissalView;
- (void)setupDismissedView;
- (_Bool)shouldUseDismissedSize;
- (void)resizeCell;
- (void)updateContainerAndDismissedViewOnView:(id)view;
- (void)showDismissalOnView:(id)view animated:(_Bool)animated;
- (void)undoDismissCellAnimated:(_Bool)animated;
- (long long)style;
- (long long)style_compact;
- (long long)style_regular;
- (void)prepareReasonsViewWithModalStyle:(_Bool)style;
- (void)showReasonsInline;
- (void)showReasonsModally;
- (void)dismissInlineReasonsWithCompletion:(id /* block */)completion;
- (void)dismissAnyModal;
- (id)moreInfoButtonRendererFromNotificationRenderer:(id)renderer;
- (id)undoButtonRendererFromNotificationRenderer:(id)renderer;
- (id)undoButtonRendererFromDismissalRenderer:(id)renderer;
- (_Bool)showingReasonView;
- (void)showReasons;
- (void)resizeContainerAndReasonsView;
- (void)logDismissalFollowUpRenderer:(id)renderer;
- (void)didTapDismissalFollowupCancelActionWithRenderer:(id)renderer;
- (void)didTapDismissalFollowupSubmitActionWithRenderer:(id)renderer reasonRenderer:(id)renderer;
- (void)didFinishAnnouncement:(id)announcement;
- (void)didTapDismissalFollowupUndoActionWithRenderer:(id)renderer;
- (void)handleSelectedReasonEndpoint:(id)endpoint;
- (void)handleTapWithButtonRenderer:(id)renderer;
- (void)loadThumbnails;

@end

#endif /* YTVideoDismissalController_h */
