  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTVideoPlayerOverlayDelegate_Protocol_h
#define YTVideoPlayerOverlayDelegate_Protocol_h
@import Foundation;

#include "YTPlayerBarViewDelegate-Protocol.h"
#include "YTPlayerMenuProtocol-Protocol.h"

@protocol YTVideoPlayerOverlayDelegate <YTPlayerMenuProtocol, YTPlayerBarViewDelegate>

@required

/* required instance methods */
- (void)userDidSelectCaptionTrack:(id)track source:(long long)source;
- (void)showAddToMenuFromView:(id)view;
- (void)setUserAudioOnlyModeActive:(_Bool)active;
- (void)showLiveChat:(_Bool)chat;
- (_Bool)isShowingLiveChat;
- (void)didDismissModal;
- (void)didPressCopyDebugInfo;
- (void)didSetNerdStatsEnabled:(_Bool)enabled;
- (void)seekToEnd;
- (void)playIfPermitted;
- (void)didSwipeToExitFullscreenWithGesture:(unsigned long long)gesture;
- (void)didSwipeToEnterFullscreen;
- (void)didCancelSwipeToExitFullscreen;
- (void)didRequestToEnterFullscreen;
- (void)setRenderingViewCustomFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame animated:(_Bool)animated duration:(double)duration;
- (void)setRenderingViewCustomTranslation:(struct CGPoint { double x0; double x1; })translation customScale:(double)scale animated:(_Bool)animated duration:(double)duration;
- (void)setPlayerBackgroundColor:(id)color;
- (void)setPinchToRotateEnabled:(_Bool)enabled;
- (void)enableCaptionsIfAvailableWithSource:(long long)source;
- (void)setMuted:(_Bool)muted;

@optional

/* optional instance methods */
- (void)setDoubleTapToSeekState:(_Bool)state;

@end

#endif /* YTVideoPlayerOverlayDelegate_Protocol_h */
