//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTVoiceSearchPlateView_h
#define YTVoiceSearchPlateView_h
@import Foundation;

#include "GSKMicButton.h"
#include "GSKStreamingTextView.h"
#include "QTMActivityIndicator.h"
#include "YTVoiceSearchPlateViewDelegate-Protocol.h"

@class UIButton, UILabel, UIView;

@interface YTVoiceSearchPlateView : UIView

@property (retain, nonatomic) QTMActivityIndicator *activityIndicator;
@property (retain, nonatomic) UIButton *closeButton;
@property (retain, nonatomic) UILabel *tryAgainLabel;
@property (retain, nonatomic) UILabel *errorVoiceTipOne;
@property (retain, nonatomic) UILabel *errorVoiceTipTwo;
@property (retain, nonatomic) UILabel *errorVoiceTipThree;
@property (retain, nonatomic) UILabel *trySayingLabel;
@property (retain, nonatomic) UILabel *listeningVoiceTipsLabel;
@property (weak, nonatomic) id <YTVoiceSearchPlateViewDelegate> delegate;
@property (retain, nonatomic) GSKStreamingTextView *streamingTextView;
@property (retain, nonatomic) UIView *micButtonContainerView;
@property (retain, nonatomic) GSKMicButton *micButton;
@property (nonatomic) long long pageStyle;
@property (nonatomic) _Bool displayAsOverlay;
@property (nonatomic) _Bool showsVoiceTips;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)updateVoiceTips:(id)tips;
- (void)layoutSubviews;
- (void)updateViewWithState:(unsigned long long)state;
- (id)accessibilityElements;
- (void)didTapCloseButton;
- (void)adjustSubviewsLayout;
- (void)setListeningVoiceTipsVisibility:(_Bool)visibility;
- (void)setErrorVoiceTipsVisibility:(_Bool)visibility;
- (id)buildErrorVoiceTipLabel;
- (void)updateMicButtonAccessibility:(_Bool)accessibility;
- (double)navigationBarHeight;

@end

#endif /* YTVoiceSearchPlateView_h */
