  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTVSS3State_h
#define YTVSS3State_h
@import Foundation;

#include "YTCPN.h"

@class NSData, NSObject, NSString;

@interface YTVSS3State : NSObject

@property (readonly, nonatomic) YTCPN *CPN;
@property (readonly, nonatomic) NSString *videoID;
@property (readonly, copy, nonatomic) NSString *hostCPN;
@property (nonatomic) double mediaLength;
@property (nonatomic) _Bool embargoActive;
@property (nonatomic) _Bool muted;
@property (nonatomic) _Bool userAudioOnlyModeActive;
@property (copy, nonatomic) NSString *clipID;
@property (copy, nonatomic) NSData *accountLinkState;
@property (nonatomic) int visibility;
@property (nonatomic) int connectionType;
@property (retain, nonatomic) NSString *captionTrackID;
@property (retain, nonatomic) NSString *audioTrackID;
@property (nonatomic) float playbackRate;
@property (nonatomic) float baselinePlaybackRate;
@property (nonatomic) int outputVolume;
@property (retain, nonatomic) NSData *serializedWatchTimeContextData;
@property (nonatomic) _Bool delayedPlaybackReported;
@property (nonatomic) _Bool reportDelayPlayInNextWatchtimePing;
@property (nonatomic) int formatItag;
@property (nonatomic) int audioFormatItag;
@property (copy, nonatomic) NSData *heartbeatLoggingToken;
@property (nonatomic) int playlistLoopStatus;

/* instance methods */
- (id)initWithCPN:(id)cpn videoID:(id)id mediaLength:(double)length hostCPN:(id)cpn;
- (id)watchTimeSegmentWithCurrentState;
- (_Bool)isEmbargoActive;
- (_Bool)isMuted;
- (_Bool)isUserAudioOnlyModeActive;
- (_Bool)isDelayedPlaybackReported;
- (_Bool)shouldReportDelayPlayInNextWatchtimePing;

@end

#endif /* YTVSS3State_h */
