  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTWatchMiniBarCircularProgressView_h
#define YTWatchMiniBarCircularProgressView_h
@import Foundation;

#include "YTCircularProgressView.h"

@class CAShapeLayer;

@interface YTWatchMiniBarCircularProgressView : YTCircularProgressView

@property (retain, nonatomic) CAShapeLayer *progressBackgroundLayer;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame lineWidth:(double)width fillColor:(struct CGColor *)color lineColor:(struct CGColor *)color lineBackgroundColor:(struct CGColor *)color;
- (void)layoutSubviews;
- (void)cancelProgressAnimation;
- (void)setLineColor:(struct CGColor *)color;
- (void)setLineBackgroundColor:(struct CGColor *)color;
- (void)setProgress:(double)progress;
- (void)animateFromValue:(double)value toValue:(double)value duration:(double)duration;
- (void)configureLineBackgroundWithLineWidth:(double)width lineBackgroundColor:(struct CGColor *)color;
- (_Bool)isAccessibilityElement;

@end

#endif /* YTWatchMiniBarCircularProgressView_h */
