//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTWhosWatchingModel_h
#define YTWhosWatchingModel_h
@import Foundation;

#include "YTIWhosWatchingPageRenderer.h"

@class NSArray, NSObject;

@interface YTWhosWatchingModel : NSObject // (Swift)

@property (nonatomic, readonly) YTIWhosWatchingPageRenderer *pageRenderer;
@property (nonatomic, readonly) NSArray *accountItems;

/* instance methods */
- (id)initWithPageRenderer:(id)renderer accountItems:(id)items;
- (id)init;

@end

#endif /* YTWhosWatchingModel_h */
