  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
  @class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
  @protocol NSObject, NSCopying, NSCoding;
@class NSObject, NSString, NSArray, NSDictionary, UIView, UIViewController; 
@protocol NSObject, NSCopying, NSCoding;
//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.672, BuildCommit: 400d3d0bcbb331f43a3266dd71d67c779f12e7d8)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16, SDK: 26.2, Tool: ld (1230.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef YTYPCHandleIapServiceImpl_h
#define YTYPCHandleIapServiceImpl_h
@import Foundation;

#include "YTAccountScopedBaseInnerTubeRequestService.h"
#include "YTFlowLogger-Protocol.h"
#include "YTInnerTubeResponseParser.h"
#include "YTYPCHandleIapService-Protocol.h"

@class NSString;

@interface YTYPCHandleIapServiceImpl : YTAccountScopedBaseInnerTubeRequestService <YTYPCHandleIapService> {
    /* instance variables */
    YTInnerTubeResponseParser *_resourceParser;
    id <YTFlowLogger> _flowLogger;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithAccountID:(id)id;
- (void)makeRequestWithProto:(id)proto transaction:(id)transaction innerTubeResponseBlock:(id /* block */)block errorBlock:(id /* block */)block;
- (void)internalMakeRequestWithProto:(id)proto innerTubeResponseBlock:(id /* block */)block errorBlock:(id /* block */)block;
- (void)internalMakeRequestWithProtoAndAttestation:(id)attestation innerTubeResponseBlock:(id /* block */)block errorBlock:(id /* block */)block attestationResponseData:(id)data;
- (_Bool)handlesTransactionType:(unsigned long long)type;

@end

#endif /* YTYPCHandleIapServiceImpl_h */
