name: "Sync List"

on:
  push:
    paths:
      - 'src/Build_Tweak/**'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Sync Logic"
        run: |
          TARGET=".github/workflows/build-tweaks.yml"
          
          # Quét danh sách dự án (Giữ nguyên hoa thường AutoAC)
          # Dùng find để an toàn hơn ls
          PROJECTS=$(find src/Build_Tweak -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)
          
          echo "Tìm thấy: $PROJECTS"

          # Tạo danh sách options
          # Dòng đầu tiên là none (mặc định)
          OPTIONS="          - none"
          
          if [ -n "$PROJECTS" ]; then
            ADD_PROJECTS=$(echo "$PROJECTS" | sed 's/^/          - /')
            FINAL_LIST="$OPTIONS"$'\n'"$ADD_PROJECTS"
          else
            FINAL_LIST="$OPTIONS"
          fi

          # Ghi đè: Xóa từ dòng 'options:' đến hết file và thay bằng list mới
          sed -i '/options:/q' "$TARGET"
          echo -e "$FINAL_LIST" >> "$TARGET"

      - name: "Push"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || (git commit -m "sync list" && git push)
