      - name: 🛠️ Xử lý File siêu tốc
        run: |
          FILE_URL="${{ github.event.client_payload.file_url }}"
          FILE_TYPE="${{ github.event.client_payload.file_type }}"
          PROJECT="${{ github.event.client_payload.project }}"
          
          mkdir -p depictions/icons depictions/images debs
          
          case "$FILE_TYPE" in
            "i") PATH="depictions/icons/${PROJECT}.png" ;;
            "b") PATH="depictions/images/${PROJECT}-banner.png" ;;
            "1"|"2"|"3") PATH="depictions/images/${PROJECT}${FILE_TYPE}.png" ;;
            "v") PATH="depictions/images/${PROJECT}.mp4" ;;
            "d") PATH="debs/${PROJECT}.deb" ;;
          esac
          
          curl -L "$FILE_URL" -o "$PATH"
          
          git config user.name "PhapSuAction"
          git config user.email "action@github.com"
          git add .
          git commit -m "⚡ Update $FILE_TYPE cho $PROJECT"
          git push origin main
