name: Auto sync sileo Packages

on:
  push:
    paths:
      - 'debs/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Đảm bảo lấy đủ lịch sử để push không lỗi

      - name: Install dpkg-dev
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Generate Packages
        run: |
          # Kiểm tra nếu thư mục debs tồn tại
          if [ -d "debs" ]; then
            cd debs
            dpkg-scanpackages -m . /dev/null > ../Packages
            cd ..
            bzip2 -kf Packages
            echo "✅ Đã tạo Packages & Packages.bz2"
          else
            echo "❌ Không tìm thấy thư mục debs"
            exit 1
          fi

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update Packages & Packages.bz2 [skip ci]"
          file_pattern: "Packages*"
          branch: main # Đảm bảo push đúng vào nhánh chính
